// One-off dev tool: turns an open Europe GeoJSON into a committed TS module of
// SVG path strings keyed by ISO-3166-1 alpha-2, for the admin Acquisition
// choropleth. NO runtime map dependency (no d3 / topojson) — we bake a simple
// equirectangular projection + point thinning here and ship only the paths.
//
// Usage (the GeoJSON is fetched once, not committed):
//   curl -sL https://raw.githubusercontent.com/leakyMirror/map-of-europe/master/GeoJSON/europe.geojson -o /tmp/europe.geojson
//   bun frontend/scripts/build_europe_map.ts /tmp/europe.geojson
//
// Source: leakyMirror/map-of-europe (derived from public-domain Natural Earth).

import { writeFileSync } from "node:fs";

const src = process.argv[2] ?? "/tmp/europe.geojson";
const OUT = new URL("../src/lib/europeGeo.ts", import.meta.url);

// Equirectangular frame over Europe. Countries whose centroid falls outside the
// keep-box are dropped; anything still off-frame is clipped by the viewBox.
const LON_MIN = -25;
const LON_MAX = 45;
const LAT_MIN = 34;
const LAT_MAX = 72;
const MID_LAT_RAD = (((LAT_MIN + LAT_MAX) / 2) * Math.PI) / 180;
const COS_MID = Math.cos(MID_LAT_RAD);
// k chosen so the projected height is 1000 units.
const K = 1000 / (LAT_MAX - LAT_MIN);
const VW = Math.round((LON_MAX - LON_MIN) * COS_MID * K);
const VH = 1000;
// Point-thinning epsilon (projected units) + min polygon area to keep — drops
// sub-pixel jitter and tiny offshore islands so the file stays small.
const EPS = 1.6;
const MIN_AREA = 3;

function project(lon: number, lat: number): [number, number] {
  const x = (lon - LON_MIN) * COS_MID * K;
  const y = (LAT_MAX - lat) * K;
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
}

function ringToCommands(ring: number[][]): string | null {
  const pts: [number, number][] = [];
  let last: [number, number] | null = null;
  for (const [lon, lat] of ring) {
    const p = project(lon, lat);
    if (last && Math.abs(p[0] - last[0]) < EPS && Math.abs(p[1] - last[1]) < EPS) continue;
    pts.push(p);
    last = p;
  }
  if (pts.length < 4) return null;
  // Shoelace area in projected space — skip specks.
  let area = 0;
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    area += a[0] * b[1] - b[0] * a[1];
  }
  if (Math.abs(area) / 2 < MIN_AREA) return null;
  return `M${pts.map((p) => `${p[0]} ${p[1]}`).join("L")}Z`;
}

function polygonsToPath(rings: number[][][]): string {
  // Outer ring + holes; we render all rings (holes via even-odd would need a
  // fill-rule, but at this scale a country's holes are negligible — keep outer
  // rings only by taking ring[0] of each polygon at the caller).
  return rings
    .map((r) => ringToCommands(r))
    .filter((s): s is string => s !== null)
    .join("");
}

interface Feature {
  properties: Record<string, unknown>;
  geometry: { type: string; coordinates: unknown };
}

const raw = await Bun.file(src).text();
const fc = JSON.parse(raw) as { features: Feature[] };

const paths: Record<string, string> = {};
const names: Record<string, string> = {};

for (const f of fc.features) {
  const iso = String(f.properties.ISO2 ?? "").toUpperCase();
  if (!/^[A-Z]{2}$/.test(iso)) continue;
  const lon = Number(f.properties.LON);
  const lat = Number(f.properties.LAT);
  if (Number.isFinite(lon) && Number.isFinite(lat)) {
    if (lon < LON_MIN - 5 || lon > LON_MAX + 10 || lat < LAT_MIN - 6 || lat > LAT_MAX + 6) {
      continue;
    }
  }
  const g = f.geometry;
  let d = "";
  if (g.type === "Polygon") {
    // Outer ring only (index 0) to keep paths compact.
    d = polygonsToPath([(g.coordinates as number[][][])[0] ?? []]);
  } else if (g.type === "MultiPolygon") {
    const polys = g.coordinates as number[][][][];
    d = polygonsToPath(polys.map((poly) => poly[0] ?? []));
  }
  if (!d) continue;
  paths[iso] = d;
  names[iso] = String(f.properties.NAME ?? iso);
}

const isoSorted = Object.keys(paths).sort();
const body = `// AUTO-GENERATED by frontend/scripts/build_europe_map.ts — do not edit by hand.
// Simplified equirectangular Europe map: SVG path per ISO-3166-1 alpha-2,
// outer rings only, point-thinned. No runtime map dependency. Re-generate by
// re-running the script (see its header) when the country set needs to change.

export const EUROPE_VIEWBOX = "0 0 ${VW} ${VH}";

/** ISO-2 → SVG path (one or more \`M..Z\` subpaths) in the EUROPE_VIEWBOX frame. */
export const EUROPE_PATHS: Record<string, string> = {
${isoSorted.map((iso) => `  ${iso}: ${JSON.stringify(paths[iso])},`).join("\n")}
};

/** ISO-2 → English country name (for tooltips / "other" grouping). */
export const EUROPE_NAMES: Record<string, string> = {
${isoSorted.map((iso) => `  ${iso}: ${JSON.stringify(names[iso])},`).join("\n")}
};
`;

writeFileSync(OUT, body);
const bytes = Buffer.byteLength(body);
console.log(
  `[build_europe_map] wrote ${isoSorted.length} countries, ${(bytes / 1024).toFixed(0)}KB → src/lib/europeGeo.ts (viewBox 0 0 ${VW} ${VH})`,
);
