// One-off dev tool: turns the Natural Earth 110m world GeoJSON into a committed
// TS module of SVG path strings keyed by ISO-3166-1 alpha-2, for the admin
// Acquisition choropleth world view. Same approach as build_europe_map.ts.
//
// Usage:
//   curl -sL https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson -o /tmp/world.geojson
//   bun frontend/scripts/build_world_map.ts /tmp/world.geojson

import { writeFileSync } from "node:fs";

const src = process.argv[2] ?? "/tmp/world.geojson";
const OUT = new URL("../src/lib/worldGeo.ts", import.meta.url);

// Equirectangular world projection, cropping Antarctica below -60° lat.
const LON_MIN = -180;
const LON_MAX = 180;
const LAT_MIN = -60;
const LAT_MAX = 85;
const VW = 1200;
const VH = Math.round((VW * (LAT_MAX - LAT_MIN)) / (LON_MAX - LON_MIN));
const SCALE_X = VW / (LON_MAX - LON_MIN);
const SCALE_Y = VH / (LAT_MAX - LAT_MIN);

// Simplification thresholds — coarser than Europe (110m data, small canvas).
const EPS = 0.8;
const MIN_AREA = 1.5;

function project(lon: number, lat: number): [number, number] {
  const x = (lon - LON_MIN) * SCALE_X;
  const y = (LAT_MAX - lat) * SCALE_Y;
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
}

function ringToCommands(ring: number[][]): string | null {
  const pts: [number, number][] = [];
  let last: [number, number] | null = null;
  for (const [lon, lat] of ring) {
    if (lon < LON_MIN || lon > LON_MAX || lat < LAT_MIN || lat > LAT_MAX) continue;
    const p = project(lon, lat);
    if (last && Math.abs(p[0] - last[0]) < EPS && Math.abs(p[1] - last[1]) < EPS) continue;
    pts.push(p);
    last = p;
  }
  if (pts.length < 4) return null;
  let area = 0;
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i];
    const b = pts[(i + 1) % pts.length];
    area += a[0] * b[1] - b[0] * a[1];
  }
  if (Math.abs(area) / 2 < MIN_AREA) return null;
  return `M${pts.map((p) => `${p[0]} ${p[1]}`).join("L")}Z`;
}

function polygonsToPath(rings: number[][][]): string {
  return rings
    .map((r) => ringToCommands(r))
    .filter((s): s is string => s !== null)
    .join("");
}

interface Feature {
  properties: Record<string, unknown>;
  geometry: { type: string; coordinates: unknown };
}

const raw = await Bun.file(src).text();
const fc = JSON.parse(raw) as { features: Feature[] };

const paths: Record<string, string> = {};
const names: Record<string, string> = {};

for (const f of fc.features) {
  // Natural Earth uses ISO_A2; fall back to ADM0_A3 for the few missing ones.
  let iso = String(f.properties.ISO_A2 ?? "").toUpperCase();
  if (iso === "-99" || !/^[A-Z]{2}$/.test(iso)) {
    // Try FIPS_10 or skip
    iso = String(f.properties.ISO_A2_EH ?? "").toUpperCase();
    if (iso === "-99" || !/^[A-Z]{2}$/.test(iso)) continue;
  }

  const g = f.geometry;
  let d = "";
  if (g.type === "Polygon") {
    d = polygonsToPath([(g.coordinates as number[][][])[0] ?? []]);
  } else if (g.type === "MultiPolygon") {
    const polys = g.coordinates as number[][][][];
    d = polygonsToPath(polys.map((poly) => poly[0] ?? []));
  }
  if (!d) continue;
  paths[iso] = d;
  names[iso] = String(f.properties.NAME ?? f.properties.ADMIN ?? iso);
}

const isoSorted = Object.keys(paths).sort();
const body = `// AUTO-GENERATED by frontend/scripts/build_world_map.ts — do not edit by hand.
// Simplified equirectangular world map: SVG path per ISO-3166-1 alpha-2,
// outer rings only, point-thinned. No runtime map dependency. Re-generate by
// re-running the script (see its header) when the country set needs to change.

export const WORLD_VIEWBOX = "0 0 ${VW} ${VH}";

/** ISO-2 → SVG path (one or more \`M..Z\` subpaths) in the WORLD_VIEWBOX frame. */
export const WORLD_PATHS: Record<string, string> = {
${isoSorted.map((iso) => `  ${iso}: ${JSON.stringify(paths[iso])},`).join("\n")}
};

/** ISO-2 → English country name (for tooltips). */
export const WORLD_NAMES: Record<string, string> = {
${isoSorted.map((iso) => `  ${iso}: ${JSON.stringify(names[iso])},`).join("\n")}
};

/** Set of ISO-2 codes that appear in the Europe choropleth (for detecting
 *  "outside Europe" signups and switching to the world view). */
export const EUROPE_ISO_SET = new Set([
  "AL","AD","AT","BY","BE","BA","BG","HR","CY","CZ","DK","EE","FI","FR","DE",
  "GR","HU","IS","IE","IT","XK","LV","LI","LT","LU","MK","MT","MD","MC","ME",
  "NL","NO","PL","PT","RO","RU","SM","RS","SK","SI","ES","SE","CH","TR","UA","GB","VA",
]);
`;

writeFileSync(OUT, body);
const bytes = Buffer.byteLength(body);
console.log(
  `[build_world_map] wrote ${isoSorted.length} countries, ${(bytes / 1024).toFixed(0)}KB → src/lib/worldGeo.ts (viewBox 0 0 ${VW} ${VH})`,
);
