// Generated from public Austrian business-directory results, August 2026.
// Contact, discovery and official image sources are retained in the research report.

import type { RawDirectoryEntry } from "./suppliers_data";

export const AUSTRIA_GSOL_2026_08: RawDirectoryEntry[] = [
  {
    id: "at26-gsol-perfekte-hochzeit-linda-hollnbuchner-pcghd",
    name: "Perfekte Hochzeit Linda Hollnbuchner",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Rotenmühlgasse 7/Top1, 1120",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Perfekte Hochzeit Linda Hollnbuchner esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Perfekte Hochzeit Linda Hollnbuchner is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.perfektehochzeit.at/",
    gallery_urls: [
      "https://perfektehochzeit.at/wp-content/uploads/2023/08/1016196-0276-720dpi-scaled-1-1024x680.webp",
      "https://perfektehochzeit.at/wp-content/uploads/2023/08/tanja%E2%88%9Edennis_2022_09_16_058527-1024x683.webp",
      "https://perfektehochzeit.at/wp-content/uploads/2023/08/tanja%E2%88%9Edennis_2022_09_16_048424-1024x683.webp",
      "https://perfektehochzeit.at/wp-content/uploads/2023/08/TheWeddingPhotographer_EkaterinaAlexey_1278-jpg.webp",
    ],
    contact_email: "linda@perfektehochzeit.at",
    contact_phone: "+43664/5010858",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-das-hochzeitskastell-kjacp",
    name: "Das Hochzeitskastell",
    category: "photography",
    city: "Hirm, AT",
    address: "Hauptplatz 2, 7024",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Das Hochzeitskastell esküvői szolgáltató Hirm településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Das Hochzeitskastell is a wedding vendor based in Hirm. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://dashochzeitskastell.at/",
    gallery_urls: [
      "https://dashochzeitskastell.at/wp-content/uploads/2026/04/8-MARTINA_HECHT-Photography_8-440x660.jpg",
      "https://dashochzeitskastell.at/wp-content/uploads/2026/04/12-MARTINA_HECHT-Photography_12-440x660.jpg",
      "https://dashochzeitskastell.at/wp-content/uploads/2026/04/37-TE_Martina-Hecht_1-10-440x660.jpg",
      "https://dashochzeitskastell.at/wp-content/uploads/2026/04/22-Martina-Hecht_1-4-440x660.jpg",
    ],
    contact_email: "office@dashochzeitskastell.at",
    contact_phone: "+43676/3465886",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-hochzeitsfotograf-salzburg-muamer-sarajlic-yszij",
    name: "Hochzeitsfotograf Salzburg - Muamer Sarajlic",
    category: "photography",
    city: "Hallein, AT",
    address: "Zellerweg 6, 5400",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Hochzeitsfotograf Salzburg - Muamer Sarajlic esküvői szolgáltató Hallein településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Hochzeitsfotograf Salzburg - Muamer Sarajlic is a wedding vendor based in Hallein. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.foto-muamer.at/",
    gallery_urls: [
      "https://www.foto-muamer.at/wp-content/uploads/schwarzweiss-hochzeit-waldfoto-mattsee-schloss-brautpaar.jpg",
      "https://www.foto-muamer.at/wp-content/uploads/portrait-hochzeitsfotograf-hallein-salzburger-hochzeitsfotografie-studiofotograf-960x1200.jpg",
      "https://www.foto-muamer.at/wp-content/uploads/Hochzeitsfotos-emotionen-salzburg-1200x1020.jpg",
      "https://www.foto-muamer.at/wp-content/uploads/hochzeitsfoto-spalier-testimonial-bewertung-schloss-mirabell-brautpaar.jpg",
    ],
    contact_email: "online@foto-muamer.at",
    contact_phone: "+43664/99908698",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-markus-posch-wcbog",
    name: "Markus Posch",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Meissauergasse 2A/2/75, 1220",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Markus Posch esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Markus Posch is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.markusposch.com",
    gallery_urls: [
      "https://gelbe-seiten-online.at/media_at/01909/019090575/galerien/Galerie/posch1.jpg",
      "https://gelbe-seiten-online.at/media_at/01909/019090575/staticmap.png",
    ],
    contact_email: "posch.markus@hotmail.com",
    contact_phone: "+43676/3640293",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-thomas-oberascher-photography-exnva",
    name: "Thomas Oberascher Photography",
    category: "photography",
    city: "Haslach, AT",
    address: "Überfuhrstraße 7, 5061",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Thomas Oberascher Photography esküvői szolgáltató Haslach településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Thomas Oberascher Photography is a wedding vendor based in Haslach. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://thomasoberascher.com/",
    gallery_urls: [
      "https://thomasoberascher.com/wp-content/uploads/2024/02/freie-trauung-sonnalm-kitzbuehl-00072.jpg",
      "https://thomasoberascher.com/wp-content/uploads/2024/03/hero-shot-00001.jpg",
      "https://thomasoberascher.com/wp-content/uploads/2024/03/hero-shot-00002.jpg",
      "https://thomasoberascher.com/wp-content/uploads/2024/03/hero-shot-00003.jpg",
    ],
    contact_email: "hello@thomasoberascher.com",
    contact_phone: "+43699/18856789",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-marcus-stephan-buchberger-puvyh",
    name: "Marcus Stephan Buchberger",
    category: "photography",
    city: "Graz, AT",
    address: "Stenggstraße 59/11, 8043",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Marcus Stephan Buchberger esküvői szolgáltató Graz településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Marcus Stephan Buchberger is a wedding vendor based in Graz. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://marcusbuchberger.com/",
    gallery_urls: [
      "https://marcusbuchberger.com/wp-content/uploads/Obstbau-Haas-in-Gnas-094-768x1152.jpg",
      "https://marcusbuchberger.com/wp-content/uploads/Kloster-Neustift-Vahrn-155-768x1152.jpg",
    ],
    contact_email: "contact@marcusbuchberger.com",
    contact_phone: "+43664/4824399",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-onn-events-weddings-ajdil",
    name: "ONN Events&Weddings",
    category: "entertainment",
    city: "Kottingbrunn, AT",
    address: "Schloss 2/2, 2542",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "ONN Events&Weddings esküvői szolgáltató Kottingbrunn településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "ONN Events&Weddings is a wedding vendor based in Kottingbrunn. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://onn-events.com/",
    gallery_urls: [
      "https://onn-events.com/wp-content/uploads/2026/04/fb.jpg",
      "https://onn-events.com/wp-content/uploads/2025/07/Hochzeit_Slider3.jpg",
      "https://onn-events.com/wp-content/uploads/2025/07/Hochzeit_Slider1.jpg",
      "https://onn-events.com/wp-content/uploads/2025/07/Hochzeit_Slider2.jpg",
    ],
    contact_email: "nina@onn-events.com",
    contact_phone: "+43664/1506868",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-michael-schartner-wedding-photographer-xhqsn",
    name: "Michael Schartner Wedding Photographer",
    category: "photography",
    city: "Adnet, AT",
    address: "Adnet 159, 5421",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Michael Schartner Wedding Photographer esküvői szolgáltató Adnet településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Michael Schartner Wedding Photographer is a wedding vendor based in Adnet. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://michaelschartner.com/",
    gallery_urls: [
      "https://images.squarespace-cdn.com/content/v1/674185bd5a65612eb8c525f8/cbf99e92-98cb-435f-9d87-6ba976994bad/Michael+Schartner+Wedding+Photography+Hochzeitsfotograf-082.jpg",
      "https://images.squarespace-cdn.com/content/v1/674185bd5a65612eb8c525f8/d535df24-9d70-417e-9487-d30316c173ff/Michael+Schartner+Wedding+Photography+Hochzeitsfotograf-121.jpg",
      "https://images.squarespace-cdn.com/content/v1/674185bd5a65612eb8c525f8/8329c2b2-a939-4238-8c50-1d48aba971c1/Michael+Schartner+Wedding+Photography+Hochzeitsfotograf-004.jpg",
      "https://images.squarespace-cdn.com/content/v1/674185bd5a65612eb8c525f8/da8588ac-4136-45a8-b1a6-f62c8a1d8c25/Michael+Schartner+Wedding+Photography+Hochzeitsfotograf-019.jpg",
    ],
    contact_email: "contact@michaelschartner.com",
    contact_phone: "+43660/2721992",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-florentina-blumen-kunst-ozkqe",
    name: "Florentina -Blumen & Kunst",
    category: "florist",
    city: "Linz, AT",
    address: "Eisenhandstrasse 51, 4020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Florentina -Blumen & Kunst esküvői szolgáltató Linz településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Florentina -Blumen & Kunst is a wedding vendor based in Linz. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.florentina-blumen.at",
    gallery_urls: [
      "https://www.florentina-blumen.at/wp-content/uploads/2019/04/img1.jpg",
      "https://florentina-blumen.at/wp-content/uploads/2019/06/42876485_1701741649936603_1168227466674700288_n.jpg",
      "https://florentina-blumen.at/wp-content/uploads/2019/04/72575f7f-2c5c-4bc5-a978-355b3d687b3d.jpg",
    ],
    contact_email: "info@florentina-blumen.at",
    contact_phone: "+43732/777216",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-profihero-at-anpvb",
    name: "Profihero.at",
    category: "catering",
    city: "Wien, AT",
    address: "Boschstraße 19/72/12, 1190",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Profihero.at esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Profihero.at is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://profihero.at/",
    gallery_urls: [
      "https://gelbe-seiten-online.at/media_at/01909/019091513/galerien/Galerie/profi1_6335f.jpg",
      "https://gelbe-seiten-online.at/media_at/01909/019091513/staticmap.png",
    ],
    contact_email: "info@profihero.at",
    contact_phone: "+431/4120078",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-coverage-hochzeits-und-eventband-pdnps",
    name: "Coverage - Hochzeits- und Eventband",
    category: "live_music",
    city: "Pasching, AT",
    address: "Birnenweg 24, 4061",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Coverage - Hochzeits- und Eventband esküvői szolgáltató Pasching településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Coverage - Hochzeits- und Eventband is a wedding vendor based in Pasching. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.coverage.co.at/",
    gallery_urls: [
      "https://www.coverage.co.at/wp-content/uploads/Unplugged-Duo-fuer-Hochzeit.jpg",
      "https://www.coverage.co.at/wp-content/uploads/Coverage-Live-Musik-fuer-Events-1.jpg",
    ],
    contact_email: "office@coverage.co.at",
    contact_phone: "+43699/11110334",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-agentur-traumhochzeit-saskia-schedlbauer-cotnq",
    name: "Agentur Traumhochzeit - Saskia Schedlbauer",
    category: "wedding_planner",
    city: "Stainz, AT",
    address: "Erzherzog-Johann-Strasse 3, 8510",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Agentur Traumhochzeit - Saskia Schedlbauer esküvői szolgáltató Stainz településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Agentur Traumhochzeit - Saskia Schedlbauer is a wedding vendor based in Stainz. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.agentur-traumhochzeit.at",
    gallery_urls: [
      "https://agentur-traumhochzeit.de/wp-content/uploads/Bild-Kapitel-1-Bedeutung-Eheschliessung.jpg",
      "https://agentur-traumhochzeit.de/wp-content/uploads/Bild-Kapitel-1-Bedeutung-Eheschliessung-683x1024.jpg",
      "https://agentur-traumhochzeit.de/wp-content/uploads/Agentur-Traumhochzeit-SM_004_MichaelaKlose-683x1024.jpg",
      "https://agentur-traumhochzeit.de/wp-content/uploads/Agentur-Traumhochzeit-Bild-Kapitel-10-Andreas-Nusch-684x1024.jpg",
    ],
    contact_email: "s.schedlbauer@agentur-traumhochzeit.at",
    contact_phone: "+433463/21600",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-evoy-dekor-kg-ijsxr",
    name: "Evoy Dekor KG",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Laxenburgerstrasse 22, 1100",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Evoy Dekor KG esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Evoy Dekor KG is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.evoydekor.at",
    gallery_urls: [
      "https://www.evoydekor.at/uploads/MzjVfQmM/640x640_640x640/121000202_3917660254928176_1372726532292316340_n_Web.jpg",
      "https://www.evoydekor.at/uploads/gn86RvSG/640x640_640x640/127036813_4059606750733525_7366320779143226813_o.jpg",
    ],
    contact_email: "office@evoydekor.com",
    contact_phone: "+431/8903130",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-magical-weddings-events-badfs",
    name: "Magical Weddings & Events",
    category: "wedding_planner",
    city: "Kottingbrunn, AT",
    address: "Schubertgasse 12a, 2542",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Magical Weddings & Events esküvői szolgáltató Kottingbrunn településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Magical Weddings & Events is a wedding vendor based in Kottingbrunn. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://magical-weddings.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01909/019091230/staticmap.png"],
    contact_email: "melanie@magical-weddings.at",
    contact_phone: "+43681/84024087",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-personal-weddings-x-celents-ecdkt",
    name: "PERSONAL WEDDINGS X CELENTS",
    category: "wedding_planner",
    city: "Langenzersdorf, AT",
    address: "Rebschulgasse 6/2/6, 2103",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "PERSONAL WEDDINGS X CELENTS esküvői szolgáltató Langenzersdorf településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "PERSONAL WEDDINGS X CELENTS is a wedding vendor based in Langenzersdorf. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://personal-weddings.at/",
    gallery_urls: [
      "https://personal-weddings.at/wp-content/uploads/2025/02/Denise-Carmen_Wien_Hochzeitsfotograf_schloss-hof_hochzeitslocation-wien_schloss-hof_018.jpg",
      "https://personal-weddings.at/wp-content/uploads/2025/02/slideshow-39.jpg",
      "https://personal-weddings.at/wp-content/uploads/2025/06/linefotografie-10-29-24-Celents-22.jpg",
      "https://personal-weddings.at/wp-content/uploads/2025/02/Denise-Carmen_Wien_Hochzeitsfotograf_schloss-hof_hochzeitslocation-wien_schloss-hof_160.jpg",
    ],
    contact_email: "info@personal-weddings.at",
    contact_phone: "+43664/1584999",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-freie-redner-agentur-dfugt",
    name: "Freie Redner Agentur",
    category: "celebrant",
    city: "Reichraming, AT",
    address: "Weißenbachstraße 10, 4462",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Freie Redner Agentur esküvői szolgáltató Reichraming településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Freie Redner Agentur is a wedding vendor based in Reichraming. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.simone-nussbaumer.at/",
    gallery_urls: [
      "https://image.jimcdn.com/app/cms/image/transf/none/path/sc6ed7da863d8605b/backgroundarea/ic6d72030917a8bbf/version/1669537758/image.jpg",
    ],
    contact_email: "mail@simone-nussbaumer.at",
    contact_phone: "+43681/81206350",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-evelyn-schmid-fotografie-pduua",
    name: "Evelyn Schmid Fotografie",
    category: "photography",
    city: "Wien, AT",
    address: "Kernstraße 7/14, 1120",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Evelyn Schmid Fotografie esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Evelyn Schmid Fotografie is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.evelynschmidfotografie.com/",
    gallery_urls: [
      "https://image.jimcdn.com/app/cms/image/transf/dimension=1920x1024:format=jpg/path/s1c2f515954e2dff7/image/i4ca8114b4fd4bc81/version/1786691954/portr%C3%A4t-der-hochzeitsfotografin-evelyn-schmid.jpg",
      "https://image.jimcdn.com/app/cms/image/transf/dimension=1357x10000:format=jpg/path/s1c2f515954e2dff7/image/i60d340647f82678a/version/1784706773/die-hochzeitsfotografin-evelyn-schmid-stellt-sich-vor-das-zitat-lautet-ich-werde-euch-nicht-den-ganzen-tag-sagen-wie-ihr-stehen-oder-schauen-sollt-genie%C3%9Ft-eure-hochzeit-um-die-bilder-k%C3%BCmmere-ich-mich.jpg",
      "https://image.jimcdn.com/app/cms/image/transf/dimension=1365x10000:format=jpg/path/s1c2f515954e2dff7/image/ie694ef76d78e295c/version/1783062030/emotionale-freie-trauung-in-der-pfalz-mit-jubelnden-hochzeitsg%C3%A4sten-beim-auszug-des-brautpaars.jpg",
    ],
    contact_email: "evelynschmidfotografie@gmail.com",
    contact_phone: "+43677/61110258",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-wedinx-vzley",
    name: "Wedinx",
    category: "photography",
    city: "Wien, AT",
    address: "Axel-Corti-Gasse 12, 1210",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Wedinx esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Wedinx is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.wedinx.com/",
    gallery_urls: [
      "https://www.wedinx.com/wp-content/uploads/2023/10/shutterstock_132324362-1200x825-1.jpeg",
      "https://www.wedinx.com/wp-content/uploads/2023/10/p3-img-10.jpeg",
      "https://www.wedinx.com/wp-content/uploads/2023/10/Hochzeitsfotograf-Wien.jpg",
      "https://www.wedinx.com/wp-content/uploads/2023/10/Wein-Hochzeitsfotograf.jpg",
    ],
    contact_email: "hello@wedinx.com",
    contact_phone: "+43699/17699919",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-stefan-pallek-photography-dkada",
    name: "Stefan Pallek Photography",
    category: "photography",
    city: "Hörsching, AT",
    address: "Holunderweg 7, 4063",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Stefan Pallek Photography esküvői szolgáltató Hörsching településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Stefan Pallek Photography is a wedding vendor based in Hörsching. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.stefanpallek.at/",
    gallery_urls: [
      "https://www.stefanpallek.at/wp-content/uploads/2024/12/hochzeit-tm-eidenberger-alm-040-brautpaar.jpg",
      "https://www.stefanpallek.at/wp-content/uploads/2026/03/hochzeit-hoamat-brautpaar-am-see-01.jpg",
      "https://www.stefanpallek.at/wp-content/uploads/2024/12/hochzeit-eidenbergeralm-brautpaar-shooting-15.jpg",
      "https://www.stefanpallek.at/wp-content/uploads/2024/12/hochzeit-presshaus-aschach-05.jpg",
    ],
    contact_email: "office@stefanpallek.at",
    contact_phone: "+43699/10251060",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-lechner-kuchentechnik-gmbh-qplqu",
    name: "Lechner Küchentechnik GmbH",
    category: "catering",
    city: "Sankt Florian am Inn, AT",
    address: "Bubing 129, 4782",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Lechner Küchentechnik GmbH esküvői szolgáltató Sankt Florian am Inn településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Lechner Küchentechnik GmbH is a wedding vendor based in Sankt Florian am Inn. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.lechner-kuechentechnik.com/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/00014/000144214/staticmap.png"],
    contact_email: "info@lechner-kuechentechnik.com",
    contact_phone: "+437712/29099",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-hochzeitswerkstatt-c016b",
    name: "Hochzeitswerkstatt",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Wallrißstraße 7, 1180",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Hochzeitswerkstatt esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Hochzeitswerkstatt is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://hochzeitswerkstatt.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01782/017824454/staticmap.png"],
    contact_email: "office@hochzeitswerkstatt.at",
    contact_phone: "+43720/512168",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-trau-dich-at-hochzeitsplaner-fur-das-salzkammerg-c9fc4",
    name: "trau-dich.at Hochzeitsplaner für das Salzkammergut",
    category: "wedding_planner",
    city: "Bad Goisern am Hallstättersee, AT",
    address: "Posern 78, 4822",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "trau-dich.at Hochzeitsplaner für das Salzkammergut esküvői szolgáltató Bad Goisern am Hallstättersee településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "trau-dich.at Hochzeitsplaner für das Salzkammergut is a wedding vendor based in Bad Goisern am Hallstättersee. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.trau-dich.at/",
    gallery_urls: [
      "https://static.wixstatic.com/media/2e0b46_2973a78858824e32abb453fcb9ee6755%7Emv2_d_4188_2787_s_4_2.jpg/v1/fit/w_2500,h_1330,al_c/2e0b46_2973a78858824e32abb453fcb9ee6755%7Emv2_d_4188_2787_s_4_2.jpg",
      "https://static.parastorage.com/services/editor-elements-library/dist/thunderbolt/media/sloppyframe.3214ce8e.png",
    ],
    contact_email: "info@trau-dich.at",
    contact_phone: "+43699/19066266",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-gabi-socher-hochzeitsplaner-sag-ja-cd0c3",
    name: "Gabi Socher Hochzeitsplaner - sag ja",
    category: "wedding_planner",
    city: "Gmunden, AT",
    address: "Ort 1, 4810",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Gabi Socher Hochzeitsplaner - sag ja esküvői szolgáltató Gmunden településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Gabi Socher Hochzeitsplaner - sag ja is a wedding vendor based in Gmunden. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.sagJa.at",
    gallery_urls: [
      "https://sagja-im-salzkammergut.at/wp-content/uploads/2023/12/inspo00070.jpg",
      "https://sagja-im-salzkammergut.at/wp-content/uploads/2024/08/Gmundnerberghaus_Foto_brandingbrothers_2024_04_GBH-114.jpg",
      "https://sagja-im-salzkammergut.at/wp-content/uploads/2023/09/pexels-agung-pandit-wiguna-2085524-min.jpg",
      "https://sagja-im-salzkammergut.at/wp-content/uploads/2023/09/www.sagja-im-salzkammergut.at_Zopf-Photography_DSC3740-1-min.jpg",
    ],
    contact_email: "gabi.socher@schlossort.at",
    contact_phone: "+43664/4634898",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-hochzeitsplaner-fur-salzburg-und-das-seengebiet--0b5bf",
    name: "Hochzeitsplaner für Salzburg und das Seengebiet Daniela Kainz",
    category: "wedding_planner",
    city: "Salzburg, AT",
    address: "Auerspergstraße 37, 5020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Hochzeitsplaner für Salzburg und das Seengebiet Daniela Kainz esküvői szolgáltató Salzburg településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Hochzeitsplaner für Salzburg und das Seengebiet Daniela Kainz is a wedding vendor based in Salzburg. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.weddingsalzburg.at",
    gallery_urls: [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidoAnlnFYGTwqwgdDjZVxoJtT4gDyuN3V5QKVfvuw20bj6y47VuBfsEpLSTzfDow9MXqvp66XzPsMtg74RBaUnWMkHf6OBFDykEGFT6otxK0BA9OnvVyryPf8964K0NxyDKDqoBovpOnzE10pGQJe_K9m6mEyk1_oiLMecg9N50V_8UvOTvsxYjSqwOpI/w428-h640/Weddingplanner%20Salzburg%20Schloss%20Leopoldskron%20Table%20Plan.jpg",
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgXj0azuLUlwQYTzQnG2n2KkHok1Y8pWHhzsZ1vNpEfCXuuhLenCuhoesUpkZwXC8_PCiBtGNkmm0UhvW_uJEgAfsK5-mbD05_unRn_YbibdgqSnmTjQ6iQKLG2SSfW_leoXm6MgliTPsGPjgKmi8Kxe3ZensQ1FtK40yvpz_3Q_YGuzOQ0r5w1Ef8-Uhk/w428-h640/Weddingplanner%20Salzburg%20Schloss%20Prielau%20(5).jpg",
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHva8QZwK83-ZFtOS_mG0d3vit7Lx2LRuE7qY-QeI1V7r0RQAoF10Ymc6iAP0_HwtiKjk18IoxE7uyUQjz3lXqwN-zaehRfnk7KSj3GV7IoRRAOH_0HJzi6C3qohjyAHijxJ0qibSCYX1otKQfOUl11awlgcZi5jvflLhSkoIEBwiCW4Wo5ftN21pl4ik/w426-h640/Weddingplanner%20Salzburg%20Schloss%20Prielau%20(3).jpg",
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEifoTiIA4_XSkmc87xn_1vHi8O6-YWb2lAPI8bsHxakIQ9oDdnNsZcbEx0nuhuC1_IIOs5JNDAymYe_CDQNu_1eJA_l7FVqi84zFlWibk0AptEq16V04VZc974LZrWFlVmJI2od8bDIJuwaRG6vz9rMh07SqyZD0rlkLMs_tkuxyiQa7iD8Wdp4VVPgDY8/w428-h640/Weddingplanner%20Salzburg%20Schloss%20Prielau%20(9).jpg",
    ],
    contact_email: "daniela@weddingsalzburg.at",
    contact_phone: "+43664/3076997",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-hochzeitshummel-festorganisation-und-beratun-c4156",
    name: "Die HochzeitsHummel Festorganisation und Beratung Susanne Hummel",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Vösendorfer Straße 119, 1230",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Die HochzeitsHummel Festorganisation und Beratung Susanne Hummel esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Die HochzeitsHummel Festorganisation und Beratung Susanne Hummel is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.hochzeitshummel.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918572/staticmap.png"],
    contact_email: "info@hochzeitshummel.at",
    contact_phone: "+43699/10008655",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-creativ-hochzeitsorganisation-mag-astrid-seiser-ce69b",
    name: "Creativ Hochzeitsorganisation Mag. Astrid Seiser",
    category: "wedding_planner",
    city: "Pfaffenhofen, AT",
    address: "Seiserweg 85, 6405",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Creativ Hochzeitsorganisation Mag. Astrid Seiser esküvői szolgáltató Pfaffenhofen településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Creativ Hochzeitsorganisation Mag. Astrid Seiser is a wedding vendor based in Pfaffenhofen. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.creativhochzeit.com/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918580/staticmap.png"],
    contact_email: "info@creativhochzeit.com",
    contact_phone: "+435262/64167",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-kalligrafie-kunzenmann-eva-maria-d5ffc",
    name: "KALLIGRAFIE Kunzenmann Eva-Maria",
    category: "wedding_planner",
    city: "Hall in Tirol, AT",
    address: "Eugenstraße 11, 6060",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "KALLIGRAFIE Kunzenmann Eva-Maria esküvői szolgáltató Hall in Tirol településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "KALLIGRAFIE Kunzenmann Eva-Maria is a wedding vendor based in Hall in Tirol. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.kalligrafieraum.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918574/staticmap.png"],
    contact_email: "mail@kalligrafieraum.at",
    contact_phone: "+43664/2835407",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-donabauer-barbara-wedding-planner-b0bcc",
    name: "Donabauer Barbara - Wedding Planner",
    category: "wedding_planner",
    city: "Salzburg, AT",
    address: "Forellenweg 55, 5020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Donabauer Barbara - Wedding Planner esküvői szolgáltató Salzburg településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Donabauer Barbara - Wedding Planner is a wedding vendor based in Salzburg. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.donabauer.org/de/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918571/staticmap.png"],
    contact_email: "office@donabauer.org",
    contact_phone: "+43662/4328410",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-traumplan-mag-a-agnes-trippel-eventagentur-cf1e5",
    name: "Traumplan Mag.a Agnes Trippel Eventagentur",
    category: "wedding_planner",
    city: "Mödling, AT",
    address: "Quellenstraße 15, 2340",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Traumplan Mag.a Agnes Trippel Eventagentur esküvői szolgáltató Mödling településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Traumplan Mag.a Agnes Trippel Eventagentur is a wedding vendor based in Mödling. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.traumplan.at/",
    gallery_urls: [
      "https://www.traumplan.at/poazibun/2021/02/Thallern_147.jpg",
      "https://www.traumplan.at/poazibun/2021/02/Foto-18.10.20-15-42-27-min-scaled.jpg",
      "https://www.traumplan.at/poazibun/2019/02/Hochzeit-Andrea-und-Alexander-0401.jpg",
      "https://www.traumplan.at/poazibun/2019/02/Styled-Shoot-Sch%C3%B6nbrunn_017.jpg",
    ],
    contact_email: "office@traumplan.at",
    contact_phone: "+43699/17194440",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-yildiz-dekor-3695c",
    name: "Yildiz Dekor",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Wiener Neustädter Straße 221-233, 1230",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Yildiz Dekor esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Yildiz Dekor is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.dekoverleih.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01782/017824459/staticmap.png"],
    contact_email: "office@yildizdekor.at",
    contact_phone: "+431/3471037",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-prime-moments-exclusive-weddings-events-c4b7f",
    name: "Prime Moments exclusive weddings & events",
    category: "wedding_planner",
    city: "Salzburg, AT",
    address: "Dreifaltigkeitsgasse 16, 5020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Prime Moments exclusive weddings & events esküvői szolgáltató Salzburg településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Prime Moments exclusive weddings & events is a wedding vendor based in Salzburg. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.prime-moments.com",
    gallery_urls: [
      "http://www.prime-moments.com/fileadmin/user_upload/117.jpg",
      "http://www.prime-moments.com/fileadmin/_processed_/csm_Bildschirmfoto_2014-10-07_um_09.49.57_c236af7c4d.png",
      "http://www.prime-moments.com/fileadmin/_processed_/csm_117_aaf7686eb7.jpg",
      "http://www.prime-moments.com/fileadmin/_processed_/csm_js419_cdf75b144d.jpg",
    ],
    contact_email: "jc@prime-moments.com",
    contact_phone: "+43662/870373",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-momentino-at-50301",
    name: "momentino.at",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Laudongasse 16, 1080",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "momentino.at esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "momentino.at is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.momentino.at",
    gallery_urls: [
      "https://momentino.at/cdn/shop/files/momentino-goldensummer-berge_1024x.jpg?v=1775917648",
      "https://momentino.at/cdn/shop/files/Momentino-yoga-wandern-knappenhof_jpg_1024x.jpg?v=1765790745",
      "https://momentino.at/cdn/shop/files/IMG_2244_720x_jpg_2_957c788e-e782-4c23-9566-7a502318c1ad_720x_jpg_1024x.jpg?v=1776088265",
      "https://momentino.at/cdn/shop/files/yoga-am-steg-web_jpg_cdebee66-f7e3-4362-85d5-a39de3887b6a_720x_jpg_1024x.jpg?v=1776088394",
    ],
    contact_email: "denisa.becker@momentino.at",
    contact_phone: "+43650/3393741",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-kreativ-studio-f5ac7",
    name: "Kreativ-Studio",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Hausfeldstraße 20, 1220",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Kreativ-Studio esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Kreativ-Studio is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.barbaras-kreativ-studio.blogspot.co.at",
    gallery_urls: [
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjJwTFI6VwY1M_ecjUcEnx_sRMGjC2fb6DVZYpULUog769ls_VonwLpvHFwW5qh6vlT5J_14QJGXH9vvygF9VNFcXzZNPn_t8EloRnAS8TOi2PHjyGBClCWlddb6g0YE9Q7za-jt3KGiWqs4tMFFJ8HsKiaHWwdFsxCv2oBZP-I8VuO6v79rpNk19S9/w1200-h630-p-k-no-nu/IMG_20220826_165757.jpg",
    ],
    contact_email: "kreativ-studio@chello.at",
    contact_phone: "+43664/5013135",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-zeitlose-zeremonie-f15ac",
    name: "Die Zeitlose Zeremonie",
    category: "celebrant",
    city: "Wien, AT",
    address: "Paradisgasse 26A, 1190",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Die Zeitlose Zeremonie esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Die Zeitlose Zeremonie is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.zeremonie.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01782/017824448/staticmap.png"],
    contact_email: "kontakt@zeremonie.at",
    contact_phone: "+43650/5411953",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-zeremonienleiter-com-24b7d",
    name: "zeremonienleiter.com",
    category: "celebrant",
    city: "Wien, AT",
    address: "Mariensteig 17, 1130",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "zeremonienleiter.com esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "zeremonienleiter.com is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://zeremonienleiter.eu/",
    gallery_urls: [
      "https://zeremonienleiter.eu/images/bereich-images/locations.jpg",
      "https://zeremonienleiter.eu/images/bereich-images/hochzeit.jpg",
      "https://zeremonienleiter.eu/images/bereich-images/redner.jpg",
      "https://zeremonienleiter.eu/images/bereich-images/party.jpg",
    ],
    contact_email: "office@zeremonienleiter.com",
    contact_phone: "+43676/6407420",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-traumhochzeit-at-433e9",
    name: "traumhochzeit.at",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Hervicusgasse 4, 1120",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "traumhochzeit.at esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "traumhochzeit.at is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://traumhochzeit.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918590/staticmap.png"],
    contact_email: "office@traumhochzeit.at",
    contact_phone: "+43664/4208382",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-topava-marketing-handels-gmbh-913ae",
    name: "Topava Marketing-& Handels GmbH",
    category: "wedding_planner",
    city: "Groß-Enzersdorf, AT",
    address: "Robert Stolz-Gasse 1, 2301",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Topava Marketing-& Handels GmbH esküvői szolgáltató Groß-Enzersdorf településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Topava Marketing-& Handels GmbH is a wedding vendor based in Groß-Enzersdorf. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.hochzeit-brautinfo.at/",
    gallery_urls: [
      "https://www.hochzeit-brautinfo.at/data/temp/Header_Header_Aussteller26_1920_670_cut_q90.jpg",
    ],
    contact_email: "webmarketing@brautinfo.at",
    contact_phone: "+43664/4632868",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-ideenwerkstatt-st-johann-02761",
    name: "Ideenwerkstatt St.Johann",
    category: "wedding_planner",
    city: "Sankt Johann im Pongau, AT",
    address: "Neu-Reinbach 6, 5600",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Ideenwerkstatt St.Johann esküvői szolgáltató Sankt Johann im Pongau településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Ideenwerkstatt St.Johann is a wedding vendor based in Sankt Johann im Pongau. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.1000-ideen.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918585/staticmap.png"],
    contact_email: "ideenwerkstatt@sbg.at",
    contact_phone: "+43650/6829559",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-bezaubernde-braut-e0e81",
    name: "Die Bezaubernde Braut",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Mariahilfer Straße 1A, 1060",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Die Bezaubernde Braut esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Die Bezaubernde Braut is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.bezauberndebraut.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017918581/staticmap.png"],
    contact_email: "info@bezaubernde-braut.at",
    contact_phone: "+43699/17115640",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-traumerei-e-u-0ffb2",
    name: "die träumerei e.U.",
    category: "wedding_planner",
    city: "Maria Bild, AT",
    address: "Maria Bild 53, 8382",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "die träumerei e.U. esküvői szolgáltató Maria Bild településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "die träumerei e.U. is a wedding vendor based in Maria Bild. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.dietraeumerei.at/",
    gallery_urls: [
      "https://static.wixstatic.com/media/f53f05_d01b092644c84154a43e594f16e25685~mv2.jpg/v1/fill/w_2500,h_1668,al_c/f53f05_d01b092644c84154a43e594f16e25685~mv2.jpg",
    ],
    contact_email: "office@dietraeumerei.at",
    contact_phone: "+433329/45571",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-zauberhafte-unterhaltung-mit-frascati-gloria-6ea69",
    name: "Zauberhafte Unterhaltung mit Frascati & Gloria",
    category: "wedding_planner",
    city: "Innsbruck, AT",
    address: "Postfach 830, 6023",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Zauberhafte Unterhaltung mit Frascati & Gloria esküvői szolgáltató Innsbruck településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Zauberhafte Unterhaltung mit Frascati & Gloria is a wedding vendor based in Innsbruck. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.zauberer.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01806/018062052/staticmap.png"],
    contact_email: "gloria@frascati.at",
    contact_phone: "+43800/240431486",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-schnur-alice-meisterphotographie-95092",
    name: "Schnür Alice - Meisterphotographie",
    category: "wedding_planner",
    city: "Klosterneuburg, AT",
    address: "Hauptstraße 110, 3400",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Schnür Alice - Meisterphotographie esküvői szolgáltató Klosterneuburg településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Schnür Alice - Meisterphotographie is a wedding vendor based in Klosterneuburg. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.photo-schnuer.com/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01789/017890329/staticmap.png"],
    contact_email: "office@photo-schnuer.com",
    contact_phone: "+43676/4009140",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-fotoatelier-christian-schorg-gmbh-5e103",
    name: "Fotoatelier - Christian Schörg GmbH",
    category: "photography",
    city: "Baden, AT",
    address: "Haueisgasse 8, 2500",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Fotoatelier - Christian Schörg GmbH esküvői szolgáltató Baden településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Fotoatelier - Christian Schörg GmbH is a wedding vendor based in Baden. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.foto-schoerg.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01789/017890328/staticmap.png"],
    contact_email: "atelier@foto-schoerg.at",
    contact_phone: "+432252/42470",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-wimmer-christian-cateringservice-leib-seele-070f2",
    name: "Wimmer Christian Cateringservice, Leib & Seele",
    category: "catering",
    city: "Ried im Innkreis, AT",
    address: "Haager Straße 3, 4910",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Wimmer Christian Cateringservice, Leib & Seele esküvői szolgáltató Ried im Innkreis településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Wimmer Christian Cateringservice, Leib & Seele is a wedding vendor based in Ried im Innkreis. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.party-cateringservice.at/",
    gallery_urls: ["https://www.party-cateringservice.at/upload/imgproc/1426811_head.jpg"],
    contact_email: "leib.seele@aon.at",
    contact_phone: "+437752/80631",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-atelier-fur-floristik-veronika-matt-d7fc4",
    name: "Atelier für Floristik, Veronika Matt",
    category: "florist",
    city: "Hörbranz, AT",
    address: "Heribrandstraße 3, 6912",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Atelier für Floristik, Veronika Matt esküvői szolgáltató Hörbranz településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Atelier für Floristik, Veronika Matt is a wedding vendor based in Hörbranz. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.veronika-matt.com/",
    gallery_urls: [
      "https://static.wixstatic.com/media/c48bf2_9877b779a37645ada53e774d4bc0918f~mv2.jpg/v1/crop/x_8,y_0,w_5092,h_4000/fill/w_600,h_471,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/Veronika-Matt-Floristik-Mai-2026_kb26_0120.jpg",
      "https://static.wixstatic.com/media/c48bf2_d7bf23a56c1c4c39b86ae483d080c4c1~mv2.jpg/v1/fill/w_940,h_627,q_90,enc_avif,quality_auto/c48bf2_d7bf23a56c1c4c39b86ae483d080c4c1~mv2.jpg",
      "https://static.wixstatic.com/media/c48bf2_1e1c42a35c374d4e9b965d3d7fc61dbe~mv2.jpg/v1/fill/w_940,h_627,q_90,enc_avif,quality_auto/c48bf2_1e1c42a35c374d4e9b965d3d7fc61dbe~mv2.jpg",
      "https://static.wixstatic.com/media/c48bf2_b7f2f8c3235f4291a22cb091ab43eca6~mv2.jpg/v1/fill/w_940,h_627,q_90,enc_avif,quality_auto/c48bf2_b7f2f8c3235f4291a22cb091ab43eca6~mv2.jpg",
    ],
    contact_email: "atelier@veronikamatt.at",
    contact_phone: "+43664/99497606",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-brautmoden-vondru-aff42",
    name: "Brautmoden Vondru",
    category: "bridal_boutique",
    city: "Wien, AT",
    address: "Thaliastraße 43, 1160",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Brautmoden Vondru esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Brautmoden Vondru is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.vondru.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01788/017888667/staticmap.png"],
    contact_email: "office@vondru.at",
    contact_phone: "+431/495940369",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-brautmode-stern-14d3d",
    name: "Brautmode Stern",
    category: "bridal_boutique",
    city: "Wien, AT",
    address: "Mariahilfer Straße 163, 1150",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Brautmode Stern esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Brautmode Stern is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.brautmodestern.at",
    gallery_urls: [
      "https://www.brautmodestern.at/uploads/1YsL0ERt/768x0_1024x0/brautkleider.jpg",
      "https://www.brautmodestern.at/uploads/ZDq6DZm9/768x0_1024x0/abendkleider.jpg",
      "https://www.brautmodestern.at/uploads/qeOXLWcz/768x0_1024x0/damenaccessoires.jpg",
      "https://www.brautmodestern.at/uploads/AwHHzW63/768x0_1024x0/herrenmode.jpg",
    ],
    contact_email: "info@brautmodestern.at",
    contact_phone: "+431/8933794",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-berger-florian-gmbh-4342f",
    name: "Berger Florian GmbH",
    category: "florist",
    city: "Schwanenstadt, AT",
    address: "Ferdinand Berger-Straße 1, 4690",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Berger Florian GmbH esküvői szolgáltató Schwanenstadt településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Berger Florian GmbH is a wedding vendor based in Schwanenstadt. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.bergershop.com",
    gallery_urls: [
      "https://www.bergershop.com/wp-content/uploads/2025/09/10780_abb-aehnlich_3.jpg",
    ],
    contact_email: "info@bergershop.com",
    contact_phone: "+437673/40072220",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-alpenhotel-speckbacherhof-bfdcc",
    name: "Alpenhotel Speckbacherhof",
    category: "bridal_boutique",
    city: "Gnadenwald, AT",
    address: "Gnadenwald 2, 6069",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Alpenhotel Speckbacherhof esküvői szolgáltató Gnadenwald településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Alpenhotel Speckbacherhof is a wedding vendor based in Gnadenwald. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.speckbacherhof.at/",
    gallery_urls: [
      "https://www.speckbacherhof.at/wp-content/uploads/2020/02/FreieTrauungNici12.jpg",
      "https://www.speckbacherhof.at/wp-content/uploads/2019/02/001-Synthesa-Speckbacherhof-bearbeitet.jpg",
      "https://www.speckbacherhof.at/wp-content/uploads/2019/02/Winter_Panorama.jpg",
      "https://www.speckbacherhof.at/wp-content/uploads/2019/02/Familienresidenz.jpg",
    ],
    contact_email: "info@speckbacherhof.at",
    contact_phone: "+435223/52511",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-hochzeitsfotograf-wien-valphotography-atlbe",
    name: "Hochzeitsfotograf Wien - ValPhotography",
    category: "photography",
    city: "Wien, AT",
    address: "Attemsgasse 23, 1220",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Hochzeitsfotograf Wien - ValPhotography esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Hochzeitsfotograf Wien - ValPhotography is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.valphotography.at",
    gallery_urls: [
      "https://www.valphotography.at/wp-content/uploads/2024/02/Hochzeitsfotograf-23.jpg",
      "https://www.valphotography.at/wp-content/uploads/2024/02/Destination-Wedding-Photographer-66-776x1024.jpg",
      "https://www.valphotography.at/wp-content/uploads/2024/02/Hochzeitsfotograf-Wien-54-1024x683.jpg",
      "https://www.valphotography.at/wp-content/uploads/2024/02/2116637.jpg",
    ],
    contact_email: "val@valphotography.at",
    contact_phone: "+43699/17699919",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-hochzeitsfotografin-michele-peloza-tdbhx",
    name: "Hochzeitsfotografin Michele Peloza",
    category: "photography",
    city: "Pettenbach, AT",
    address: "Enengl-Florianiweg 5, 4643 Pettenbach",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Hochzeitsfotografin Michele Peloza esküvői szolgáltató Pettenbach településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Hochzeitsfotografin Michele Peloza is a wedding vendor based in Pettenbach. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.michelepeloza.com",
    gallery_urls: [
      "https://www.michelepeloza.com/wp-content/uploads/2023/11/Fotograf-Linz_001.webp",
    ],
    contact_email: "info@michelepeloza.com",
    contact_phone: "+43 650 2729265",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-mathias-brabetz-photography-obuug",
    name: "Mathias Brabetz Photography",
    category: "photography",
    city: "Telfs, AT",
    address: "Mühlgasse 2, 6410",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Mathias Brabetz Photography esküvői szolgáltató Telfs településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Mathias Brabetz Photography is a wedding vendor based in Telfs. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.hochzeitsfotograf.mathiasbrabetz.com",
    gallery_urls: [
      "https://gelbe-seiten-online.at/media_at/01909/019090844/galerien/Galerie/foto1.jpg",
      "https://gelbe-seiten-online.at/media_at/01909/019090844/galerien/Galerie/foto2.jpg",
      "https://gelbe-seiten-online.at/media_at/01909/019090844/staticmap.png",
    ],
    contact_email: "contact@mathiasbrabetz.com",
    contact_phone: "+43664/2172884",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-golden-elephant-hochzeitsfotograf-hochzeitsvideo-bwuxg",
    name: "Golden Elephant - Hochzeitsfotograf & Hochzeitsvideograf",
    category: "videography",
    city: "Wimpassing an der Leitha, AT",
    address: "Feldgasse 5, 2485",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Golden Elephant - Hochzeitsfotograf & Hochzeitsvideograf esküvői szolgáltató Wimpassing an der Leitha településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Golden Elephant - Hochzeitsfotograf & Hochzeitsvideograf is a wedding vendor based in Wimpassing an der Leitha. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://golden-elephant.at/de/",
    gallery_urls: [
      "https://golden-elephant.at/wp-content/uploads/2024/01/Hochzeitsfotograf-Burgenland-Niederoesterreich-Steiermark-Burgenland-Golden-Elephant-Cover.webp",
      "https://golden-elephant.at/wp-content/uploads/2026/04/hochzeitsfotogaf-burgenland-niederoesterreich-steiermark.webp",
    ],
    contact_email: "office@golden-elephant.at",
    contact_phone: "+43699/11091594",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-hochzeitswelt-zarembach-krenn-og-pqndo",
    name: "Die Hochzeitswelt Zarembach - Krenn OG",
    category: "wedding_planner",
    city: "Linz, AT",
    address: "Hoppichlerstr 10, 4040",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Die Hochzeitswelt Zarembach - Krenn OG esküvői szolgáltató Linz településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Die Hochzeitswelt Zarembach - Krenn OG is a wedding vendor based in Linz. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.hochzeitswelt.at/",
    gallery_urls: [
      "https://www.hochzeitswelt.at/wp-content/uploads/2024/05/hochzeitsmesse-oesterreich.jpg",
      "https://www.hochzeitswelt.at/wp-content/uploads/2026/02/hochzeitsmesse-wels-hochzeitswelt-1-1-768x512.jpg",
      "https://www.hochzeitswelt.at/wp-content/uploads/2025/02/hochzeitsmesse-klagenfurt-hochzeitsmesse-kaernten-768x576.jpg",
      "https://www.hochzeitswelt.at/wp-content/uploads/2024/06/20241027-HochzeitsWelt-Hochzeitsmesse-Wien-183-768x1152.jpg",
    ],
    contact_email: "info@diehochzeitswelt.at",
    contact_phone: "+43699/11791615",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-airimesei-weddings-hwyuu",
    name: "Airimesei-Weddings",
    category: "photography",
    city: "Wien, AT",
    address: "Kummergasse 5, 1210",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Airimesei-Weddings esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Airimesei-Weddings is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://airimesei-weddings.at/",
    gallery_urls: [
      "https://airimesei-weddings.at/wp-content/uploads/2025/10/TNprev-1109.jpg",
      "https://airimesei-weddings.at/wp-content/uploads/2025/10/LMw-6110.jpg",
      "https://airimesei-weddings.at/wp-content/uploads/2025/10/LB-2132.jpg",
      "https://airimesei-weddings.at/wp-content/uploads/2025/10/TNprev-1097.jpg",
    ],
    contact_email: "airimesei.weddings@gmail.com",
    contact_phone: "+43670/4027271",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-bryan-reinhart-hochzeitsfotograf-29b9d",
    name: "Bryan Reinhart Hochzeitsfotograf",
    category: "photography",
    city: "Salzburg, AT",
    address: "Nonntaler Hauptstraße 18, 5020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Bryan Reinhart Hochzeitsfotograf esküvői szolgáltató Salzburg településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Bryan Reinhart Hochzeitsfotograf is a wedding vendor based in Salzburg. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://bryanreinhart.info/",
    gallery_urls: [
      "https://cdn.myportfolio.com/03f1b248755892c4f4e5bb9795a43520/4b12e2b1-9989-4f73-9d90-a1c07e49402d_rwc_0x222x960x541x960.jpg?h=fd7a8c74e95786f87b829354c2288953",
    ],
    contact_email: "bryan_reinhart@hotmail.com",
    contact_phone: "+43650/5617805",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-kollmann-julia-photography-hochzeitsfotograf-98dac",
    name: "Kollmann Julia Photography - Hochzeitsfotograf",
    category: "photography",
    city: "Marchtrenk, AT",
    address: "Waldstraße 2a, 4614",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Kollmann Julia Photography - Hochzeitsfotograf esküvői szolgáltató Marchtrenk településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Kollmann Julia Photography - Hochzeitsfotograf is a wedding vendor based in Marchtrenk. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.juliakollmann.com",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017912882/staticmap.png"],
    contact_email: "info@juliakollmann.com",
    contact_phone: "+43650/6136132",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-finest-wedding-photography-susi-nagele-hochzeits-51751",
    name: "FINEST WEDDING PHOTOGRAPHY Susi Nagele Hochzeitsfotograf - Fotostudio",
    category: "photography",
    city: "Wien, AT",
    address: "Klosterneuburger Straße 34, 1200",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "FINEST WEDDING PHOTOGRAPHY Susi Nagele Hochzeitsfotograf - Fotostudio esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "FINEST WEDDING PHOTOGRAPHY Susi Nagele Hochzeitsfotograf - Fotostudio is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.finestweddingphotography.com",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01791/017912996/staticmap.png"],
    contact_email: "office@finestweddingphotography.com",
    contact_phone: "+43680/3136765",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-die-hochzeitsplaner-bed54",
    name: "Die Hochzeitsplaner",
    category: "wedding_planner",
    city: "Wien, AT",
    address: "Lerchenfelder Straße 54-56, 1080",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Die Hochzeitsplaner esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Die Hochzeitsplaner is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "https://www.hochzeitsplaner.at/",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01787/017872145/staticmap.png"],
    contact_email: "office@hochzeitsplaner.co.at",
    contact_phone: "+431/9445743",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "at26-gsol-tauf-u-hochzeitsshop-e2f3f",
    name: "Tauf- u. Hochzeitsshop",
    category: "bridal_boutique",
    city: "Wien, AT",
    address: "Große Stadtgutg 26, 1020",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Tauf- u. Hochzeitsshop esküvői szolgáltató Wien településen. A vállalkozás teljes címet, közvetlen telefonos és e-mailes elérhetőséget, valamint saját online portfóliót tesz közzé.",
    blurb_en:
      "Tauf- u. Hochzeitsshop is a wedding vendor based in Wien. The business publishes a full address, direct phone and email contacts, and its own online portfolio.",
    website: "http://www.hochzeitsshop.at",
    gallery_urls: ["https://gelbe-seiten-online.at/media_at/01908/019080748/staticmap.png"],
    contact_email: "info@brautstyling.at",
    contact_phone: "+43699/19694488",
    lat: null,
    lng: null,
    source: "curated",
    price_band: null,
  },
];
