// Curated suppliers directory. v1 is read-only — outbound contact only, no
// booking/messaging. Real entries only: name, address, website, capacity, and
// price band must correspond to a real business. Empty categories (catering,
// photo_video, music_dj, …) will be filled by community submissions via the
// "Drop your own" flow until the v2 marketplace lands.
//
// Capacity is the published seated-dinner / "esküvőre" range where the venue
// makes one public. Couples should still confirm exact figures with the venue
// — numbers shift between seated dinner / standing reception / ceremony layouts.

export type { DirectorySupplierBase, SupplierCategory } from "@shared/suppliers";
import type { DirectorySupplierBase } from "@shared/suppliers";

const noContact = { contact_email: null, contact_phone: null } as const;

export const DIRECTORY: DirectorySupplierBase[] = [
  {
    id: "normafa-rendezvenyhaz",
    name: "Normafa Rendezvényház",
    category: "venue",
    city: "Budapest",
    address: "1121 Budapest, Hegyhát út 16.",
    capacity_min: 120,
    capacity_max: 150,
    blurb_hu: "Erdős környezetű rendezvényház a Normafánál, 120–150 fős esküvőkre.",
    blurb_en: "Forest-set venue near Normafa, 120–150 guests.",
    website: "https://normafarendezvenyhaz.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "etyeki-kuria",
    name: "Etyeki Kúria",
    category: "venue",
    city: "Etyek",
    address: "2091 Etyek, Báthori utca 21.",
    capacity_min: 60,
    capacity_max: 120,
    blurb_hu: "Borvidéki kúriaesküvő Etyeken, 60–120 fős létszámra.",
    blurb_en: "Wine-region manor wedding in Etyek, 60–120 guests.",
    website: "https://etyekikuria.com/pages/eskuvo",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "nadas-pihenopark",
    name: "Nádas Pihenőpark",
    category: "venue",
    city: "Vasad",
    address: "2211 Vasad, Monori út 100.",
    capacity_min: 80,
    capacity_max: 250,
    blurb_hu: "Tóparti birtok közel Budapesthez, 80–250 fős esküvőkre.",
    blurb_en: "Lakeside estate near Budapest, weddings of 80–250.",
    website: "https://nadaspihenopark.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "obolhaz",
    name: "ÖbölHáz Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1117 Budapest, Kopaszi-gát 1.",
    capacity_min: 100,
    capacity_max: 250,
    blurb_hu: "Vízparti rendezvényközpont a Kopaszi-gáton, 100–250 fős esküvőkre.",
    blurb_en: "Waterfront venue at Kopaszi-gát, 100–250 guests.",
    website: "https://obolhaz.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "lupa-event-hall",
    name: "Lupa Event Hall",
    category: "venue",
    city: "Budakalász",
    address: "2011 Budakalász, Tó utca 1.",
    capacity_min: 240,
    capacity_max: 500,
    blurb_hu: "Tóparti modern rendezvényközpont, 240–500 fős kapacitás.",
    blurb_en: "Modern lakeside venue, capacity 240–500.",
    website: "https://lupabeach.com/en/helyszin/lupa-event-hall/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "godolloi-kiralyi-kastely",
    name: "Gödöllői Királyi Kastély",
    category: "venue",
    city: "Gödöllő",
    address: "2100 Gödöllő, Grassalkovich-kastély",
    capacity_min: 50,
    capacity_max: 200,
    blurb_hu: "Királyi barokk kastély Gödöllőn, 50–200 fős esküvőkre.",
    blurb_en: "Royal Baroque palace in Gödöllő, weddings of 50–200.",
    website: "https://kiralyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "haraszthy-pinceszet",
    name: "Haraszthy Pincészet",
    category: "venue",
    city: "Etyek",
    address: "2091 Etyek, Vincellér utca 44.",
    capacity_min: 80,
    capacity_max: 130,
    blurb_hu: "Pincészet és rendezvényhelyszín Etyeken, 80–130 fős esküvőkre.",
    blurb_en: "Winery and event venue in Etyek, 80–130 guests.",
    website: "https://haraszthy.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "tundererdo",
    name: "Tündérerdő",
    category: "venue",
    city: "Budapest",
    address: "1024 Budapest, Szépvölgyi dűlő 1.",
    capacity_min: 50,
    capacity_max: 150,
    blurb_hu: "Erdei rendezvényhelyszín a budai hegyekben, 50–150 fős esküvőkre.",
    blurb_en: "Forest venue in the Buda hills, 50–150 guests.",
    website: "https://www.tundererdo.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "dodos-kitchen",
    name: "DODO's Kitchen",
    category: "venue",
    city: "Budapest",
    address: "1203 Budapest, Vízisport utca 12–18.",
    capacity_min: 10,
    capacity_max: 200,
    blurb_hu: "Étterem és rendezvénytér a Duna-parton, 10–200 fős esküvőkre.",
    blurb_en: "Restaurant and event space by the Danube, 10–200 guests.",
    website: "https://dodoskitchen.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "botaniq-turai-kastely",
    name: "BOTANIQ Turai Kastély",
    category: "venue",
    city: "Tura",
    address: "2194 Tura, Park utca 37.",
    capacity_min: null,
    capacity_max: 60,
    blurb_hu: "Privát luxuskastély Turán, max. 60 fős privát rendezvényekre.",
    blurb_en: "Private luxury castle in Tura, intimate events up to 60.",
    website: "https://botaniqkastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "palvolgyi-rendezvenysator",
    name: "Pál-völgyi Rendezvénysátor",
    category: "venue",
    city: "Budapest",
    address: "1025 Budapest, Szépvölgyi út 162.",
    capacity_min: 80,
    capacity_max: 200,
    blurb_hu: "Erdei rendezvénysátor Pál-völgyben, 80–200 fős esküvőkre.",
    blurb_en: "Forest tent venue at Pál-völgy, 80–200 guests.",
    website: "https://palvolgyirendezveny.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "tisza-kastely-geszt",
    name: "Tisza-kastély, Geszt",
    category: "venue",
    city: "Geszt",
    address: "5734 Geszt, Arany János utca 23.",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Műemléki Tisza-kastély Geszten, 20–80 fős esküvőkre.",
    blurb_en: "Heritage Tisza castle in Geszt, weddings of 20–80.",
    website: "https://tiszakastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "festetics-kastely-deg",
    name: "Festetics-kastély, Dég",
    category: "venue",
    city: "Dég",
    address: "8135 Dég, Hunyadi utca 11.",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Klasszicista Festetics-kastély Dégen, 20–80 fős létszámra.",
    blurb_en: "Neoclassical Festetics castle in Dég, 20–80 guests.",
    website: "https://degikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "karolyi-kastely-fuzerradvany",
    name: "Károlyi-kastély, Füzérradvány",
    category: "venue",
    city: "Füzérradvány",
    address: "3993 Füzérradvány, gróf Károlyi Ede út 1.",
    capacity_min: 20,
    capacity_max: 120,
    blurb_hu: "Történelmi kastélyesküvő Füzérradványban, 20–120 fős létszámra.",
    blurb_en: "Historic castle wedding in Füzérradvány, 20–120 guests.",
    website: "https://fuzerradvanyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "nest-cottage-birtok",
    name: "Nest Cottage Birtok",
    category: "venue",
    city: "Balatonszőlős",
    address: "8233 Balatonszőlős, Izabella út",
    capacity_min: 30,
    capacity_max: 120,
    blurb_hu: "Balaton-felvidéki birtok Balatonszőlősön, 30–120 fős esküvőkre.",
    blurb_en: "Estate in the Balaton uplands, 30–120 guests.",
    website: "https://www.nestcottage.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "fenyoharaszt-kastelyszallo",
    name: "Fenyőharaszt Kastélyszálló",
    category: "venue",
    city: "Verseg-Fenyőharaszt",
    address: "2174 Verseg-Fenyőharaszt",
    capacity_min: 50,
    capacity_max: 180,
    blurb_hu: "Kastélyszálló erdős birtokon Versegen, 50–180 fős esküvőkre.",
    blurb_en: "Castle hotel on a forested estate, 50–180 guests.",
    website: "https://eskuvonkhelyszine.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "gereby-kuria",
    name: "Geréby Kúria Hotel és Lovasudvar",
    category: "venue",
    city: "Lajosmizse",
    address: "6050 Lajosmizse, Alsólajos 224.",
    capacity_min: 50,
    capacity_max: 250,
    blurb_hu: "Lovasudvarral kombinált kúria Lajosmizsén, 50–250 fős esküvőkre.",
    blurb_en: "Manor with equestrian estate in Lajosmizse, 50–250 guests.",
    website: "https://gereby.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "brunszvik-kastely",
    name: "Brunszvik-kastély",
    category: "venue",
    city: "Martonvásár",
    address: "2462 Martonvásár, Brunszvik utca 2.",
    capacity_min: 20,
    capacity_max: 150,
    blurb_hu: "Romantikus park és kastély Martonvásáron, 20–150 fős esküvőkre.",
    blurb_en: "Romantic park and castle in Martonvásár, 20–150 guests.",
    website: "https://brunszvik-kastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "pronay-kastely",
    name: "Prónay-kastély",
    category: "venue",
    city: "Alsópetény",
    address: "2617 Alsópetény, Kossuth Lajos utca 34.",
    capacity_min: 30,
    capacity_max: 100,
    blurb_hu: "Hangulatos kastélybirtok Alsópetényben, 30–100 fős esküvőkre.",
    blurb_en: "Atmospheric castle estate in Alsópetény, 30–100 guests.",
    website: "https://pronaykastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "karolyi-kastely-fehervarcsurgo",
    name: "Károlyi-kastély, Fehérvárcsurgó",
    category: "venue",
    city: "Fehérvárcsurgó",
    address: "8052 Fehérvárcsurgó, Petőfi Sándor utca 2.",
    capacity_min: 30,
    capacity_max: 150,
    blurb_hu: "Károlyi-kastély arborétummal Fehérvárcsurgón, 30–150 fős esküvőkre.",
    blurb_en: "Károlyi castle with arboretum in Fehérvárcsurgó, 30–150 guests.",
    website: "https://www.karolyi.org.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "puchner-kastelyszallo",
    name: "Puchner Kastélyszálló",
    category: "venue",
    city: "Bikal",
    address: "7346 Bikal, Rákóczi utca 22.",
    capacity_min: null,
    capacity_max: 250,
    blurb_hu: "Kastélyszálló élményparkkal Bikalon, max. 250 fős esküvőkre.",
    blurb_en: "Castle hotel with experience park in Bikal, up to 250 guests.",
    website: "https://puchner.hu/eskuvohelyszin",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "fried-kastelyszallo",
    name: "Fried Kastélyszálló Resort",
    category: "venue",
    city: "Simontornya",
    address: "7081 Simontornya, Malom utca 33.",
    capacity_min: 30,
    capacity_max: 120,
    blurb_hu: "Felújított kastélyszálló Simontornyán, 30–120 fős esküvőkre.",
    blurb_en: "Restored castle hotel in Simontornya, 30–120 guests.",
    website: "https://friedhotel.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "la-contessa",
    name: "La Contessa Kastélyhotel",
    category: "venue",
    city: "Szilvásvárad",
    address: "3348 Szilvásvárad, Park utca 6.",
    capacity_min: null,
    capacity_max: 120,
    blurb_hu: "Bükki kastélyhotel Szilvásváradon, max. 120 fős esküvőkre.",
    blurb_en: "Bükk-mountain castle hotel in Szilvásvárad, up to 120 guests.",
    website: "https://lacontessa.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "hertelendy-kastely",
    name: "Hertelendy Kastély",
    category: "venue",
    city: "Kutas",
    address: "7513 Kutas, Hertelendy Kastély",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Magán-kastélybirtok luxusszállással, 20–80 fős eseményekre.",
    blurb_en: "Private castle estate with luxury stay, 20–80 guests.",
    website: "https://www.hertelendy-castle.com/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "graefl-major",
    name: "Graefl Major Kétútköz",
    category: "venue",
    city: "Kétútköz",
    address: "3384 Poroszló külterület, Kétútköz",
    capacity_min: 30,
    capacity_max: 150,
    blurb_hu: "Tisza-menti birtok és majorság, 30–150 fős esküvőkre.",
    blurb_en: "Tisza-side estate and farmstead, 30–150 guests.",
    website: "https://graefl.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "dudits-kastely",
    name: "Dudits Kastély",
    category: "venue",
    city: "Hajós",
    address: "6344 Hajós, Borbíró utca 1.",
    capacity_min: 50,
    capacity_max: 180,
    blurb_hu: "Borvidéki kastély Hajóson, 50–180 fős esküvőkre.",
    blurb_en: "Wine-region castle in Hajós, 50–180 guests.",
    website: "https://dudits.eu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "ottevenyi-foldvary-kastely",
    name: "Öttevényi Földváry-kastély",
    category: "venue",
    city: "Öttevény",
    address: "9153 Öttevény, Fő utca 173.",
    capacity_min: 60,
    capacity_max: 150,
    blurb_hu: "Felújított Földváry-kastély Öttevényben, 60–150 fős esküvőkre.",
    blurb_en: "Restored Földváry castle in Öttevény, 60–150 guests.",
    website: "https://ottevenyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "nadasdy-kastely-nadasdladany",
    name: "Nádasdy Kastély, Nádasdladány",
    category: "venue",
    city: "Nádasdladány",
    address: "8145 Nádasdladány, Kastélypark 1.",
    capacity_min: 20,
    capacity_max: 100,
    blurb_hu: "Neogótikus Nádasdy-kastély, 20–100 fős esküvőkre.",
    blurb_en: "Neo-Gothic Nádasdy castle, 20–100 guests.",
    website: "https://nadasdladanyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "zichy-park-hotel",
    name: "Zichy Park Hotel",
    category: "venue",
    city: "Bikács",
    address: "7082 Bikács, Zichy Park Hotel",
    capacity_min: 50,
    capacity_max: 130,
    blurb_hu: "Kastélypark hotel Bikácson, 50–130 fős esküvőkre.",
    blurb_en: "Castle-park hotel in Bikács, 50–130 guests.",
    website: "https://www.zichypark-hotel.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "alcsuti-arboretum",
    name: "Alcsúti Arborétum",
    category: "venue",
    city: "Alcsútdoboz",
    address: "8087 Alcsútdoboz, Kastély 2.",
    capacity_min: 50,
    capacity_max: 120,
    blurb_hu: "Történelmi arborétum Alcsúton, 50–120 fős kerti esküvőkre.",
    blurb_en: "Historic arboretum in Alcsút, 50–120 garden weddings.",
    website: "https://alcsuti-arboretum.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "the-wedding-city",
    name: "The Wedding City",
    category: "venue",
    city: "Budapest",
    address: "1112 Budapest, Repülőtéri út 2.",
    capacity_min: 50,
    capacity_max: 200,
    blurb_hu: "Budai esküvői helyszín, 50–200 fős esküvőkre.",
    blurb_en: "Buda-side wedding venue, 50–200 guests.",
    website: "https://theweddingcity.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "spoon-the-boat",
    name: "Spoon The Boat",
    category: "venue",
    city: "Budapest",
    address: "1052 Budapest, Vigadó tér 3. kikötő",
    capacity_min: 50,
    capacity_max: 400,
    blurb_hu: "Hajóétterem a Vigadó térnél, 50–400 fős esküvőkre.",
    blurb_en: "Boat restaurant at Vigadó tér, 50–400 guests.",
    website: "https://spoonboat.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "aria-hotel-budapest",
    name: "Aria Hotel Budapest",
    category: "venue",
    city: "Budapest",
    address: "1051 Budapest, Hercegprímás utca 5.",
    capacity_min: 20,
    capacity_max: 100,
    blurb_hu: "Belvárosi luxushotel skybarral, 20–100 fős eseményekre.",
    blurb_en: "Downtown luxury hotel with sky bar, 20–100 guests.",
    website: "https://www.ariahotelbudapest.com/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "halaszbastya-etterem",
    name: "Halászbástya Étterem",
    category: "venue",
    city: "Budapest",
    address: "1014 Budapest, Budai Vár, Halászbástya",
    capacity_min: 20,
    capacity_max: 120,
    blurb_hu: "Étterem a Budai Várban, panorámás esküvő 20–120 fő.",
    blurb_en: "Restaurant in the Buda Castle, panoramic weddings 20–120.",
    website: "https://halaszbastya.eu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "gundel-etterem",
    name: "Gundel Étterem",
    category: "venue",
    city: "Budapest",
    address: "1146 Budapest, Gundel Károly út 4.",
    capacity_min: 20,
    capacity_max: 250,
    blurb_hu: "Klasszikus Gundel a Városligetnél, 20–250+ fős esküvőkre.",
    blurb_en: "Classic Gundel by Városliget, weddings 20–250+.",
    website: "https://gundel.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "varkert-bazar",
    name: "Várkert Bazár",
    category: "venue",
    city: "Budapest",
    address: "1013 Budapest, Ybl Miklós tér 2–6.",
    capacity_min: 50,
    capacity_max: 600,
    blurb_hu: "Történelmi Várkert Bazár a Duna-parton, 50–600 fős eseményekre.",
    blurb_en: "Historic Várkert Bazár on the Danube, 50–600 guests.",
    website: "https://varkertbazar.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "larus",
    name: "Larus Étterem és Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1124 Budapest, Csörsz utca 18/B",
    capacity_min: 50,
    capacity_max: 300,
    blurb_hu: "Hegyvidéki rendezvényközpont, 50–300 fő (max. 750 fős rendezvény).",
    blurb_en: "Hillside event center, 50–300 guests (events up to 750).",
    website: "https://larusevent.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "symbol-budapest",
    name: "Symbol Budapest",
    category: "venue",
    city: "Budapest",
    address: "1036 Budapest, Bécsi út 56.",
    capacity_min: 50,
    capacity_max: 500,
    blurb_hu: "Óbudai szórakoztatóközpont, 50–500 fős esküvőkre.",
    blurb_en: "Óbuda entertainment complex, 50–500 guests.",
    website: "https://symbolbudapest.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "benczur-haz",
    name: "Benczúr Ház Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1068 Budapest, Benczúr utca 27.",
    capacity_min: 30,
    capacity_max: 180,
    blurb_hu: "Belvárosi villa rendezvényháza, 30–180 fős esküvőkre.",
    blurb_en: "Downtown villa event house, 30–180 guests.",
    website: "https://www.pkalapitvany.hu/bhkk",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "festetics-palota",
    name: "Festetics Palota",
    category: "venue",
    city: "Budapest",
    address: "1088 Budapest, Pollack Mihály tér 3.",
    capacity_min: 50,
    capacity_max: 250,
    blurb_hu: "Múzeumi palota a Pollack Mihály téren, 50–250 fős esküvőkre.",
    blurb_en: "Museum palace on Pollack Mihály square, 50–250 guests.",
    website: "https://festeticspalota.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
];
