// Curated suppliers directory. v1 is read-only — outbound contact only, no
// booking/messaging. Real entries only: name, address, website, capacity, and
// price band must correspond to a real business. Empty categories (catering,
// photo_video, music_dj, …) will be filled by community submissions via the
// "Drop your own" flow until the v2 marketplace lands.
//
// Capacity is the published seated-dinner / "esküvőre" range where the venue
// makes one public. Couples should still confirm exact figures with the venue
// — numbers shift between seated dinner / standing reception / ceremony layouts.

export type { DirectorySupplierBase, SupplierCategory } from "@shared/suppliers";
import type { DirectorySupplierBase } from "@shared/suppliers";

const noContact = {
  contact_email: null,
  contact_phone: null,
  // Coords are layered on below from VENUE_COORDS; entries without a hit
  // fall through to null and just don't show up on the map view.
  lat: null,
  lng: null,
} as const;

/** Approximate WGS-84 coords keyed by directory id. Sourced from the
 *  Hungarian postcode of the venue's address (Budapest postcodes are
 *  4-digit district centroids; rural venues use the town centre). Good
 *  enough for "here's where it is on a map" — couples click through to
 *  the venue website for precise navigation. */
const VENUE_COORDS: Record<string, { lat: number; lng: number }> = {
  "normafa-rendezvenyhaz": { lat: 47.5048, lng: 18.9667 },
  "etyeki-kuria": { lat: 47.4519, lng: 18.7548 },
  "nadas-pihenopark": { lat: 47.3543, lng: 19.4675 },
  obolhaz: { lat: 47.4647, lng: 19.0464 },
  "lupa-event-hall": { lat: 47.6311, lng: 19.0625 },
  "godolloi-kiralyi-kastely": { lat: 47.601, lng: 19.359 },
  "haraszthy-pinceszet": { lat: 47.4519, lng: 18.7548 },
  tundererdo: { lat: 47.5197, lng: 19.0344 },
  "dodos-kitchen": { lat: 47.4341, lng: 19.1106 },
  "botaniq-turai-kastely": { lat: 47.6093, lng: 19.5917 },
  "palvolgyi-rendezvenysator": { lat: 47.5311, lng: 19.0306 },
  "tisza-kastely-geszt": { lat: 46.8867, lng: 21.5897 },
  "festetics-kastely-deg": { lat: 46.8675, lng: 18.4495 },
  "karolyi-kastely-fuzerradvany": { lat: 48.5108, lng: 21.4564 },
  "nest-cottage-birtok": { lat: 46.953, lng: 17.877 },
  "fenyoharaszt-kastelyszallo": { lat: 47.7236, lng: 19.5083 },
  "gereby-kuria": { lat: 47.0244, lng: 19.5575 },
  "brunszvik-kastely": { lat: 47.3107, lng: 18.7878 },
  "pronay-kastely": { lat: 47.8997, lng: 19.2997 },
  "karolyi-kastely-fehervarcsurgo": { lat: 47.2939, lng: 18.2603 },
  "puchner-kastelyszallo": { lat: 46.3214, lng: 18.4117 },
  "fried-kastelyszallo": { lat: 46.7547, lng: 18.5491 },
  "la-contessa": { lat: 48.1014, lng: 20.3922 },
  "hertelendy-kastely": { lat: 46.3506, lng: 17.4861 },
  "graefl-major": { lat: 47.6358, lng: 20.6481 },
  "dudits-kastely": { lat: 46.4036, lng: 19.1192 },
  "ottevenyi-foldvary-kastely": { lat: 47.6481, lng: 17.4744 },
  "nadasdy-kastely-nadasdladany": { lat: 47.1739, lng: 18.2856 },
  "zichy-park-hotel": { lat: 46.7128, lng: 18.6361 },
  "alcsuti-arboretum": { lat: 47.4242, lng: 18.6056 },
  "the-wedding-city": { lat: 47.464, lng: 19.005 },
  "spoon-the-boat": { lat: 47.494, lng: 19.048 },
  "aria-hotel-budapest": { lat: 47.5012, lng: 19.0517 },
  "halaszbastya-etterem": { lat: 47.5018, lng: 19.0357 },
  "gundel-etterem": { lat: 47.5159, lng: 19.079 },
  "varkert-bazar": { lat: 47.4983, lng: 19.0411 },
  larus: { lat: 47.4925, lng: 19.0036 },
  "symbol-budapest": { lat: 47.5396, lng: 19.0428 },
  "benczur-haz": { lat: 47.5106, lng: 19.07 },
  "festetics-palota": { lat: 47.491, lng: 19.067 },
};

// `submitter_type` is layered on by the DIRECTORY map below — curated entries
// never have a submitter, so it's always null. Keeping it off the literals
// here keeps the 100+ entries terse.
const RAW_DIRECTORY: Omit<
  DirectorySupplierBase,
  "submitter_type" | "vendor_account_id" | "hero_image_url"
>[] = [
  {
    id: "normafa-rendezvenyhaz",
    name: "Normafa Rendezvényház",
    category: "venue",
    city: "Budapest",
    address: "1121 Budapest, Hegyhát út 16.",
    capacity_min: 120,
    capacity_max: 150,
    blurb_hu: "Erdős környezetű rendezvényház a Normafánál, 120–150 fős esküvőkre.",
    blurb_en: "Forest-set venue near Normafa, 120–150 guests.",
    website: "https://normafarendezvenyhaz.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "etyeki-kuria",
    name: "Etyeki Kúria",
    category: "venue",
    city: "Etyek",
    address: "2091 Etyek, Báthori utca 21.",
    capacity_min: 60,
    capacity_max: 120,
    blurb_hu: "Borvidéki kúriaesküvő Etyeken, 60–120 fős létszámra.",
    blurb_en: "Wine-region manor wedding in Etyek, 60–120 guests.",
    website: "https://etyekikuria.com/pages/eskuvo",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "nadas-pihenopark",
    name: "Nádas Pihenőpark",
    category: "venue",
    city: "Vasad",
    address: "2211 Vasad, Monori út 100.",
    capacity_min: 80,
    capacity_max: 250,
    blurb_hu: "Tóparti birtok közel Budapesthez, 80–250 fős esküvőkre.",
    blurb_en: "Lakeside estate near Budapest, weddings of 80–250.",
    website: "https://nadaspihenopark.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "obolhaz",
    name: "ÖbölHáz Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1117 Budapest, Kopaszi-gát 1.",
    capacity_min: 100,
    capacity_max: 250,
    blurb_hu: "Vízparti rendezvényközpont a Kopaszi-gáton, 100–250 fős esküvőkre.",
    blurb_en: "Waterfront venue at Kopaszi-gát, 100–250 guests.",
    website: "https://obolhaz.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "lupa-event-hall",
    name: "Lupa Event Hall",
    category: "venue",
    city: "Budakalász",
    address: "2011 Budakalász, Tó utca 1.",
    capacity_min: 240,
    capacity_max: 500,
    blurb_hu: "Tóparti modern rendezvényközpont, 240–500 fős kapacitás.",
    blurb_en: "Modern lakeside venue, capacity 240–500.",
    website: "https://lupabeach.com/en/helyszin/lupa-event-hall/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "godolloi-kiralyi-kastely",
    name: "Gödöllői Királyi Kastély",
    category: "venue",
    city: "Gödöllő",
    address: "2100 Gödöllő, Grassalkovich-kastély",
    capacity_min: 50,
    capacity_max: 200,
    blurb_hu: "Királyi barokk kastély Gödöllőn, 50–200 fős esküvőkre.",
    blurb_en: "Royal Baroque palace in Gödöllő, weddings of 50–200.",
    website: "https://kiralyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "haraszthy-pinceszet",
    name: "Haraszthy Pincészet",
    category: "venue",
    city: "Etyek",
    address: "2091 Etyek, Vincellér utca 44.",
    capacity_min: 80,
    capacity_max: 130,
    blurb_hu: "Pincészet és rendezvényhelyszín Etyeken, 80–130 fős esküvőkre.",
    blurb_en: "Winery and event venue in Etyek, 80–130 guests.",
    website: "https://haraszthy.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "tundererdo",
    name: "Tündérerdő",
    category: "venue",
    city: "Budapest",
    address: "1024 Budapest, Szépvölgyi dűlő 1.",
    capacity_min: 50,
    capacity_max: 150,
    blurb_hu: "Erdei rendezvényhelyszín a budai hegyekben, 50–150 fős esküvőkre.",
    blurb_en: "Forest venue in the Buda hills, 50–150 guests.",
    website: "https://www.tundererdo.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "dodos-kitchen",
    name: "DODO's Kitchen",
    category: "venue",
    city: "Budapest",
    address: "1203 Budapest, Vízisport utca 12–18.",
    capacity_min: 10,
    capacity_max: 200,
    blurb_hu: "Étterem és rendezvénytér a Duna-parton, 10–200 fős esküvőkre.",
    blurb_en: "Restaurant and event space by the Danube, 10–200 guests.",
    website: "https://dodoskitchen.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "botaniq-turai-kastely",
    name: "BOTANIQ Turai Kastély",
    category: "venue",
    city: "Tura",
    address: "2194 Tura, Park utca 37.",
    capacity_min: null,
    capacity_max: 60,
    blurb_hu: "Privát luxuskastély Turán, max. 60 fős privát rendezvényekre.",
    blurb_en: "Private luxury castle in Tura, intimate events up to 60.",
    website: "https://botaniqkastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "palvolgyi-rendezvenysator",
    name: "Pál-völgyi Rendezvénysátor",
    category: "venue",
    city: "Budapest",
    address: "1025 Budapest, Szépvölgyi út 162.",
    capacity_min: 80,
    capacity_max: 200,
    blurb_hu: "Erdei rendezvénysátor Pál-völgyben, 80–200 fős esküvőkre.",
    blurb_en: "Forest tent venue at Pál-völgy, 80–200 guests.",
    website: "https://palvolgyirendezveny.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "tisza-kastely-geszt",
    name: "Tisza-kastély, Geszt",
    category: "venue",
    city: "Geszt",
    address: "5734 Geszt, Arany János utca 23.",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Műemléki Tisza-kastély Geszten, 20–80 fős esküvőkre.",
    blurb_en: "Heritage Tisza castle in Geszt, weddings of 20–80.",
    website: "https://tiszakastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "festetics-kastely-deg",
    name: "Festetics-kastély, Dég",
    category: "venue",
    city: "Dég",
    address: "8135 Dég, Hunyadi utca 11.",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Klasszicista Festetics-kastély Dégen, 20–80 fős létszámra.",
    blurb_en: "Neoclassical Festetics castle in Dég, 20–80 guests.",
    website: "https://degikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "karolyi-kastely-fuzerradvany",
    name: "Károlyi-kastély, Füzérradvány",
    category: "venue",
    city: "Füzérradvány",
    address: "3993 Füzérradvány, gróf Károlyi Ede út 1.",
    capacity_min: 20,
    capacity_max: 120,
    blurb_hu: "Történelmi kastélyesküvő Füzérradványban, 20–120 fős létszámra.",
    blurb_en: "Historic castle wedding in Füzérradvány, 20–120 guests.",
    website: "https://fuzerradvanyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "nest-cottage-birtok",
    name: "Nest Cottage Birtok",
    category: "venue",
    city: "Balatonszőlős",
    address: "8233 Balatonszőlős, Izabella út",
    capacity_min: 30,
    capacity_max: 120,
    blurb_hu: "Balaton-felvidéki birtok Balatonszőlősön, 30–120 fős esküvőkre.",
    blurb_en: "Estate in the Balaton uplands, 30–120 guests.",
    website: "https://www.nestcottage.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "fenyoharaszt-kastelyszallo",
    name: "Fenyőharaszt Kastélyszálló",
    category: "venue",
    city: "Verseg-Fenyőharaszt",
    address: "2174 Verseg-Fenyőharaszt",
    capacity_min: 50,
    capacity_max: 180,
    blurb_hu: "Kastélyszálló erdős birtokon Versegen, 50–180 fős esküvőkre.",
    blurb_en: "Castle hotel on a forested estate, 50–180 guests.",
    website: "https://eskuvonkhelyszine.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "gereby-kuria",
    name: "Geréby Kúria Hotel és Lovasudvar",
    category: "venue",
    city: "Lajosmizse",
    address: "6050 Lajosmizse, Alsólajos 224.",
    capacity_min: 50,
    capacity_max: 250,
    blurb_hu: "Lovasudvarral kombinált kúria Lajosmizsén, 50–250 fős esküvőkre.",
    blurb_en: "Manor with equestrian estate in Lajosmizse, 50–250 guests.",
    website: "https://gereby.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "brunszvik-kastely",
    name: "Brunszvik-kastély",
    category: "venue",
    city: "Martonvásár",
    address: "2462 Martonvásár, Brunszvik utca 2.",
    capacity_min: 20,
    capacity_max: 150,
    blurb_hu: "Romantikus park és kastély Martonvásáron, 20–150 fős esküvőkre.",
    blurb_en: "Romantic park and castle in Martonvásár, 20–150 guests.",
    website: "https://brunszvik-kastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "pronay-kastely",
    name: "Prónay-kastély",
    category: "venue",
    city: "Alsópetény",
    address: "2617 Alsópetény, Kossuth Lajos utca 34.",
    capacity_min: 30,
    capacity_max: 100,
    blurb_hu: "Hangulatos kastélybirtok Alsópetényben, 30–100 fős esküvőkre.",
    blurb_en: "Atmospheric castle estate in Alsópetény, 30–100 guests.",
    website: "https://pronaykastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "karolyi-kastely-fehervarcsurgo",
    name: "Károlyi-kastély, Fehérvárcsurgó",
    category: "venue",
    city: "Fehérvárcsurgó",
    address: "8052 Fehérvárcsurgó, Petőfi Sándor utca 2.",
    capacity_min: 30,
    capacity_max: 150,
    blurb_hu: "Károlyi-kastély arborétummal Fehérvárcsurgón, 30–150 fős esküvőkre.",
    blurb_en: "Károlyi castle with arboretum in Fehérvárcsurgó, 30–150 guests.",
    website: "https://www.karolyi.org.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "puchner-kastelyszallo",
    name: "Puchner Kastélyszálló",
    category: "venue",
    city: "Bikal",
    address: "7346 Bikal, Rákóczi utca 22.",
    capacity_min: null,
    capacity_max: 250,
    blurb_hu: "Kastélyszálló élményparkkal Bikalon, max. 250 fős esküvőkre.",
    blurb_en: "Castle hotel with experience park in Bikal, up to 250 guests.",
    website: "https://puchner.hu/eskuvohelyszin",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "fried-kastelyszallo",
    name: "Fried Kastélyszálló Resort",
    category: "venue",
    city: "Simontornya",
    address: "7081 Simontornya, Malom utca 33.",
    capacity_min: 30,
    capacity_max: 120,
    blurb_hu: "Felújított kastélyszálló Simontornyán, 30–120 fős esküvőkre.",
    blurb_en: "Restored castle hotel in Simontornya, 30–120 guests.",
    website: "https://friedhotel.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "la-contessa",
    name: "La Contessa Kastélyhotel",
    category: "venue",
    city: "Szilvásvárad",
    address: "3348 Szilvásvárad, Park utca 6.",
    capacity_min: null,
    capacity_max: 120,
    blurb_hu: "Bükki kastélyhotel Szilvásváradon, max. 120 fős esküvőkre.",
    blurb_en: "Bükk-mountain castle hotel in Szilvásvárad, up to 120 guests.",
    website: "https://lacontessa.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "hertelendy-kastely",
    name: "Hertelendy Kastély",
    category: "venue",
    city: "Kutas",
    address: "7513 Kutas, Hertelendy Kastély",
    capacity_min: 20,
    capacity_max: 80,
    blurb_hu: "Magán-kastélybirtok luxusszállással, 20–80 fős eseményekre.",
    blurb_en: "Private castle estate with luxury stay, 20–80 guests.",
    website: "https://www.hertelendy-castle.com/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "graefl-major",
    name: "Graefl Major Kétútköz",
    category: "venue",
    city: "Kétútköz",
    address: "3384 Poroszló külterület, Kétútköz",
    capacity_min: 30,
    capacity_max: 150,
    blurb_hu: "Tisza-menti birtok és majorság, 30–150 fős esküvőkre.",
    blurb_en: "Tisza-side estate and farmstead, 30–150 guests.",
    website: "https://graefl.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "dudits-kastely",
    name: "Dudits Kastély",
    category: "venue",
    city: "Hajós",
    address: "6344 Hajós, Borbíró utca 1.",
    capacity_min: 50,
    capacity_max: 180,
    blurb_hu: "Borvidéki kastély Hajóson, 50–180 fős esküvőkre.",
    blurb_en: "Wine-region castle in Hajós, 50–180 guests.",
    website: "https://dudits.eu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "ottevenyi-foldvary-kastely",
    name: "Öttevényi Földváry-kastély",
    category: "venue",
    city: "Öttevény",
    address: "9153 Öttevény, Fő utca 173.",
    capacity_min: 60,
    capacity_max: 150,
    blurb_hu: "Felújított Földváry-kastély Öttevényben, 60–150 fős esküvőkre.",
    blurb_en: "Restored Földváry castle in Öttevény, 60–150 guests.",
    website: "https://ottevenyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "nadasdy-kastely-nadasdladany",
    name: "Nádasdy Kastély, Nádasdladány",
    category: "venue",
    city: "Nádasdladány",
    address: "8145 Nádasdladány, Kastélypark 1.",
    capacity_min: 20,
    capacity_max: 100,
    blurb_hu: "Neogótikus Nádasdy-kastély, 20–100 fős esküvőkre.",
    blurb_en: "Neo-Gothic Nádasdy castle, 20–100 guests.",
    website: "https://nadasdladanyikastely.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "zichy-park-hotel",
    name: "Zichy Park Hotel",
    category: "venue",
    city: "Bikács",
    address: "7082 Bikács, Zichy Park Hotel",
    capacity_min: 50,
    capacity_max: 130,
    blurb_hu: "Kastélypark hotel Bikácson, 50–130 fős esküvőkre.",
    blurb_en: "Castle-park hotel in Bikács, 50–130 guests.",
    website: "https://www.zichypark-hotel.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "alcsuti-arboretum",
    name: "Alcsúti Arborétum",
    category: "venue",
    city: "Alcsútdoboz",
    address: "8087 Alcsútdoboz, Kastély 2.",
    capacity_min: 50,
    capacity_max: 120,
    blurb_hu: "Történelmi arborétum Alcsúton, 50–120 fős kerti esküvőkre.",
    blurb_en: "Historic arboretum in Alcsút, 50–120 garden weddings.",
    website: "https://alcsuti-arboretum.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "the-wedding-city",
    name: "The Wedding City",
    category: "venue",
    city: "Budapest",
    address: "1112 Budapest, Repülőtéri út 2.",
    capacity_min: 50,
    capacity_max: 200,
    blurb_hu: "Budai esküvői helyszín, 50–200 fős esküvőkre.",
    blurb_en: "Buda-side wedding venue, 50–200 guests.",
    website: "https://theweddingcity.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "spoon-the-boat",
    name: "Spoon The Boat",
    category: "venue",
    city: "Budapest",
    address: "1052 Budapest, Vigadó tér 3. kikötő",
    capacity_min: 50,
    capacity_max: 400,
    blurb_hu: "Hajóétterem a Vigadó térnél, 50–400 fős esküvőkre.",
    blurb_en: "Boat restaurant at Vigadó tér, 50–400 guests.",
    website: "https://spoonboat.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "aria-hotel-budapest",
    name: "Aria Hotel Budapest",
    category: "venue",
    city: "Budapest",
    address: "1051 Budapest, Hercegprímás utca 5.",
    capacity_min: 20,
    capacity_max: 100,
    blurb_hu: "Belvárosi luxushotel skybarral, 20–100 fős eseményekre.",
    blurb_en: "Downtown luxury hotel with sky bar, 20–100 guests.",
    website: "https://www.ariahotelbudapest.com/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "halaszbastya-etterem",
    name: "Halászbástya Étterem",
    category: "venue",
    city: "Budapest",
    address: "1014 Budapest, Budai Vár, Halászbástya",
    capacity_min: 20,
    capacity_max: 120,
    blurb_hu: "Étterem a Budai Várban, panorámás esküvő 20–120 fő.",
    blurb_en: "Restaurant in the Buda Castle, panoramic weddings 20–120.",
    website: "https://halaszbastya.eu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "gundel-etterem",
    name: "Gundel Étterem",
    category: "venue",
    city: "Budapest",
    address: "1146 Budapest, Gundel Károly út 4.",
    capacity_min: 20,
    capacity_max: 250,
    blurb_hu: "Klasszikus Gundel a Városligetnél, 20–250+ fős esküvőkre.",
    blurb_en: "Classic Gundel by Városliget, weddings 20–250+.",
    website: "https://gundel.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "varkert-bazar",
    name: "Várkert Bazár",
    category: "venue",
    city: "Budapest",
    address: "1013 Budapest, Ybl Miklós tér 2–6.",
    capacity_min: 50,
    capacity_max: 600,
    blurb_hu: "Történelmi Várkert Bazár a Duna-parton, 50–600 fős eseményekre.",
    blurb_en: "Historic Várkert Bazár on the Danube, 50–600 guests.",
    website: "https://varkertbazar.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "larus",
    name: "Larus Étterem és Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1124 Budapest, Csörsz utca 18/B",
    capacity_min: 50,
    capacity_max: 300,
    blurb_hu: "Hegyvidéki rendezvényközpont, 50–300 fő (max. 750 fős rendezvény).",
    blurb_en: "Hillside event center, 50–300 guests (events up to 750).",
    website: "https://larusevent.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "symbol-budapest",
    name: "Symbol Budapest",
    category: "venue",
    city: "Budapest",
    address: "1036 Budapest, Bécsi út 56.",
    capacity_min: 50,
    capacity_max: 500,
    blurb_hu: "Óbudai szórakoztatóközpont, 50–500 fős esküvőkre.",
    blurb_en: "Óbuda entertainment complex, 50–500 guests.",
    website: "https://symbolbudapest.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "benczur-haz",
    name: "Benczúr Ház Rendezvényközpont",
    category: "venue",
    city: "Budapest",
    address: "1068 Budapest, Benczúr utca 27.",
    capacity_min: 30,
    capacity_max: 180,
    blurb_hu: "Belvárosi villa rendezvényháza, 30–180 fős esküvőkre.",
    blurb_en: "Downtown villa event house, 30–180 guests.",
    website: "https://www.pkalapitvany.hu/bhkk",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "festetics-palota",
    name: "Festetics Palota",
    category: "venue",
    city: "Budapest",
    address: "1088 Budapest, Pollack Mihály tér 3.",
    capacity_min: 50,
    capacity_max: 250,
    blurb_hu: "Múzeumi palota a Pollack Mihály téren, 50–250 fős esküvőkre.",
    blurb_en: "Museum palace on Pollack Mihály square, 50–250 guests.",
    website: "https://festeticspalota.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },

  // ── Shortlist import (hungary_wedding_suppliers_shortlist.xlsx, 2026-05-11) ──
  // 5 entries per category across photographer / videographer / planner /
  // makeup / bridal salon / DJ / florist / live band / hair / photo booth /
  // content creator / officiant / cake. Phone/email kept when published on
  // the vendor's site; otherwise the website is the contact path. Gundel
  // skipped here — already listed above as `gundel-etterem`. "Budapest
  // Wedding" deduplicated to a single planner entry (was duplicated under
  // Content Creator + Officiant in the source sheet).

  // Venues
  {
    id: "aranybastya",
    name: "Aranybástya",
    category: "venue",
    city: "Budapest",
    address: "Budapest I., Budai Vár",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Luxus, panorámás esküvői helyszín a Budai várban.",
    blurb_en: "Luxury panoramic Buda Castle wedding venue.",
    website: "https://en.aranybastya.com/wedding-venue-in-budapest",
    ...noContact,
    contact_phone: "+36 1 200 8817",
    source: "curated",
    price_band: 5,
  },
  {
    id: "budapest-congress-center",
    name: "Budapest Congress Center",
    category: "venue",
    city: "Budapest",
    address: "1123 Budapest, Jagelló út 1-3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Nagy szállodai és konferencia helyszín saját catering szolgáltatással.",
    blurb_en: "Large hotel/conference venue with in-house catering.",
    website: "https://www.bcc.hu/services/event-catering/",
    ...noContact,
    contact_email: "bcc@accor.com",
    contact_phone: "+36 1 372 5400",
    source: "curated",
    price_band: 4,
  },
  {
    id: "brody-house",
    name: "Brody House",
    category: "venue",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Butik vendéglátó csoport rendezvény helyszínekkel; űrlapon elérhető.",
    blurb_en: "Boutique venue and hospitality group; inquiries via the site.",
    website: "https://brody.land/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "kiscelli-muzeum",
    name: "Kiscelli Múzeum",
    category: "venue",
    city: "Budapest",
    address: "Budapest III. kerület",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Történelmi múzeumi helyszín, gyakran használt esküvőkre és rendezvényekre.",
    blurb_en: "Historic museum venue often used for weddings and events.",
    website: "https://kiscellimuzeum.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },

  // Catering
  {
    id: "the-kitchen-caters",
    name: "The Kitchen Caters",
    category: "catering",
    city: "Budapest",
    address: "Budapest, Erzsébet tér 7-8.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Prémium rendezvény-catering; direkt elérhetőség.",
    blurb_en: "Premium catering; direct phone and email public.",
    website: "https://www.thekitchencaters.com/",
    ...noContact,
    contact_email: "info@thekitchencaters.com",
    contact_phone: "+36 20 570 9360",
    source: "curated",
    price_band: 5,
  },
  {
    id: "budapest-catering",
    name: "Budapest Catering",
    category: "catering",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Teljes körű rendezvény-catering; nyilvános ajánlatkérés.",
    blurb_en: "Full-service event catering; public inquiry site.",
    website: "https://budapestcatering.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "connect-catering",
    name: "Connect Catering",
    category: "catering",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Rendezvény és esküvő ready catering Budapesten.",
    blurb_en: "Event and wedding-capable catering.",
    website: "https://connectcatering.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "johnnys-catering",
    name: "Johnny's Catering",
    category: "catering",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Catering szolgáltatások Budapest és Magyarország területén.",
    blurb_en: "Catering services around Budapest and Hungary.",
    website: "https://johnnys.hu/en/catering-services-budapest/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "budapest-congress-center-catering",
    name: "Budapest Congress Center Catering",
    category: "catering",
    city: "Budapest",
    address: "1123 Budapest, Jagelló út 1-3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Saját rendezvény-catering és cukrászdai szolgáltatás.",
    blurb_en: "In-house event catering and confectionery.",
    website: "https://www.bcc.hu/services/event-catering/",
    ...noContact,
    contact_email: "bcc@accor.com",
    contact_phone: "+36 1 372 5400",
    source: "curated",
    price_band: 4,
  },

  // Photographers
  {
    id: "eszter-anna-photography",
    name: "Eszter Anna Photography",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Budapesti székhelyű esküvői fotós.",
    blurb_en: "Budapest-based wedding photographer.",
    website: "https://www.eszterannaphotography.hu/wedding/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "gyula-co",
    name: "GYULA CO — Zacsfalvi Gyula",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Budapesti székhelyű destination esküvői fotós.",
    blurb_en: "Destination wedding photographer based in Budapest.",
    website: "https://gyula.co/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "purephoto",
    name: "PurePhoto",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői fotós csapat; űrlapon e-mail/telefon.",
    blurb_en: "Wedding photography team; contact form collects email and phone.",
    website: "https://purephoto.net/en/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "the-budapest-photographer",
    name: "The Budapest Photographer",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői csomagok feltüntetve; árajánlat-kérés.",
    blurb_en: "Wedding packages displayed; consult request.",
    website: "https://www.thebudapestphotographer.com/weddingphotography",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "kondella-misi",
    name: "Kondella Misi Photography",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Direkt telefon/WhatsApp elérhetőség.",
    blurb_en: "Direct phone/WhatsApp public.",
    website: "https://www.kondellamisi.hu/",
    ...noContact,
    contact_phone: "+36 20 824 6240",
    source: "curated",
    price_band: 3,
  },

  // Videographers
  {
    id: "closer-wedding",
    name: "CLOSER Wedding",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői videós; csomagok 550 000 Ft-tól.",
    blurb_en: "Wedding videography; packages from 550,000 HUF noted on site.",
    website: "https://www.closerwedding.com/contact",
    ...noContact,
    contact_email: "closerweddingstudio@gmail.com",
    contact_phone: "+36 30 782 6136",
    source: "curated",
    price_band: 4,
  },
  {
    id: "connor-delano-weddings",
    name: "Connor Delano Weddings",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Fotó és videós csapat.",
    blurb_en: "Photography and videography team.",
    website: "https://www.connordelano.com/budapest-wedding-photographer/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "alomklip",
    name: "Álomklip",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői filmek (Bridestory lista).",
    blurb_en: "Wedding films vendor listed for Hungary on Bridestory.",
    website: "https://www.bridestory.com/hungary",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "budapest-event-photo-video",
    name: "Budapest Event Photography/Video",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Ügynökség fotózás és esküvői videós bérléssel.",
    blurb_en: "Agency offers photography and wedding videographer hire.",
    website:
      "https://budapestevent.hu/en/event-photography-rental-wedding-videographer-hire-budapest-hungary/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "budapest-fun-photo-video",
    name: "Budapest Fun Photography/Video",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Ügynökség esküvő/rendezvény fotó/videó szolgáltatással.",
    blurb_en: "Agency offers wedding/event photo and video services.",
    website:
      "https://budapestfun.hu/en/event-photography-rental-wedding-videographer-hire-budapest-hungary/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Planners (mapped to "entertainment" — closest existing category)
  {
    id: "budapest-wedding",
    name: "Budapest Wedding",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvő- és rendezvényszervező; direkt elérhetőség.",
    blurb_en: "Wedding and event planner; direct contacts public.",
    website: "https://www.budapestwedding.com/contact-us/",
    ...noContact,
    contact_email: "info@budapestwedding.com",
    contact_phone: "+36 20 323 2215",
    source: "curated",
    price_band: 4,
  },
  {
    id: "beautiful-wedding",
    name: "Beautiful Wedding (Wedding Planner in Hungary)",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Destination esküvő-szervező; direkt elérhetőség.",
    blurb_en: "Destination wedding planner; public direct contact.",
    website: "https://weddingplannerinhungary.com/contact",
    ...noContact,
    contact_email: "timea@beautifulwedding.hu",
    contact_phone: "+36 20 432 6817",
    source: "curated",
    price_band: 4,
  },
  {
    id: "cinderellas-day",
    name: "Cinderella's Day",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvőszervezés; nyilvános telefon/e-mail.",
    blurb_en: "Wedding planning; public phone and email.",
    website: "https://cinderellasday.com/contact-us/",
    ...noContact,
    contact_email: "info@cinderellasday.com",
    contact_phone: "+36 20 360 3920",
    source: "curated",
    price_band: 4,
  },
  {
    id: "hungarianweddings",
    name: "HungarianWeddings.com",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Helyi esküvőszervező nemzetközi és multikulturális esküvőkre.",
    blurb_en: "Local wedding planner for international and multicultural weddings.",
    website: "https://www.hungarianweddings.com/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "my-wedding-planner-hungary",
    name: "My Wedding Planner in Hungary",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Teljes körű esküvőszervező ügynökség nemzetközi esküvőkre.",
    blurb_en: "Full-service planning agency for multinational weddings.",
    website: "https://myweddingplanner.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },

  // Makeup artists
  {
    id: "czikk-luca-makeup",
    name: "Czikk Luca Makeup Artist",
    category: "hair_makeup",
    city: "Budapest",
    address: "1023 Budapest, Bécsi út 4.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Menyasszonyi és fashion smink; direkt elérhetőség.",
    blurb_en: "Bridal and fashion makeup; direct contact.",
    website: "https://www.czikkluca.hu/english/",
    ...noContact,
    contact_email: "czikkluca.makeup@gmail.com",
    contact_phone: "+36 30 703 2848",
    source: "curated",
    price_band: 3,
  },
  {
    id: "sagnes-makeup",
    name: "SÁgnes Makeup",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Menyasszonyi smink; árak nyilvánosak, kedvező árszint.",
    blurb_en: "Bridal makeup with public pricing; budget-friendly.",
    website: "https://www.sagnesmakeup.hu/english/",
    ...noContact,
    contact_email: "agnes.szanto@gmail.com",
    contact_phone: "+36 31 780 2010",
    source: "curated",
    price_band: 2,
  },
  {
    id: "mehes-bettina-makeup",
    name: "Méhes Bettina Makeup",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői és menyasszonyi smink; telefonos elérhetőség.",
    blurb_en: "Wedding and bridal makeup; phone public.",
    website: "https://mehesbettinamakeup.hu/",
    ...noContact,
    contact_phone: "+36 30 153 3505",
    source: "curated",
    price_band: 3,
  },
  {
    id: "nogradi-barbi-makeup",
    name: "Nógrádi Barbi Makeup",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Professzionális menyasszonyi smink szakember.",
    blurb_en: "Professional bridal makeup artist.",
    website: "https://www.nogradibarbi.com/",
    ...noContact,
    contact_email: "nogradibarbimua@gmail.com",
    contact_phone: "+36 20 939 0262",
    source: "curated",
    price_band: 3,
  },
  {
    id: "bridal-beauty-makeup",
    name: "Bridal Beauty — Smink",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Smink és haj esküvőkre; űrlapos elérhetőség.",
    blurb_en: "Makeup and hair for weddings; contact form.",
    website: "https://en.bridalbeauty.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Bridal salons
  {
    id: "la-mariee-budapest",
    name: "La Mariée Budapest",
    category: "attire",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Pronovias menyasszonyi szalon; kapcsolat oldal.",
    blurb_en: "Pronovias bridal salon; contact page.",
    website: "https://lamariee.hu/en/contact/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "wedding-secret",
    name: "Wedding Secret",
    category: "attire",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Időpont egyeztetés telefonon vagy e-mailben.",
    blurb_en: "Appointments by phone or email.",
    website: "https://www.weddingsecret.hu/en/",
    ...noContact,
    contact_email: "info@weddingsecret.hu",
    contact_phone: "+36 20 386 9762",
    source: "curated",
    price_band: 3,
  },
  {
    id: "prive-bridal-boutique",
    name: "Privé Bridal Boutique",
    category: "attire",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Prémium menyasszonyi butik.",
    blurb_en: "Premium bridal boutique.",
    website:
      "https://www.privesalon.hu/en/bridal-boutique-budapest-wedding-dress-rental-shop-and-salon/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "laura-eskuvoi-ruhaszalon",
    name: "Laura Esküvői Ruhaszalon",
    category: "attire",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Régóta működő prémium menyasszonyi ruhaszalon.",
    blurb_en: "Long-running premium bridal salon.",
    website: "https://lauraszalon.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "eskuvopalota",
    name: "Esküvőpalota",
    category: "attire",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Menyasszonyi és vőlegényi ruhák.",
    blurb_en: "Wedding dresses and groom's outfits.",
    website: "https://eskuvopalota.hu/english/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // DJs
  {
    id: "wedding-dj-hungary",
    name: "Wedding DJ Hungary",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői DJ hang- és fénytechnikai szolgáltatással.",
    blurb_en: "Wedding DJ with sound and light services.",
    website: "https://weddingdjhungary.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "slager-dj",
    name: "Sláger DJ",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői DJ; kedvező ár-érték arány.",
    blurb_en: "Wedding DJ; positions itself as good value.",
    website: "https://www.slagerdj.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "eskuvore-dj",
    name: "Esküvőre DJ",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Direkt telefon és e-mail; árazás nyilvános.",
    blurb_en: "Direct phone and email; add-on pricing public.",
    website: "https://www.eskuvoredj.com/kapcsolat",
    ...noContact,
    contact_email: "info@eskuvoredj.com",
    contact_phone: "+36 30 419 9397",
    source: "curated",
    price_band: 3,
  },
  {
    id: "eskuvo-dj",
    name: "Esküvő.DJ",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői DJ, rendezvény DJ, effektek; kapcsolat oldal.",
    blurb_en: "Wedding DJ, event DJ, effects; contact page.",
    website: "https://www.eskuvo.dj/en/contact/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "budapestdj-hu",
    name: "BudapestDj.hu",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvő- és rendezvény DJ, karaoke; 14 év tapasztalat.",
    blurb_en: "Wedding/event DJ and karaoke; 14 years' experience.",
    website: "https://budapestdj.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Florists / decor
  {
    id: "fleurt",
    name: "FLEURT",
    category: "decor_floral",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Luxus virágdekoráció esküvőkre és rendezvényekre.",
    blurb_en: "Luxury flower decoration for weddings and events.",
    website: "https://fleurt.hu/english/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "szirom-flowers",
    name: "Szirom Flowers",
    category: "decor_floral",
    city: "Budapest",
    address: "1067 Budapest, Podmaniczky utca 39.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői virágok; nyilvános e-mail és bolti cím.",
    blurb_en: "Wedding flowers; email and shop address public.",
    website: "https://www.szirom.hu/wedding/",
    ...noContact,
    contact_email: "eskuvo@szirom.hu",
    source: "curated",
    price_band: 3,
  },
  {
    id: "fiori-damore-wedding",
    name: "Fiori d'Amore Wedding",
    category: "decor_floral",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Luxus esküvői virágkötő és dekorátor.",
    blurb_en: "Luxury wedding florist and decorator.",
    website: "https://fioridamorewedding.com/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "budapest-flower",
    name: "Budapest Flower",
    category: "decor_floral",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői virágkötés; telefonos elérhetőség.",
    blurb_en: "Wedding flower work; phone public.",
    website: "https://www.budapestflower.hu/en/eskuvo",
    ...noContact,
    contact_phone: "+36 20 592 0263",
    source: "curated",
    price_band: 3,
  },
  {
    id: "dolce-vita-flowers",
    name: "Dolce Vita Flowers",
    category: "decor_floral",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Prémium virágkiszállítás; direkt elérhetőség.",
    blurb_en: "Premium flower delivery; direct contacts public.",
    website: "https://www.dolcevitaflowersbp.com/",
    ...noContact,
    contact_email: "dolcevitaflowershop@gmail.com",
    contact_phone: "+36 30 169 0303",
    source: "curated",
    price_band: 3,
  },

  // Wedding bands / live music
  {
    id: "budapest-showtime",
    name: "Budapest Showtime",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Professzionális élő zenekar rendezvényekre.",
    blurb_en: "Professional live band for events.",
    website: "https://budapestshowtime.com/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "budapest-show-band",
    name: "Budapest Show Band",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Buli- és esküvői zenekar.",
    blurb_en: "Party, event and wedding band.",
    website: "https://www.budapestshowband.com/en",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "the-sparkle-band",
    name: "The Sparkle Band",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Luxus esküvői zenekar; budapesti foglalási oldal.",
    blurb_en: "Luxury wedding band; Budapest booking page.",
    website: "https://www.thesparkleband.com/wedding-band-budapest",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "budapest-event-band-hire",
    name: "Budapest Event Band Hire",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Cover- és élő zenekar bérlés ügynökség.",
    blurb_en: "Agency for cover bands and live music.",
    website: "https://budapestevent.hu/en/party-music-band-hire-budapest/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "gig-heaven-bands",
    name: "Gig Heaven Wedding Bands Budapest",
    category: "music_dj",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Piactér foglalható esküvői zenekarokkal; nyilvános árak.",
    blurb_en: "Marketplace of bookable wedding bands with public price ranges.",
    website: "https://www.gigheaven.com/search/wedding-bands/hungary/budapest.html",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Hair stylists
  {
    id: "szabo-balazs-peter",
    name: "Szabó Balázs Péter",
    category: "hair_makeup",
    city: "Budapest",
    address: "1136 Budapest, Hegedűs Gyula utca 24/a.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői és alkalmi haj csomagok.",
    blurb_en: "Wedding and occasion hair packages.",
    website: "https://szabobalazspeter.hu/en/",
    ...noContact,
    contact_email: "info@szabobalazspeter.hu",
    contact_phone: "+36 20 937 3637",
    source: "curated",
    price_band: 3,
  },
  {
    id: "sebok-dorina",
    name: "Sebők Dorina",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői haj specialista.",
    blurb_en: "Wedding hair specialist.",
    website: "https://www.sebokdorina.hu/en/home/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "haircode",
    name: "HairCode",
    category: "hair_makeup",
    city: "Budapest",
    address: "1065 Budapest, Révay u. 1.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Központi fodrász stúdió; direkt elérhetőség.",
    blurb_en: "Central hair studio; direct contacts public.",
    website: "https://www.haircode.eu/",
    ...noContact,
    contact_email: "haircodeteam@gmail.com",
    contact_phone: "+36 20 384 1690",
    source: "curated",
    price_band: 3,
  },
  {
    id: "mosaic-hair",
    name: "Mosaic Hair",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Szalon nyilvános elérhetőséggel.",
    blurb_en: "Salon contact public.",
    website: "https://mosaic-hair.salonic.hu/contact",
    ...noContact,
    contact_email: "mosaicheadspa@gmail.com",
    contact_phone: "+36 20 247 4444",
    source: "curated",
    price_band: 3,
  },
  {
    id: "bridal-beauty-hair",
    name: "Bridal Beauty — Haj",
    category: "hair_makeup",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Smink és haj esküvőkre.",
    blurb_en: "Makeup and hair for weddings.",
    website: "https://en.bridalbeauty.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Photo booths
  {
    id: "hashtagselfie-hungary",
    name: "HashtagSelfie Hungary",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői fotóbox és selfie állomás országosan.",
    blurb_en: "Photo booth/selfie station for weddings; nationwide.",
    website: "https://www.hashtagselfie.hu/en",
    ...noContact,
    contact_email: "info@hashtagselfie.hu",
    contact_phone: "+36 20 429 9395",
    source: "curated",
    price_band: 3,
  },
  {
    id: "party-booth",
    name: "Party Booth",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Modern fotóbox; direkt elérhetőség.",
    blurb_en: "Modern photo booth; direct contacts.",
    website: "https://www.partybooth.hu/en/contact/",
    ...noContact,
    contact_email: "hello@partybooth.hu",
    contact_phone: "+36 30 940 8075",
    source: "curated",
    price_band: 3,
  },
  {
    id: "photobooth-in-budapest",
    name: "Photobooth in Budapest",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Direkt telefon és e-mail.",
    blurb_en: "Direct phone and email.",
    website: "https://www.photoboothinbudapest.com/",
    ...noContact,
    contact_email: "hello@photoboothinbudapest.com",
    contact_phone: "+36 30 317 9196",
    source: "curated",
    price_band: 3,
  },
  {
    id: "myway-photobox",
    name: "MyWayPhotobox",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Fotóbox és selfie állomás országos bérlés.",
    blurb_en: "Photo booth/selfie machine rentals nationwide.",
    website: "https://mywayphotobox.eu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "instant-selfie",
    name: "InstantSelfie",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Fotóbox és selfiebox bérlés.",
    blurb_en: "Photobox/selfiebox rental.",
    website: "https://instantselfie.hu/en/photobox-hungary/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Content creators (mapped to photo_video)
  {
    id: "wezoree-budapest-content",
    name: "Wezoree Content Creator marketplace",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Piactér Budapest content creator kategóriával és induló árakkal.",
    blurb_en: "Marketplace listing Budapest content creators with starting prices.",
    website: "https://wezoree.com/vendors/budapest/content-creator/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "luxwedd-athens-budapest",
    name: "Luxwedd Athens (Budapest via Wezoree)",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Listázott Budapest content creator; magasabb árszint a katalógusban.",
    blurb_en: "Listed in Budapest content creators; high-end pricing on directory.",
    website: "https://wezoree.com/vendors/budapest/content-creator/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "hipstudio",
    name: "HIPStudio",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Digitális tartalomgyártó ügynökség; nem kifejezetten esküvő-specifikus.",
    blurb_en: "Digital content production agency; not wedding-specific.",
    website: "https://www.hipstudio.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "upwork-content-creators-budapest",
    name: "Upwork Content Creators — Budapest",
    category: "photo_video",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Freelancer piactér opció; egyenként ellenőrizendő.",
    blurb_en: "Freelance marketplace option; vet individually.",
    website: "https://www.upwork.com/hire/content-creators/hu/budapest/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },

  // Wedding officiants / celebrants
  {
    id: "your-story-ceremony",
    name: "Your Story Ceremony",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Nemzetközi szertartásvezető szolgáltatás Budapesten.",
    blurb_en: "International celebrant service in Budapest.",
    website: "https://www.yourstoryceremony.com/english",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "native-ceremony",
    name: "Native Ceremony",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Többnyelvű esküvői MC és szertartás szolgáltatás.",
    blurb_en: "Multilingual wedding MC and ceremony service; contact form.",
    website: "https://nativeceremony.eu/en/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "gabor-herendi",
    name: "Gábor Herendi",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "MC és szertartásvezető HU/EN/ES nyelven.",
    blurb_en: "MC and wedding officiant in Hungarian, English and Spanish.",
    website: "https://herendigabor.hu/master-of-ceremonies-hungary",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "gig-heaven-celebrants",
    name: "Gig Heaven Celebrants Budapest",
    category: "entertainment",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Szertartásvezetők piactere.",
    blurb_en: "Marketplace for celebrants and officiants.",
    website:
      "https://www.gigheaven.com/search/wedding-officiants-wedding-celebrants/hungary/budapest.html",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Cake / dessert
  {
    id: "peace-of-cake",
    name: "Peace of Cake — Pinczel Orsi",
    category: "cake_dessert",
    city: "Budapest",
    address: "1136 Budapest, Hegedűs Gyula utca 20.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői torták; direkt elérhetőség.",
    blurb_en: "Wedding cakes; direct contacts.",
    website: "https://peaceofcake.hu/kapcsolat/",
    ...noContact,
    contact_email: "hello@peaceofcake.hu",
    contact_phone: "+36 20 661 4311",
    source: "curated",
    price_band: 3,
  },
  {
    id: "gerbeaud",
    name: "Gerbeaud",
    category: "cake_dessert",
    city: "Budapest",
    address: "1051 Budapest, Vörösmarty tér 7-8.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi torta rendelés sales e-mailen keresztül.",
    blurb_en: "Custom cake orders via sales email.",
    website: "https://gerbeaudwebshop.hu/en/pages/kapcsolat",
    ...noContact,
    contact_email: "sales@gerbeaud.hu",
    contact_phone: "+36 1 429 9000",
    source: "curated",
    price_band: 5,
  },
  {
    id: "muvesz-cafe",
    name: "Művész Café",
    category: "cake_dessert",
    city: "Budapest",
    address: "1061 Budapest, Andrássy út 29.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői és rendezvény torták.",
    blurb_en: "Cakes for weddings and events.",
    website: "https://www.muveszkavehaz.com/en/cakes-ordering/",
    ...noContact,
    contact_email: "info@muveszkavehaz.com",
    contact_phone: "+36 70 333 2116",
    source: "curated",
    price_band: 4,
  },
  {
    id: "cake-to-go-budapest",
    name: "Cake to go Budapest",
    category: "cake_dessert",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi torta ajánlatkérés űrlapon.",
    blurb_en: "Custom cake inquiry form.",
    website: "https://caketogobudapest.hu/kapcsolat/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "szivemcsucske-tortamuhely",
    name: "Szívemcsücske Tortaműhely",
    category: "cake_dessert",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi torták és kiszállítás.",
    blurb_en: "Custom cakes and delivery.",
    website: "https://szivemcsucsketorta.hu/?lang=en",
    ...noContact,
    source: "curated",
    price_band: 3,
  },

  // Tent / pavilion (sátor)
  {
    id: "rg-sator-party-service",
    name: "RG Sátor & Party Service",
    category: "tent_pavilion",
    city: "Túrkeve",
    address: "5420 Túrkeve, Németh utca 1.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői és raktársátor bérlés bútor- és kiegészítő-kölcsönzéssel.",
    blurb_en: "Wedding and storage tent rental with furniture and accessory hire.",
    website: "https://rgsator.hu/",
    ...noContact,
    contact_email: "info@rgsator.hu",
    contact_phone: "+36 20 988 4399",
    source: "curated",
    price_band: 3,
  },
  {
    id: "tofisator",
    name: "TOFI 2005 Kft. (Tofisátor)",
    category: "tent_pavilion",
    city: "Rábapaty",
    address: "9641 Rábapaty, Petőfi utca",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Sátorbérlésre specializált, projektalapú rendezvénysetup.",
    blurb_en: "Specialist tent rental for project-based event setups.",
    website: "http://www.tofisator.hu/",
    ...noContact,
    contact_email: "info@tofisator.hu",
    contact_phone: "+36 30 939 3796",
    source: "curated",
    price_band: 4,
  },
  {
    id: "satorszerviz",
    name: "Sátorszerviz (Zsomboys Bt & Kristály Bt)",
    category: "tent_pavilion",
    city: "Zsombó",
    address: "6792 Zsombó, Szatymazi út 1.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Személyre szabott sátorbérlés, gyors ajánlatadás rendezvényekre.",
    blurb_en: "Bespoke tent rental with fast quotes for events.",
    website: "https://satorszerviz.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "nomad-tent",
    name: "Nomad Tent Kft.",
    category: "tent_pavilion",
    city: "Budapest",
    address: "1191 Budapest, József Attila utca 36-42.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "NOMADIK kültéri fedések bérlése esküvőkre és exkluzív szabadtéri eseményekre.",
    blurb_en: "NOMADIK outdoor stretch tents for weddings and premium open-air events.",
    website: "https://nomadpartysator.hu/",
    ...noContact,
    contact_email: "info@nomadpartysator.hu",
    contact_phone: "+36 70 773 3927",
    source: "curated",
    price_band: 4,
  },
  {
    id: "sls-rendezvenytechnika-tent",
    name: "SLS Rendezvénytechnika Kft. — sátor",
    category: "tent_pavilion",
    city: "Szentes",
    address: "6600 Szentes, Vásárhelyi út 114.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Sátrak hang-, fény- és színpadtechnikával egy kézben.",
    blurb_en: "Tents bundled with sound, lighting and stage tech from one supplier.",
    website: "https://slsrendezvenytechnika.hu/",
    ...noContact,
    contact_email: "vigh.peter@slsrendezvenytechnika.hu",
    contact_phone: "+36 70 332 9572",
    source: "curated",
    price_band: 3,
  },
  {
    id: "sps-satorrendeles",
    name: "SPS Rendezvénytechnika Kft.",
    category: "tent_pavilion",
    city: "Levél",
    address: "9221 Levél, Fő utca 31.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "5–15 m széles rendezvény- és VIP sátrak teljes építés-bontással, kazettás aljzattal.",
    blurb_en: "5–15 m event and VIP tents with full build/teardown and floor systems.",
    website: "https://www.satorrendeles.hu/",
    ...noContact,
    contact_email: "info@satorrendeles.hu",
    contact_phone: "+36 20 971 8495",
    source: "curated",
    price_band: 4,
  },
  {
    id: "picos-partysator",
    name: "Picos 53 Kft. (Partysátor)",
    category: "tent_pavilion",
    city: "Bag",
    address: "2191 Bag, Vasút út 3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Partysátor bérlés Budapest, Gödöllő, Aszód térségében, kb. 100 km-es vonzáskörzetben.",
    blurb_en: "Party tent rental serving Budapest, Gödöllő, Aszód and ~100 km around.",
    website: "https://partysator.109.hu/",
    ...noContact,
    contact_email: "info@partysator.hu",
    contact_phone: "+36 30 951 3184",
    source: "curated",
    price_band: 2,
  },
  {
    id: "budapestevent-tent",
    name: "BudapestEvent Rendezvényszolgáltató — sátor",
    category: "tent_pavilion",
    city: "Budapest",
    address: "1015 Budapest, Széna tér 7. I/9.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Sátor- és helyszínközvetítés, technika és teljes rendezvénylebonyolítás.",
    blurb_en: "Tent and venue sourcing, technical and full event production.",
    website: "https://budapestevent.hu/",
    ...noContact,
    contact_email: "info@budapestevent.hu",
    contact_phone: "+36 1 950 9960",
    source: "curated",
    price_band: 4,
  },
  {
    id: "cambium-rendezveny-tent",
    name: "Cambium Rendezvényszervező — stretch sátor",
    category: "tent_pavilion",
    city: "Budapest",
    address: "1077 Budapest, Kis Diófa utca 11. 3/3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "2 db 10×15 m NOMADIK stretch sátor; összekapcsolva 300 nm lefedés.",
    blurb_en: "Two 10×15 m NOMADIK stretch tents; combinable to 300 sqm cover.",
    website: "https://www.cambiumrendezveny.hu/",
    ...noContact,
    contact_email: "cambiumrendezveny@gmail.com",
    contact_phone: "+36 20 568 7358",
    source: "curated",
    price_band: 4,
  },
  {
    id: "sp-event-sorpad",
    name: "SP EVENT Kft. (Sörpad & sátor)",
    category: "tent_pavilion",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "3×3 m és 3×6 m sátrak; sörpadokkal kb. 24–32 fő leültetésére.",
    blurb_en: "3×3 m and 3×6 m tents; seats around 24–32 with beer-bench sets.",
    website: "https://sorpad.hu/berles/sator-berles/",
    ...noContact,
    contact_email: "info@sorpad.hu",
    contact_phone: "+36 20 368 3332",
    source: "curated",
    price_band: 2,
  },

  // Sound & AV tech (hangtechnika)
  {
    id: "uwave-hu",
    name: "uwave.hu",
    category: "sound_tech",
    city: "Budapest",
    address: "1141 Budapest, Cserebogár utca 42.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Mobil kihangosítás a kis megbeszéléstől a több száz fős rendezvényig.",
    blurb_en: "Mobile PA from small meetings up to multi-hundred-guest events.",
    website: "https://uwave.hu/",
    ...noContact,
    contact_email: "hangositok@gmail.com",
    contact_phone: "+36 20 430 4999",
    source: "curated",
    price_band: 3,
  },
  {
    id: "nortyx-hangcuccberles",
    name: "Nortyx Pro Kft. (Hangcuccbérlés.hu)",
    category: "sound_tech",
    city: "Érd",
    address: "2030 Érd, Lőcsei utca 61.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői és rendezvényhang- és fénytechnika kiszállítva Budapesten és környékén.",
    blurb_en: "Wedding and event sound and lighting delivered around Budapest.",
    website: "https://hangcuccberles.hu/",
    ...noContact,
    contact_email: "peter@nortyx.hu",
    contact_phone: "+36 30 587 1922",
    source: "curated",
    price_band: 3,
  },
  {
    id: "hangtechnikaberles",
    name: "HangtechnikaBerles.hu",
    category: "sound_tech",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "JBL minőségű mobil hangrendszerek kis és nagy rendezvényekre.",
    blurb_en: "JBL-class mobile PA systems for small and large events.",
    website: "https://hangtechnikaberles.hu/",
    ...noContact,
    contact_phone: "+36 20 469 4224",
    source: "curated",
    price_band: 3,
  },
  {
    id: "slv-rendezvenytechnika",
    name: "SLV Rendezvénytechnika",
    category: "sound_tech",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Hangosítás, fénytechnika és vizuáltechnika prémium márkákkal.",
    blurb_en: "Sound, lighting and visual tech with premium brand inventory.",
    website: "https://slvrendezvenytechnika.hu/",
    ...noContact,
    contact_email: "info@slvrendezvenytechnika.hu",
    contact_phone: "+36 70 415 7707",
    source: "curated",
    price_band: 3,
  },
  {
    id: "sls-rendezvenytechnika-sound",
    name: "SLS Rendezvénytechnika Kft. — hang",
    category: "sound_tech",
    city: "Szentes",
    address: "6600 Szentes, Vásárhelyi út 114.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Hang-, fény- és színpadtechnika komplett rendezvényszolgáltatással.",
    blurb_en: "Sound, lighting and stage tech with full event services.",
    website: "https://slsrendezvenytechnika.hu/",
    ...noContact,
    contact_email: "vigh.peter@slsrendezvenytechnika.hu",
    contact_phone: "+36 70 332 9572",
    source: "curated",
    price_band: 4,
  },
  {
    id: "av-rental",
    name: "AV Rental (Audiovisual Rental Kft.)",
    category: "sound_tech",
    city: "Budapest",
    address: "1107 Budapest, Mázsa utca 3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Rendezvénytechnika és hangosítás céges partnerekkel; magánszemélyes bérlés nélkül.",
    blurb_en: "Event tech and sound for corporate partners; no consumer rentals.",
    website: "https://av-rental.hu/",
    ...noContact,
    contact_email: "info@av-rental.hu",
    source: "curated",
    price_band: 4,
  },
  {
    id: "soundwork",
    name: "Soundwork",
    category: "sound_tech",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Professzionális AV-rendszerek, hangfelvétel és kreatív-technikai partneri háttér 2013 óta.",
    blurb_en: "Pro AV systems, recording and creative-technical partner since 2013.",
    website: "https://www.soundwork.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "budapestevent-sound",
    name: "BudapestEvent Rendezvényszolgáltató — hang",
    category: "sound_tech",
    city: "Budapest",
    address: "1015 Budapest, Széna tér 7. I/9.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Technikai szolgáltatás a teljes rendezvénylebonyolítás részeként, helyszín- és műsorszervezéssel.",
    blurb_en: "Technical services bundled into full event production and venue/programme planning.",
    website: "https://budapestevent.hu/",
    ...noContact,
    contact_email: "info@budapestevent.hu",
    contact_phone: "+36 1 950 9960",
    source: "curated",
    price_band: 4,
  },
  {
    id: "cambium-rendezveny-sound",
    name: "Cambium Rendezvényszervező — hangtechnika",
    category: "sound_tech",
    city: "Budapest",
    address: "1077 Budapest, Kis Diófa utca 11. 3/3.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Hangosítás, fények és rendezvénytechnikai eszközök esküvőkre.",
    blurb_en: "Sound, lighting and event tech tailored to weddings.",
    website: "https://www.cambiumrendezveny.hu/",
    ...noContact,
    contact_email: "cambiumrendezveny@gmail.com",
    contact_phone: "+36 20 568 7358",
    source: "curated",
    price_band: 3,
  },
  {
    id: "avadvice",
    name: "AVadvice (AV Advice Kft.)",
    category: "sound_tech",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "LED-fal, vetítés, L-Acoustics és speciális AV-megoldások 2004 óta.",
    blurb_en: "LED walls, projection, L-Acoustics and specialist AV since 2004.",
    website: "https://www.avadvice.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },

  // Wedding rings (jegygyűrű)
  {
    id: "ekszerpalota-karikagyuru",
    name: "Ékszerpalota (Karikagyuru.hu)",
    category: "rings",
    city: "Budapest",
    address: "1061 Budapest, Andrássy út 43.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Bemutatóterem az Andrássy úton; személyes karikagyűrű-konzultáció.",
    blurb_en: "Showroom on Andrássy út with personal wedding-ring consultations.",
    website: "https://www.karikagyuru.hu/",
    ...noContact,
    contact_email: "info@ekszerpalota.hu",
    contact_phone: "+36 70 417 0900",
    source: "curated",
    price_band: 4,
  },
  {
    id: "feil-karikagyurugyarto",
    name: "FEIL Karikagyűrűgyártó",
    category: "rings",
    city: "Budapest",
    address: "1089 Budapest, Gaál Mózes utca 5-7. I/104.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Exkluzív budapesti és szegedi bemutatóterem, előzetes időpontfoglalással.",
    blurb_en: "Exclusive Budapest and Szeged showrooms, by appointment only.",
    website: "https://karikagyurugyarto.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "gyuru-neked",
    name: "Gyűrű Neked",
    category: "rings",
    city: "Budapest",
    address: "1055 Budapest, Bihari János utca 1.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Központi bemutatóterem, törtarany-beszámítás, 100% elégedettségi garancia.",
    blurb_en: "Downtown showroom with scrap-gold trade-in and satisfaction guarantee.",
    website: "https://gyuruneked.hu/",
    ...noContact,
    contact_email: "info@gyuruneked.hu",
    contact_phone: "+36 70 771 6651",
    source: "curated",
    price_band: 3,
  },
  {
    id: "bojti-ekszer",
    name: "BOJTI Ékszermanufaktúra",
    category: "rings",
    city: "Budapest",
    address: "1054 Budapest, Alkotmány utca 19.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Exkluzív belvárosi szalon; készletről és egyedi rendelésre is.",
    blurb_en: "Exclusive downtown salon; off-the-shelf and bespoke commissions.",
    website: "https://www.bojtiekszer.hu/",
    ...noContact,
    contact_email: "bojtiekszer@bojtiekszer.hu",
    contact_phone: "+36 30 515 4383",
    source: "curated",
    price_band: 4,
  },
  {
    id: "jegygyurubolt",
    name: "Jegygyűrűbolt.hu",
    category: "rings",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "27+ páros karikagyűrű-modell; sok termék 24 990 Ft/pár belépő ársávban.",
    blurb_en: "27+ paired ring models; many entries around 24,990 HUF/pair.",
    website: "https://jegygyurubolt.hu/",
    ...noContact,
    source: "curated",
    price_band: 1,
  },
  {
    id: "gyemantgyuru",
    name: "Gyémántgyűrű (Gyémántgyűrű Kft.)",
    category: "rings",
    city: "Budapest",
    address: "1061 Budapest, Király utca 8-10.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Gyémánt- és drágaköves jegygyűrűk, kézzel készített arany ékszerek szaküzlete.",
    blurb_en: "Specialist store for diamond and gemstone rings, hand-crafted gold pieces.",
    website: "https://www.gyemantgyuru.hu/",
    ...noContact,
    source: "curated",
    price_band: 5,
  },
  {
    id: "karikagyuru-specialista",
    name: "Karikagyűrű Specialista",
    category: "rings",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Kizárólag egyedi megrendelések, személyes konzultációval.",
    blurb_en: "Custom-only rings with personal in-studio consultation.",
    website: "https://www.karikagyuruspecialista.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "monis-diamond",
    name: "Moni's Diamond (S-Gold Kft.)",
    category: "rings",
    city: "Budapest",
    address: "1051 Budapest, Október 6. utca 6.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Prémium bridal kollekció; személyes tanácsadás belvárosi üzletben.",
    blurb_en: "Premium bridal collection with downtown showroom advisory.",
    website: "https://www.monis.hu/",
    ...noContact,
    contact_email: "marketing@monis.hu",
    contact_phone: "+36 20 394 3222",
    source: "curated",
    price_band: 5,
  },
  {
    id: "schmuck-ekszer",
    name: "Schmuck Ékszer",
    category: "rings",
    city: "Kecskemét",
    address: "6000 Kecskemét, Korona utca 2., Földszint",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Több üzletből álló hálózat; Gerstner karikagyűrű-tervezés.",
    blurb_en: "Multi-store network with Gerstner wedding-ring design.",
    website: "https://www.schmuckekszer.hu/",
    ...noContact,
    contact_phone: "+36 76 320 028",
    source: "curated",
    price_band: 3,
  },
  {
    id: "velekey-ekszervilag",
    name: "Velekey Ékszervilág Kft.",
    category: "rings",
    city: "Szombathely",
    address: "9700 Szombathely, Fő tér 25.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Több üzlet (Szombathely, Hévíz, Zalaegerszeg), karikagyűrű-konfigurátor és időpontfoglalás.",
    blurb_en: "Stores in Szombathely, Hévíz, Zalaegerszeg with online ring configurator.",
    website: "https://www.velekey-ekszervilag.hu/",
    ...noContact,
    contact_email: "info@velekey-ekszervilag.hu",
    contact_phone: "+36 70 427 7212",
    source: "curated",
    price_band: 3,
  },

  // Nails (köröm)
  {
    id: "nails-house",
    name: "Nails House",
    category: "nails",
    city: "Budapest",
    address: "1064 Budapest, Rózsa utca 99-101.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Nagy szalon 3 szolgáltatási szinttel: manikűr, műköröm, pedikűr.",
    blurb_en: "Large salon with 3 service tiers: manicure, nail extensions, pedicure.",
    website: "https://nailshouse.hu/",
    ...noContact,
    contact_email: "info@nailshouse.hu",
    contact_phone: "+36 30 010 3444",
    source: "curated",
    price_band: 3,
  },
  {
    id: "lux-nail-bar",
    name: "Lux Nail Bar",
    category: "nails",
    city: "Budapest",
    address: "1138 Budapest, Szekszárdi utca 17.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Online foglalható budapesti körömszalon.",
    blurb_en: "Online-bookable Budapest nail salon.",
    website: "https://luxnailbar.salonic.hu/contact",
    ...noContact,
    contact_phone: "+36 30 160 4050",
    source: "curated",
    price_band: 3,
  },
  {
    id: "coco-nail-spa",
    name: "Coco Nail Spa",
    category: "nails",
    city: "Budapest",
    address: "1032 Budapest, Bécsi út 154. (GoBuda Mall)",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Prémium manikűr szolgáltatások mall lokációban, online foglalással.",
    blurb_en: "Premium manicure services in a mall location with online booking.",
    website: "https://www.coconail.hu/",
    ...noContact,
    contact_email: "hello@coconail.hu",
    contact_phone: "+36 70 784 7172",
    source: "curated",
    price_band: 4,
  },
  {
    id: "elite-nails-salon",
    name: "Elite Nails Salon",
    category: "nails",
    city: "Budapest",
    address: "1012 Budapest, Pálya utca 17.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Butikjellegű szalon online/telefonos időpontkezeléssel.",
    blurb_en: "Boutique-style salon with online and phone appointment management.",
    website: "https://elitenails.hu/",
    ...noContact,
    contact_email: "elitenails@elitenails.hu",
    contact_phone: "+36 70 268 1001",
    source: "curated",
    price_band: 4,
  },
  {
    id: "budapest-nails",
    name: "Budapest Nails",
    category: "nails",
    city: "Budapest",
    address: "1065 Budapest, Hajós utca 41.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Széles kéz- és lábápolási kínálat; gélmanikűr fókusszal.",
    blurb_en: "Broad hand and foot care; gel manicure a flagship service.",
    website: "https://budapest-nails.salonic.hu/contact",
    ...noContact,
    contact_email: "budapestnails.info@gmail.com",
    contact_phone: "+36 30 556 5117",
    source: "curated",
    price_band: 3,
  },
  {
    id: "nude-nails-salon",
    name: "Nude Nails Salon",
    category: "nails",
    city: "Budapest",
    address: "1015 Budapest, Donáti utca 38.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Hétfőtől vasárnapig nyitva tartó manikűr-szalon Budán.",
    blurb_en: "Buda-side manicure salon open every day of the week.",
    website: "https://www.nude-nails-salon.com/",
    ...noContact,
    contact_email: "nudenailsbuda@gmail.com",
    contact_phone: "+36 20 561 0559",
    source: "curated",
    price_band: 3,
  },
  {
    id: "spirit-nail-spa",
    name: "Spirit Nail Spa",
    category: "nails",
    city: "Budapest",
    address: "1051 Budapest, József Nádor tér 8.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Spa-élmény, steril környezet, gépi orosz manikűr a belvárosban.",
    blurb_en: "Spa experience, sterile setup, e-file Russian manicure downtown.",
    website: "https://spiritnailspa.hu/hu/",
    ...noContact,
    contact_email: "salon@spiritnailspa.hu",
    contact_phone: "+36 70 615 1200",
    source: "curated",
    price_band: 4,
  },
  {
    id: "glosslab-budapest",
    name: "The Gloss Lab (GLOSSLAB Kft.)",
    category: "nails",
    city: "Budapest",
    address: "1051 Budapest, Nádor utca 8. Fsz 5.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu:
      "Indigo Nails professzionális magyarországi képviselete; manikűr, pedikűr és termékek.",
    blurb_en: "Indigo Nails' Hungarian pro distributor; manicure, pedicure and product sales.",
    website: "https://theglosslabbudapest.hu/",
    ...noContact,
    contact_email: "info@theglosslabbudapest.hu",
    contact_phone: "+36 70 329 9444",
    source: "curated",
    price_band: 4,
  },
  {
    id: "coco-nail-studio",
    name: "Coco Nail Studio",
    category: "nails",
    city: "Budapest",
    address: "1117 Budapest, Alíz utca 6/B.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Modern szalon a Bolero Lakóparkban, széles nyitvatartással és online foglalással.",
    blurb_en: "Modern salon in Bolero Residential Park with wide hours and online booking.",
    website: "https://coconailstudio.hu/",
    ...noContact,
    contact_email: "coconailstudiooo@gmail.com",
    contact_phone: "+36 70 609 5444",
    source: "curated",
    price_band: 3,
  },
  {
    id: "a-list-salon-spa",
    name: "A-list Salon & Spa (A-LIST Nádor Kft.)",
    category: "nails",
    city: "Budapest",
    address: "1051 Budapest, József Nádor tér 8.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "3 szalon, 34 kolléga; manikűr-pedikűr külön szakemberszintekkel.",
    blurb_en: "3 salons, 34 staff; manicure and pedicure across distinct specialist tiers.",
    website: "https://www.a-list.hu/",
    ...noContact,
    contact_email: "salon@a-list.hu",
    contact_phone: "+36 70 615 1200",
    source: "curated",
    price_band: 4,
  },

  // Wedding website (esküvői weboldal)
  {
    id: "weddingproject",
    name: "WeddingProject (Papp Nikolett EV.)",
    category: "wedding_website",
    city: "Miskolc",
    address: "3535 Miskolc, Csipkevirág utca 13-15.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "RSVP, idővonal, szállásinfó; sablonok és személyre szabás.",
    blurb_en: "RSVP, timeline, accommodation info; templates and personalisation.",
    website: "https://weddingproject.hu/",
    ...noContact,
    contact_email: "info@weddingproject.hu",
    contact_phone: "+36 30 553 1652",
    source: "curated",
    price_band: 3,
  },
  {
    id: "eskuvoi-weboldalam",
    name: "Esküvői Weboldalam (GK Studio)",
    category: "wedding_website",
    city: "Mohács",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Mobilbarát, gyors határidejű esküvői weboldalak, mintasablonokkal.",
    blurb_en: "Mobile-friendly wedding websites with quick turnaround and templates.",
    website: "https://eskuvoiweboldalam.hu/",
    ...noContact,
    contact_email: "info@gregusskaroly.hu",
    contact_phone: "+36 20 256 4425",
    source: "curated",
    price_band: 3,
  },
  {
    id: "weboldal-eskuvore",
    name: "Weboldal Esküvőre",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Menü, ülésrend, RSVP, szállás, ajándéklista; kb. 2–3 hét megvalósítás.",
    blurb_en: "Menu, seating plan, RSVP, accommodation, gift list; ~2–3 week delivery.",
    website: "https://weboldaleskuvore.hu/",
    ...noContact,
    contact_email: "info@weboldaleskuvore.hu",
    contact_phone: "+36 20 228 8081",
    source: "curated",
    price_band: 3,
  },
  {
    id: "eskuvoi-weboldal-keszites",
    name: "Esküvő weboldal készítés",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi, nem sablonalapú weboldalak; nyilvános 49 000 Ft-os csomagár.",
    blurb_en: "Custom, non-template wedding sites; published 49,000 HUF package.",
    website: "https://eskuvoi-weboldal-keszites.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "webwedding",
    name: "WebWedding.hu",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Alapcsomag 35 000 Ft, bővített csomag 45 000 Ft; mobilbarát esküvői honlapok.",
    blurb_en: "Basic package 35,000 HUF, extended 45,000 HUF; mobile-friendly wedding sites.",
    website: "https://www.webwedding.hu/",
    ...noContact,
    contact_email: "info@webwedding.hu",
    source: "curated",
    price_band: 2,
  },
  {
    id: "weddingtree",
    name: "WeddingTree.hu",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi esküvői honlap, funkciók és minták publikus felülettel.",
    blurb_en: "Custom wedding sites with feature catalogue and public design samples.",
    website: "https://weddingtree.hu/",
    ...noContact,
    contact_email: "info@weddingtree.hu",
    source: "curated",
    price_band: 3,
  },
  {
    id: "egyedi-eskuvoi-honlapok",
    name: "EgyediEsküvőiHonlapok.hu",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Vendégregisztráció, interaktív ajándéklista, papírmeghívóval harmonizált design.",
    blurb_en: "Guest sign-in, interactive gift list, design aligned with paper invites.",
    website: "https://egyedieskuvoihonlapok.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "eskuvonknapja",
    name: "Esküvőnknapja.hu",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "4 alap sablon; online meghívó és weboldal egy csomagban.",
    blurb_en: "4 base templates; online invite and website bundled.",
    website: "https://eskuvonknapja.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "nagynapunk",
    name: "NagyNapunk.hu",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Digitális esküvői honlap és RSVP-funkció magyar nyelvű ügyfélkapcsolattal.",
    blurb_en: "Digital wedding site with RSVP and Hungarian-language support.",
    website: "https://www.nagynapunk.hu/",
    ...noContact,
    contact_email: "hello@nagynapunk.hu",
    contact_phone: "+36 30 925 6291",
    source: "curated",
    price_band: 3,
  },
  {
    id: "flower-wedding",
    name: "Flower Wedding",
    category: "wedding_website",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvőszervezői szemléletű digitális kommunikáció és online jelenlét.",
    blurb_en: "Wedding-planner-led digital communications and online presence.",
    website: "https://flowerwedding.hu/",
    ...noContact,
    contact_email: "hello@flowerwedding.hu",
    source: "curated",
    price_band: 4,
  },

  // Stationery: seating plans, place / menu cards, invites
  {
    id: "amare-meghivok",
    name: "Amare Esküvői Meghívók",
    category: "stationery",
    city: "Budapest",
    address: "1137 Budapest, Szent István park 18.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Esküvői meghívók és papírkiegészítők, személyes budapesti ügyintézéssel.",
    blurb_en: "Wedding invites and paper goods with in-person Budapest consultation.",
    website: "https://www.amare.hu/",
    ...noContact,
    contact_email: "amare@amare.hu",
    contact_phone: "+36 30 289 5610",
    source: "curated",
    price_band: 3,
  },
  {
    id: "meghivoink",
    name: "Meghivoink.hu",
    category: "stationery",
    city: "Szeged",
    address: "6728 Szeged, Pihenő utca 47.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "1000+ féle esküvői meghívó, ültető- és menükártya kiegészítőkkel.",
    blurb_en: "1000+ invite designs with matching seating cards and menu cards.",
    website: "https://meghivoink.hu/",
    ...noContact,
    contact_email: "kapcsolat@meghivoink.hu",
    contact_phone: "+36 30 219 6940",
    source: "curated",
    price_band: 2,
  },
  {
    id: "webalbum-eskuvoi-meghivo",
    name: "Webalbum Stúdió",
    category: "stationery",
    city: "Budapest",
    address: "1075 Budapest",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "10+ év tapasztalat, 6000+ pár; online és személyes bemutatótermi rendelés.",
    blurb_en: "10+ years experience, 6000+ couples; online and in-showroom ordering.",
    website: "https://eskuvoi.meghivo.hu/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
  {
    id: "edmo-design",
    name: "Edmo Design",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Meghívótól az ültetőkártyáig minden nyomtatott elem grafikai összehangolása.",
    blurb_en: "Cohesive graphic design from invites to seating cards.",
    website: "https://edmo-design.hu/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "patria-nyomda",
    name: "Pátria Nyomda Zrt.",
    category: "stationery",
    city: "Budapest",
    address: "1117 Budapest, Hunyadi János út 7.",
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Ipari nyomdai háttér egyedi papír- és nyomdai projektekhez.",
    blurb_en: "Industrial-scale print house for bespoke paper and print projects.",
    website: "https://patria.hu/",
    ...noContact,
    contact_email: "info@patria.hu",
    contact_phone: "+36 1 463 0440",
    source: "curated",
    price_band: 4,
  },
  {
    id: "grafit-pencil-nyomda",
    name: "Grafit Pencil Nyomda",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Meghívónyomtatás esküvőre, vállalati és privát eseményekre.",
    blurb_en: "Invitation printing for weddings, corporate and private events.",
    website: "https://valtsnyomdat.hu/meghivo-nyomtatas/",
    ...noContact,
    source: "curated",
    price_band: 3,
  },
  {
    id: "papirfalva",
    name: "Papírfalva",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Egyedi tervezésű, személyre szabható papírtermékek és esküvői meghívók.",
    blurb_en: "Custom-designed paper goods and personalisable wedding invites.",
    website: "https://papirfalva.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "miss-lulli-decor",
    name: "MISS LULLI Decor",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Teljes körű dekoráció és arculat; papírkiegészítők egységes vizuális koncepcióval.",
    blurb_en: "Full decor and identity; paper goods with one cohesive visual concept.",
    website: "https://www.misslullidecor.hu/",
    ...noContact,
    contact_email: "misslullidecor@gmail.com",
    contact_phone: "+36 20 293 2656",
    source: "curated",
    price_band: 4,
  },
  {
    id: "copyguru",
    name: "COPYGURU",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Online nyomdai rendelési felület; gyors, standardizált kivitelezés.",
    blurb_en: "Online print ordering interface; fast, standardised production.",
    website: "https://webshop.copyguru.hu/",
    ...noContact,
    source: "curated",
    price_band: 2,
  },
  {
    id: "vinczemill",
    name: "Vinczemill",
    category: "stationery",
    city: "Budapest",
    address: null,
    capacity_min: null,
    capacity_max: null,
    blurb_hu: "Pecsétes, dombornyomott és prémium papírra épülő meghívók és kiegészítők.",
    blurb_en: "Wax-sealed, embossed and premium-paper invites and accessories.",
    website: "https://www.vinczemill.hu/meghivok/",
    ...noContact,
    source: "curated",
    price_band: 4,
  },
];

export const DIRECTORY: DirectorySupplierBase[] = RAW_DIRECTORY.map((s) => {
  const c = VENUE_COORDS[s.id];
  const withCoords = c ? { ...s, lat: c.lat, lng: c.lng } : s;
  // `vendor_account_id` defaults to null at the code layer; the
  // public-list handler in routes/suppliers.ts overlays the real value
  // from the `listings` table (where claimed entries live) before responding.
  // `hero_image_url` likewise overlays from the listings table once the
  // vendor uploads one — curated entries don't ship with images today.
  return { ...withCoords, submitter_type: null, vendor_account_id: null, hero_image_url: null };
});
