// Static curated suppliers directory. v1 is read-only — outbound contact only,
// no booking/messaging. Edit this file to add or remove entries until the v2
// marketplace lands and this becomes a `suppliers` DB table.

export type { DirectorySupplier, SupplierCategory } from "@shared/suppliers";
import type { DirectorySupplier } from "@shared/suppliers";

// Sample data — replace with real curated entries as the network grows.
export const DIRECTORY: DirectorySupplier[] = [
  {
    id: "barokk-villa",
    name: "Barokk Villa",
    category: "venue",
    city: "Budapest",
    blurb_hu: "Klasszikus villaesküvő a budai oldalon, kerttel és terasszal.",
    blurb_en: "Classic villa wedding venue on the Buda side with garden and terrace.",
    website: "https://example.com/barokk-villa",
    contact_email: "info@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "savory-events",
    name: "Savory Events",
    category: "catering",
    city: "Budapest",
    blurb_hu: "Évszakhoz illő menük helyi alapanyagokból, vegán opciókkal.",
    blurb_en: "Seasonal menus from local sourcing, with strong vegan options.",
    website: "https://example.com/savory-events",
    contact_email: "hello@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "luma-photo",
    name: "Luma Photo",
    category: "photo_video",
    city: "Pécs",
    blurb_hu: "Természetes fény, minimalista szerkesztés. Páros fotózás is.",
    blurb_en: "Natural light, minimalist editing. Engagement shoots available.",
    website: "https://example.com/luma-photo",
    contact_email: "studio@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "violet-floral",
    name: "Violet Floral",
    category: "decor_floral",
    city: "Szeged",
    blurb_hu: "Romantikus kompozíciók, friss vágott virág, fenntartható alapanyag.",
    blurb_en: "Romantic compositions, fresh-cut blooms, sustainable sourcing.",
    website: "https://example.com/violet-floral",
    contact_email: "violet@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "dj-eclectic",
    name: "DJ Eclectic",
    category: "music_dj",
    city: "Budapest",
    blurb_hu: "Magyar és nemzetközi tánczene; live MC opció.",
    blurb_en: "Hungarian + international dance sets; optional live MC.",
    website: "https://example.com/dj-eclectic",
    contact_email: "book@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "fondant-bakery",
    name: "Fondant Bakery",
    category: "cake_dessert",
    city: "Debrecen",
    blurb_hu: "Egyedi tervezésű torták, candy bar, gluténmentes választék.",
    blurb_en: "Custom-designed cakes, candy bar, gluten-free options.",
    website: "https://example.com/fondant-bakery",
    contact_email: "orders@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "danube-rooms",
    name: "Danube Rooms",
    category: "accommodation",
    city: "Budapest",
    blurb_hu: "Vendégszobák a helyszín mellett, csoportos kedvezménnyel.",
    blurb_en: "Guest rooms next to the venue with block-booking discounts.",
    website: "https://example.com/danube-rooms",
    contact_email: "stay@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "cellar-bar",
    name: "Cellar & Bar Co.",
    category: "bar_drinks",
    city: "Budapest",
    blurb_hu: "Mobil bárpult, koktélmester, magyar borválaszték.",
    blurb_en: "Mobile bar setup, mixologist, curated Hungarian wine list.",
    website: "https://example.com/cellar-bar",
    contact_email: "pours@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "glow-lighting",
    name: "Glow Lighting",
    category: "lighting",
    city: "Budapest",
    blurb_hu: "Hangulatvilágítás, dance floor fény, kültéri fűzérek.",
    blurb_en: "Mood lighting, dance-floor washes, outdoor festoon strings.",
    website: "https://example.com/glow-lighting",
    contact_email: "set@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "circus-act",
    name: "Circus Act",
    category: "entertainment",
    city: "Budapest",
    blurb_hu: "Élő műsorok: bűvész, vonós kvartett, fotófülke.",
    blurb_en: "Live acts: magician, string quartet, photo booth.",
    website: "https://example.com/circus-act",
    contact_email: "shows@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "atelier-attire",
    name: "Atelier Fehér",
    category: "attire",
    city: "Budapest",
    blurb_hu: "Mértékre szabott menyasszonyi és vőlegény-öltözékek.",
    blurb_en: "Made-to-measure bridal gowns and groom suits.",
    website: "https://example.com/atelier-fehér",
    contact_email: "fit@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "rouge-beauty",
    name: "Rouge Beauty",
    category: "hair_makeup",
    city: "Budapest",
    blurb_hu: "Mobil smink és haj a készülődés helyszínén.",
    blurb_en: "Mobile hair and makeup at your getting-ready location.",
    website: "https://example.com/rouge-beauty",
    contact_email: "look@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "press-stationery",
    name: "Press & Letter",
    category: "stationery",
    city: "Budapest",
    blurb_hu: "Letterpress meghívó, ülésrend kártya, helykártyák.",
    blurb_en: "Letterpress invites, seating cards, place cards.",
    website: "https://example.com/press-letter",
    contact_email: "print@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
  {
    id: "shuttle-co",
    name: "Shuttle Co.",
    category: "transport",
    city: "Budapest",
    blurb_hu: "Vendégbusz transzfer szállás és helyszín között.",
    blurb_en: "Guest shuttle transfer between hotel and venue.",
    website: "https://example.com/shuttle-co",
    contact_email: "ride@example.com",
    contact_phone: null,
    source: "curated",
    price_band: null,
  },
];
