// Single source of truth for the country picker used in onboarding, the
// profile-page couple-settings panel, and the create-additional-workspace
// dialog. Codes are ISO 3166-1 alpha-2 (always uppercase); names are the
// short reference forms used by the UN / ISO. HU names follow the
// Helyesírási kézikönyv / hivatalos nemzetközi gyakorlat.
//
// The list is exhaustive on purpose: Weddly is positioned as
// international-first, so a couple holding their wedding in any
// recognised territory should be able to pick it without falling back
// to "Other". When suppliers gain country-aware filtering in v2, this
// is the join key.
//
// Used by both the backend (validation) and the frontend (combobox).

export interface CountryEntry {
  /** ISO 3166-1 alpha-2 (uppercase). The canonical join key. */
  code: string;
  /** UN short reference form in English. */
  en: string;
  /** Hungarian reference form (rövid, hivatalos). */
  hu: string;
}

export const COUNTRIES: ReadonlyArray<CountryEntry> = [
  { code: "AD", en: "Andorra", hu: "Andorra" },
  { code: "AE", en: "United Arab Emirates", hu: "Egyesült Arab Emírségek" },
  { code: "AF", en: "Afghanistan", hu: "Afganisztán" },
  { code: "AG", en: "Antigua and Barbuda", hu: "Antigua és Barbuda" },
  { code: "AI", en: "Anguilla", hu: "Anguilla" },
  { code: "AL", en: "Albania", hu: "Albánia" },
  { code: "AM", en: "Armenia", hu: "Örményország" },
  { code: "AO", en: "Angola", hu: "Angola" },
  { code: "AQ", en: "Antarctica", hu: "Antarktisz" },
  { code: "AR", en: "Argentina", hu: "Argentína" },
  { code: "AS", en: "American Samoa", hu: "Amerikai Szamoa" },
  { code: "AT", en: "Austria", hu: "Ausztria" },
  { code: "AU", en: "Australia", hu: "Ausztrália" },
  { code: "AW", en: "Aruba", hu: "Aruba" },
  { code: "AX", en: "Åland Islands", hu: "Åland-szigetek" },
  { code: "AZ", en: "Azerbaijan", hu: "Azerbajdzsán" },
  { code: "BA", en: "Bosnia and Herzegovina", hu: "Bosznia-Hercegovina" },
  { code: "BB", en: "Barbados", hu: "Barbados" },
  { code: "BD", en: "Bangladesh", hu: "Banglades" },
  { code: "BE", en: "Belgium", hu: "Belgium" },
  { code: "BF", en: "Burkina Faso", hu: "Burkina Faso" },
  { code: "BG", en: "Bulgaria", hu: "Bulgária" },
  { code: "BH", en: "Bahrain", hu: "Bahrein" },
  { code: "BI", en: "Burundi", hu: "Burundi" },
  { code: "BJ", en: "Benin", hu: "Benin" },
  { code: "BL", en: "Saint Barthélemy", hu: "Saint-Barthélemy" },
  { code: "BM", en: "Bermuda", hu: "Bermuda" },
  { code: "BN", en: "Brunei Darussalam", hu: "Brunei" },
  { code: "BO", en: "Bolivia", hu: "Bolívia" },
  { code: "BQ", en: "Bonaire, Sint Eustatius and Saba", hu: "Bonaire, Sint Eustatius és Saba" },
  { code: "BR", en: "Brazil", hu: "Brazília" },
  { code: "BS", en: "Bahamas", hu: "Bahama-szigetek" },
  { code: "BT", en: "Bhutan", hu: "Bhután" },
  { code: "BV", en: "Bouvet Island", hu: "Bouvet-sziget" },
  { code: "BW", en: "Botswana", hu: "Botswana" },
  { code: "BY", en: "Belarus", hu: "Belarusz" },
  { code: "BZ", en: "Belize", hu: "Belize" },
  { code: "CA", en: "Canada", hu: "Kanada" },
  { code: "CC", en: "Cocos (Keeling) Islands", hu: "Kókusz-szigetek" },
  { code: "CD", en: "Congo (Democratic Republic)", hu: "Kongói Demokratikus Köztársaság" },
  { code: "CF", en: "Central African Republic", hu: "Közép-afrikai Köztársaság" },
  { code: "CG", en: "Congo", hu: "Kongói Köztársaság" },
  { code: "CH", en: "Switzerland", hu: "Svájc" },
  { code: "CI", en: "Côte d'Ivoire", hu: "Elefántcsontpart" },
  { code: "CK", en: "Cook Islands", hu: "Cook-szigetek" },
  { code: "CL", en: "Chile", hu: "Chile" },
  { code: "CM", en: "Cameroon", hu: "Kamerun" },
  { code: "CN", en: "China", hu: "Kína" },
  { code: "CO", en: "Colombia", hu: "Kolumbia" },
  { code: "CR", en: "Costa Rica", hu: "Costa Rica" },
  { code: "CU", en: "Cuba", hu: "Kuba" },
  { code: "CV", en: "Cabo Verde", hu: "Zöld-foki Köztársaság" },
  { code: "CW", en: "Curaçao", hu: "Curaçao" },
  { code: "CX", en: "Christmas Island", hu: "Karácsony-sziget" },
  { code: "CY", en: "Cyprus", hu: "Ciprus" },
  { code: "CZ", en: "Czechia", hu: "Csehország" },
  { code: "DE", en: "Germany", hu: "Németország" },
  { code: "DJ", en: "Djibouti", hu: "Dzsibuti" },
  { code: "DK", en: "Denmark", hu: "Dánia" },
  { code: "DM", en: "Dominica", hu: "Dominika" },
  { code: "DO", en: "Dominican Republic", hu: "Dominikai Köztársaság" },
  { code: "DZ", en: "Algeria", hu: "Algéria" },
  { code: "EC", en: "Ecuador", hu: "Ecuador" },
  { code: "EE", en: "Estonia", hu: "Észtország" },
  { code: "EG", en: "Egypt", hu: "Egyiptom" },
  { code: "EH", en: "Western Sahara", hu: "Nyugat-Szahara" },
  { code: "ER", en: "Eritrea", hu: "Eritrea" },
  { code: "ES", en: "Spain", hu: "Spanyolország" },
  { code: "ET", en: "Ethiopia", hu: "Etiópia" },
  { code: "FI", en: "Finland", hu: "Finnország" },
  { code: "FJ", en: "Fiji", hu: "Fidzsi-szigetek" },
  { code: "FK", en: "Falkland Islands", hu: "Falkland-szigetek" },
  { code: "FM", en: "Micronesia", hu: "Mikronézia" },
  { code: "FO", en: "Faroe Islands", hu: "Feröer-szigetek" },
  { code: "FR", en: "France", hu: "Franciaország" },
  { code: "GA", en: "Gabon", hu: "Gabon" },
  { code: "GB", en: "United Kingdom", hu: "Egyesült Királyság" },
  { code: "GD", en: "Grenada", hu: "Grenada" },
  { code: "GE", en: "Georgia", hu: "Grúzia" },
  { code: "GF", en: "French Guiana", hu: "Francia Guyana" },
  { code: "GG", en: "Guernsey", hu: "Guernsey" },
  { code: "GH", en: "Ghana", hu: "Ghána" },
  { code: "GI", en: "Gibraltar", hu: "Gibraltár" },
  { code: "GL", en: "Greenland", hu: "Grönland" },
  { code: "GM", en: "Gambia", hu: "Gambia" },
  { code: "GN", en: "Guinea", hu: "Guinea" },
  { code: "GP", en: "Guadeloupe", hu: "Guadeloupe" },
  { code: "GQ", en: "Equatorial Guinea", hu: "Egyenlítői-Guinea" },
  { code: "GR", en: "Greece", hu: "Görögország" },
  {
    code: "GS",
    en: "South Georgia and the South Sandwich Islands",
    hu: "Déli-Georgia és Déli-Sandwich-szigetek",
  },
  { code: "GT", en: "Guatemala", hu: "Guatemala" },
  { code: "GU", en: "Guam", hu: "Guam" },
  { code: "GW", en: "Guinea-Bissau", hu: "Bissau-Guinea" },
  { code: "GY", en: "Guyana", hu: "Guyana" },
  { code: "HK", en: "Hong Kong", hu: "Hongkong" },
  { code: "HM", en: "Heard Island and McDonald Islands", hu: "Heard-sziget és McDonald-szigetek" },
  { code: "HN", en: "Honduras", hu: "Honduras" },
  { code: "HR", en: "Croatia", hu: "Horvátország" },
  { code: "HT", en: "Haiti", hu: "Haiti" },
  { code: "HU", en: "Hungary", hu: "Magyarország" },
  { code: "ID", en: "Indonesia", hu: "Indonézia" },
  { code: "IE", en: "Ireland", hu: "Írország" },
  { code: "IL", en: "Israel", hu: "Izrael" },
  { code: "IM", en: "Isle of Man", hu: "Man-sziget" },
  { code: "IN", en: "India", hu: "India" },
  { code: "IO", en: "British Indian Ocean Territory", hu: "Brit Indiai-óceáni Terület" },
  { code: "IQ", en: "Iraq", hu: "Irak" },
  { code: "IR", en: "Iran", hu: "Irán" },
  { code: "IS", en: "Iceland", hu: "Izland" },
  { code: "IT", en: "Italy", hu: "Olaszország" },
  { code: "JE", en: "Jersey", hu: "Jersey" },
  { code: "JM", en: "Jamaica", hu: "Jamaica" },
  { code: "JO", en: "Jordan", hu: "Jordánia" },
  { code: "JP", en: "Japan", hu: "Japán" },
  { code: "KE", en: "Kenya", hu: "Kenya" },
  { code: "KG", en: "Kyrgyzstan", hu: "Kirgizisztán" },
  { code: "KH", en: "Cambodia", hu: "Kambodzsa" },
  { code: "KI", en: "Kiribati", hu: "Kiribati" },
  { code: "KM", en: "Comoros", hu: "Comore-szigetek" },
  { code: "KN", en: "Saint Kitts and Nevis", hu: "Saint Kitts és Nevis" },
  { code: "KP", en: "North Korea", hu: "Észak-Korea" },
  { code: "KR", en: "South Korea", hu: "Dél-Korea" },
  { code: "KW", en: "Kuwait", hu: "Kuvait" },
  { code: "KY", en: "Cayman Islands", hu: "Kajmán-szigetek" },
  { code: "KZ", en: "Kazakhstan", hu: "Kazahsztán" },
  { code: "LA", en: "Laos", hu: "Laosz" },
  { code: "LB", en: "Lebanon", hu: "Libanon" },
  { code: "LC", en: "Saint Lucia", hu: "Saint Lucia" },
  { code: "LI", en: "Liechtenstein", hu: "Liechtenstein" },
  { code: "LK", en: "Sri Lanka", hu: "Srí Lanka" },
  { code: "LR", en: "Liberia", hu: "Libéria" },
  { code: "LS", en: "Lesotho", hu: "Lesotho" },
  { code: "LT", en: "Lithuania", hu: "Litvánia" },
  { code: "LU", en: "Luxembourg", hu: "Luxemburg" },
  { code: "LV", en: "Latvia", hu: "Lettország" },
  { code: "LY", en: "Libya", hu: "Líbia" },
  { code: "MA", en: "Morocco", hu: "Marokkó" },
  { code: "MC", en: "Monaco", hu: "Monaco" },
  { code: "MD", en: "Moldova", hu: "Moldova" },
  { code: "ME", en: "Montenegro", hu: "Montenegró" },
  { code: "MF", en: "Saint Martin (French part)", hu: "Saint-Martin (francia rész)" },
  { code: "MG", en: "Madagascar", hu: "Madagaszkár" },
  { code: "MH", en: "Marshall Islands", hu: "Marshall-szigetek" },
  { code: "MK", en: "North Macedonia", hu: "Észak-Macedónia" },
  { code: "ML", en: "Mali", hu: "Mali" },
  { code: "MM", en: "Myanmar", hu: "Mianmar" },
  { code: "MN", en: "Mongolia", hu: "Mongólia" },
  { code: "MO", en: "Macao", hu: "Makaó" },
  { code: "MP", en: "Northern Mariana Islands", hu: "Északi-Mariana-szigetek" },
  { code: "MQ", en: "Martinique", hu: "Martinique" },
  { code: "MR", en: "Mauritania", hu: "Mauritánia" },
  { code: "MS", en: "Montserrat", hu: "Montserrat" },
  { code: "MT", en: "Malta", hu: "Málta" },
  { code: "MU", en: "Mauritius", hu: "Mauritius" },
  { code: "MV", en: "Maldives", hu: "Maldív-szigetek" },
  { code: "MW", en: "Malawi", hu: "Malawi" },
  { code: "MX", en: "Mexico", hu: "Mexikó" },
  { code: "MY", en: "Malaysia", hu: "Malajzia" },
  { code: "MZ", en: "Mozambique", hu: "Mozambik" },
  { code: "NA", en: "Namibia", hu: "Namíbia" },
  { code: "NC", en: "New Caledonia", hu: "Új-Kaledónia" },
  { code: "NE", en: "Niger", hu: "Niger" },
  { code: "NF", en: "Norfolk Island", hu: "Norfolk-sziget" },
  { code: "NG", en: "Nigeria", hu: "Nigéria" },
  { code: "NI", en: "Nicaragua", hu: "Nicaragua" },
  { code: "NL", en: "Netherlands", hu: "Hollandia" },
  { code: "NO", en: "Norway", hu: "Norvégia" },
  { code: "NP", en: "Nepal", hu: "Nepál" },
  { code: "NR", en: "Nauru", hu: "Nauru" },
  { code: "NU", en: "Niue", hu: "Niue" },
  { code: "NZ", en: "New Zealand", hu: "Új-Zéland" },
  { code: "OM", en: "Oman", hu: "Omán" },
  { code: "PA", en: "Panama", hu: "Panama" },
  { code: "PE", en: "Peru", hu: "Peru" },
  { code: "PF", en: "French Polynesia", hu: "Francia Polinézia" },
  { code: "PG", en: "Papua New Guinea", hu: "Pápua Új-Guinea" },
  { code: "PH", en: "Philippines", hu: "Fülöp-szigetek" },
  { code: "PK", en: "Pakistan", hu: "Pakisztán" },
  { code: "PL", en: "Poland", hu: "Lengyelország" },
  { code: "PM", en: "Saint Pierre and Miquelon", hu: "Saint-Pierre és Miquelon" },
  { code: "PN", en: "Pitcairn", hu: "Pitcairn-szigetek" },
  { code: "PR", en: "Puerto Rico", hu: "Puerto Rico" },
  { code: "PS", en: "Palestine", hu: "Palesztina" },
  { code: "PT", en: "Portugal", hu: "Portugália" },
  { code: "PW", en: "Palau", hu: "Palau" },
  { code: "PY", en: "Paraguay", hu: "Paraguay" },
  { code: "QA", en: "Qatar", hu: "Katar" },
  { code: "RE", en: "Réunion", hu: "Réunion" },
  { code: "RO", en: "Romania", hu: "Románia" },
  { code: "RS", en: "Serbia", hu: "Szerbia" },
  { code: "RU", en: "Russia", hu: "Oroszország" },
  { code: "RW", en: "Rwanda", hu: "Ruanda" },
  { code: "SA", en: "Saudi Arabia", hu: "Szaúd-Arábia" },
  { code: "SB", en: "Solomon Islands", hu: "Salamon-szigetek" },
  { code: "SC", en: "Seychelles", hu: "Seychelle-szigetek" },
  { code: "SD", en: "Sudan", hu: "Szudán" },
  { code: "SE", en: "Sweden", hu: "Svédország" },
  { code: "SG", en: "Singapore", hu: "Szingapúr" },
  {
    code: "SH",
    en: "Saint Helena, Ascension and Tristan da Cunha",
    hu: "Szent Ilona, Ascension és Tristan da Cunha",
  },
  { code: "SI", en: "Slovenia", hu: "Szlovénia" },
  { code: "SJ", en: "Svalbard and Jan Mayen", hu: "Svalbard és Jan Mayen" },
  { code: "SK", en: "Slovakia", hu: "Szlovákia" },
  { code: "SL", en: "Sierra Leone", hu: "Sierra Leone" },
  { code: "SM", en: "San Marino", hu: "San Marino" },
  { code: "SN", en: "Senegal", hu: "Szenegál" },
  { code: "SO", en: "Somalia", hu: "Szomália" },
  { code: "SR", en: "Suriname", hu: "Suriname" },
  { code: "SS", en: "South Sudan", hu: "Dél-Szudán" },
  { code: "ST", en: "Sao Tome and Principe", hu: "São Tomé és Príncipe" },
  { code: "SV", en: "El Salvador", hu: "Salvador" },
  { code: "SX", en: "Sint Maarten (Dutch part)", hu: "Sint Maarten (holland rész)" },
  { code: "SY", en: "Syria", hu: "Szíria" },
  { code: "SZ", en: "Eswatini", hu: "Eswatini" },
  { code: "TC", en: "Turks and Caicos Islands", hu: "Turks- és Caicos-szigetek" },
  { code: "TD", en: "Chad", hu: "Csád" },
  { code: "TF", en: "French Southern Territories", hu: "Francia déli területek" },
  { code: "TG", en: "Togo", hu: "Togo" },
  { code: "TH", en: "Thailand", hu: "Thaiföld" },
  { code: "TJ", en: "Tajikistan", hu: "Tádzsikisztán" },
  { code: "TK", en: "Tokelau", hu: "Tokelau" },
  { code: "TL", en: "Timor-Leste", hu: "Kelet-Timor" },
  { code: "TM", en: "Turkmenistan", hu: "Türkmenisztán" },
  { code: "TN", en: "Tunisia", hu: "Tunézia" },
  { code: "TO", en: "Tonga", hu: "Tonga" },
  { code: "TR", en: "Türkiye", hu: "Törökország" },
  { code: "TT", en: "Trinidad and Tobago", hu: "Trinidad és Tobago" },
  { code: "TV", en: "Tuvalu", hu: "Tuvalu" },
  { code: "TW", en: "Taiwan", hu: "Tajvan" },
  { code: "TZ", en: "Tanzania", hu: "Tanzánia" },
  { code: "UA", en: "Ukraine", hu: "Ukrajna" },
  { code: "UG", en: "Uganda", hu: "Uganda" },
  {
    code: "UM",
    en: "United States Minor Outlying Islands",
    hu: "Amerikai Egyesült Államok lakatlan külbirtokai",
  },
  { code: "US", en: "United States", hu: "Amerikai Egyesült Államok" },
  { code: "UY", en: "Uruguay", hu: "Uruguay" },
  { code: "UZ", en: "Uzbekistan", hu: "Üzbegisztán" },
  { code: "VA", en: "Holy See (Vatican City)", hu: "Vatikán" },
  {
    code: "VC",
    en: "Saint Vincent and the Grenadines",
    hu: "Saint Vincent és a Grenadine-szigetek",
  },
  { code: "VE", en: "Venezuela", hu: "Venezuela" },
  { code: "VG", en: "British Virgin Islands", hu: "Brit Virgin-szigetek" },
  { code: "VI", en: "U.S. Virgin Islands", hu: "Amerikai Virgin-szigetek" },
  { code: "VN", en: "Viet Nam", hu: "Vietnám" },
  { code: "VU", en: "Vanuatu", hu: "Vanuatu" },
  { code: "WF", en: "Wallis and Futuna", hu: "Wallis és Futuna" },
  { code: "WS", en: "Samoa", hu: "Szamoa" },
  { code: "YE", en: "Yemen", hu: "Jemen" },
  { code: "YT", en: "Mayotte", hu: "Mayotte" },
  { code: "ZA", en: "South Africa", hu: "Dél-afrikai Köztársaság" },
  { code: "ZM", en: "Zambia", hu: "Zambia" },
  { code: "ZW", en: "Zimbabwe", hu: "Zimbabwe" },
];

/** Fast membership lookup for backend validation. */
export const COUNTRY_CODES: ReadonlySet<string> = new Set(COUNTRIES.map((c) => c.code));

/** Locale-aware name for a known code. Returns the raw code as a safe
 *  fallback if the code isn't in the list (shouldn't happen after backend
 *  validation, but the UI calls this for legacy rows too). */
export function countryName(code: string, locale: "hu" | "en"): string {
  const entry = COUNTRIES.find((c) => c.code === code.toUpperCase());
  if (!entry) return code;
  return locale === "hu" ? entry.hu : entry.en;
}
