// Canonical wedding checklist content shared by the interactive Planning view
// and the server-side PDF renderer. Completion does NOT live here: each item is
// materialised as an ordinary planning_items task carrying `templateItemId`, so
// the task's existing `done` flag remains the only completion truth.

import type { ConditionTag } from "./planning_prompts";
import type { UiLocale } from "./locales";
import { timelineDatesFor } from "./planning_timeline";

export type ChecklistSectionId =
  | "m12_18"
  | "m9_12"
  | "m6_9"
  | "m4_6"
  | "m2_3"
  | "m1"
  | "w2"
  | "w1"
  | "day_before"
  | "wedding_day"
  | "after";

interface ChecklistItemDefinition {
  id: string;
  condition?: ConditionTag;
}

interface ChecklistSectionDefinition {
  id: ChecklistSectionId;
  /** Due date lead measured before the wedding. Negative values fall after it. */
  leadDays: number;
  items: readonly ChecklistItemDefinition[];
}

const item = (id: string, condition?: ConditionTag): ChecklistItemDefinition => ({ id, condition });

const DEFINITIONS: readonly ChecklistSectionDefinition[] = [
  {
    id: "m12_18",
    leadDays: 450,
    items: [
      item("set-budget"),
      item("financial-contributions"),
      item("draft-guest-list"),
      item("choose-date"),
      item("choose-style"),
      item("research-venues"),
      item("book-venue"),
      item("hire-planner"),
      item("book-photographer", "pro_photo"),
      item("book-videographer"),
      item("research-caterers"),
      item("wedding-insurance"),
    ],
  },
  {
    id: "m9_12",
    leadDays: 315,
    items: [
      item("choose-outfits"),
      item("partner-attire"),
      item("choose-colors"),
      item("book-caterer"),
      item("book-florist"),
      item("book-music"),
      item("book-hair-makeup"),
      item("book-officiant"),
      item("reserve-accommodation", "accommodation_needed"),
      item("arrange-transport"),
      item("choose-wedding-party"),
      item("create-website"),
      item("begin-honeymoon"),
    ],
  },
  {
    id: "m6_9",
    leadDays: 225,
    items: [
      item("order-party-outfits"),
      item("arrange-formalwear"),
      item("finalize-guest-list"),
      item("send-save-dates", "printed_stationery"),
      item("choose-ceremony-music"),
      item("choose-readings"),
      item("choose-cake"),
      item("plan-decor"),
      item("book-lighting"),
      item("plan-rehearsal-dinner"),
      item("review-travel-docs"),
    ],
  },
  {
    id: "m4_6",
    leadDays: 150,
    items: [
      item("order-invitations", "printed_stationery"),
      item("buy-rings"),
      item("schedule-alterations"),
      item("choose-shoes"),
      item("choose-accessories"),
      item("finalize-flowers"),
      item("plan-parties"),
      item("choose-favors", "guest_keepsakes"),
      item("confirm-ceremony"),
      item("choose-menu"),
      item("finalize-cake"),
      item("draft-day-timeline"),
    ],
  },
  {
    id: "m2_3",
    leadDays: 75,
    items: [
      item("send-invitations", "printed_stationery"),
      item("track-rsvps"),
      item("draft-seating"),
      item("meet-music"),
      item("must-play"),
      item("do-not-play"),
      item("finalize-outfit"),
      item("write-vows"),
      item("prepare-marriage-docs"),
      item("confirm-honeymoon"),
      item("finalize-guest-transport", "accommodation_needed"),
      item("plan-welcome-bags"),
    ],
  },
  {
    id: "m1",
    leadDays: 30,
    items: [
      item("follow-up-rsvps"),
      item("finalize-count"),
      item("give-count-venue"),
      item("give-count-caterer"),
      item("finalize-seating"),
      item("confirm-vendors"),
      item("confirm-music"),
      item("confirm-transport"),
      item("prepare-signage", "printed_stationery"),
      item("prepare-place-cards", "printed_stationery"),
      item("collect-rings"),
      item("prepare-payments"),
    ],
  },
  {
    id: "w2",
    leadDays: 14,
    items: [
      item("confirm-timeline"),
      item("share-timeline"),
      item("confirm-diets"),
      item("prepare-emergency-kit"),
      item("assign-rings"),
      item("assign-gifts"),
      item("assign-vendor-contact"),
      item("practice-dance"),
      item("finalize-speeches"),
      item("begin-packing"),
    ],
  },
  {
    id: "w1",
    leadDays: 7,
    items: [
      item("pick-up-outfits"),
      item("check-accessories"),
      item("pack-overnight"),
      item("confirm-arrivals"),
      item("ceremony-rehearsal"),
      item("payment-envelopes"),
      item("prepare-documents"),
      item("rest-hydrate"),
    ],
  },
  {
    id: "day_before",
    leadDays: 1,
    items: [
      item("deliver-decor"),
      item("check-rings"),
      item("charge-devices"),
      item("prepare-outfits"),
      item("pack-supplies"),
      item("eat-hydrate"),
      item("sleep"),
    ],
  },
  {
    id: "wedding_day",
    leadDays: 0,
    items: [
      item("eat-breakfast"),
      item("getting-ready-time"),
      item("secure-rings-docs"),
      item("hand-off-logistics"),
      item("private-moment"),
      item("group-photos"),
      item("eat-meal"),
      item("enjoy-moment"),
    ],
  },
  {
    id: "after",
    leadDays: -7,
    items: [
      item("collect-items"),
      item("return-rentals"),
      item("pay-balances"),
      item("preserve-outfits"),
      item("organize-gifts"),
      item("send-thanks"),
      item("share-photos"),
      item("review-vendors"),
      item("choose-album"),
      item("legal-name-changes"),
      item("finalize-honeymoon-tasks"),
    ],
  },
] as const;

const SECTION_TITLES: Record<UiLocale, readonly string[]> = {
  en: [
    "12–18 months before",
    "9–12 months before",
    "6–9 months before",
    "4–6 months before",
    "2–3 months before",
    "1 month before",
    "2 weeks before",
    "1 week before",
    "Day before",
    "Wedding day",
    "After the wedding",
  ],
  hu: [
    "12–18 hónappal előtte",
    "9–12 hónappal előtte",
    "6–9 hónappal előtte",
    "4–6 hónappal előtte",
    "2–3 hónappal előtte",
    "1 hónappal előtte",
    "2 héttel előtte",
    "1 héttel előtte",
    "Előző nap",
    "Az esküvő napja",
    "Az esküvő után",
  ],
  es: [
    "12–18 meses antes",
    "9–12 meses antes",
    "6–9 meses antes",
    "4–6 meses antes",
    "2–3 meses antes",
    "1 mes antes",
    "2 semanas antes",
    "1 semana antes",
    "El día anterior",
    "El día de la boda",
    "Después de la boda",
  ],
  hr: [
    "12–18 mjeseci prije",
    "9–12 mjeseci prije",
    "6–9 mjeseci prije",
    "4–6 mjeseci prije",
    "2–3 mjeseca prije",
    "1 mjesec prije",
    "2 tjedna prije",
    "1 tjedan prije",
    "Dan prije",
    "Dan vjenčanja",
    "Nakon vjenčanja",
  ],
  de: [
    "12–18 Monate vorher",
    "9–12 Monate vorher",
    "6–9 Monate vorher",
    "4–6 Monate vorher",
    "2–3 Monate vorher",
    "1 Monat vorher",
    "2 Wochen vorher",
    "1 Woche vorher",
    "Am Vortag",
    "Am Hochzeitstag",
    "Nach der Hochzeit",
  ],
};

// Item copy follows DEFINITIONS' flattened order. Keeping content inline is the
// established Weddly catalogue pattern (planning_task_packs, supplier data): it
// stays usable by both frontend and backend without importing a UI locale tree.
const ITEM_TITLES: Record<UiLocale, readonly string[]> = {
  en: [
    "Set your wedding budget",
    "Decide who contributes financially",
    "Draft your guest list",
    "Choose your wedding date",
    "Choose your wedding style",
    "Research venues",
    "Book your venue",
    "Hire a wedding planner if needed",
    "Book your photographer",
    "Book your videographer",
    "Research caterers",
    "Consider wedding insurance",
    "Choose your wedding outfits",
    "Choose your partner's attire direction",
    "Choose your wedding colors",
    "Book your caterer",
    "Book your florist",
    "Book your DJ or band",
    "Book hair and makeup",
    "Book your officiant",
    "Reserve guest accommodation",
    "Arrange transportation",
    "Choose your wedding party",
    "Create your wedding website",
    "Begin honeymoon planning",
    "Order wedding party outfits",
    "Arrange suits or formalwear",
    "Finalize your guest list",
    "Send save-the-dates",
    "Choose ceremony music",
    "Choose ceremony readings",
    "Choose your cake supplier",
    "Plan decor and rentals",
    "Book special lighting or furniture",
    "Plan the rehearsal dinner",
    "Review honeymoon travel requirements",
    "Order invitations",
    "Buy wedding rings",
    "Schedule outfit alterations",
    "Choose wedding shoes",
    "Choose accessories",
    "Finalize floral direction",
    "Plan bachelor or bachelorette events",
    "Choose guest favors if desired",
    "Confirm ceremony structure",
    "Choose the menu",
    "Finalize cake design",
    "Draft the wedding-day timeline",
    "Send invitations",
    "Track RSVPs",
    "Draft the seating plan",
    "Meet your DJ or band",
    "Create a must-play list",
    "Create a do-not-play list",
    "Finalize wedding outfits",
    "Write vows if applicable",
    "Prepare marriage documents",
    "Confirm honeymoon reservations",
    "Finalize guest transportation",
    "Plan welcome bags if needed",
    "Follow up missing RSVPs",
    "Finalize the guest count",
    "Give the final count to the venue",
    "Give the final count to the caterer",
    "Finalize the seating chart",
    "Confirm all vendors",
    "Confirm the music",
    "Confirm transportation",
    "Prepare wedding signage",
    "Prepare place cards",
    "Collect the wedding rings",
    "Prepare remaining payments",
    "Confirm the final timeline",
    "Share the timeline with vendors",
    "Confirm dietary requirements",
    "Prepare an emergency kit",
    "Choose who is responsible for the rings",
    "Assign someone to collect gifts and cards",
    "Assign a vendor contact person",
    "Practice the first dance",
    "Finalize speeches",
    "Begin honeymoon packing",
    "Pick up wedding outfits",
    "Check all accessories",
    "Pack an overnight bag",
    "Confirm vendor arrival times",
    "Attend the ceremony rehearsal",
    "Prepare vendor payment envelopes",
    "Prepare required documents",
    "Rest and hydrate",
    "Deliver decor to the venue if required",
    "Check the rings",
    "Charge phones and power banks",
    "Prepare the outfits",
    "Pack emergency supplies",
    "Eat and hydrate properly",
    "Get enough sleep",
    "Eat breakfast and drink water",
    "Allow enough getting-ready time",
    "Keep rings and documents safe",
    "Hand logistics to a trusted person",
    "Take a private moment together",
    "Take important group photos",
    "Eat your wedding meal",
    "Enjoy the party and take in the moment",
    "Collect personal items",
    "Return rentals",
    "Pay remaining vendor balances",
    "Clean or preserve wedding outfits",
    "Organize gifts",
    "Send thank-you messages",
    "Share photos",
    "Review your vendors",
    "Choose wedding album photos",
    "Complete legal name or document changes",
    "Finalize honeymoon tasks",
  ],
  hu: [
    "Határozzátok meg az esküvői keretet",
    "Döntsétek el, ki mivel járul hozzá",
    "Készítsétek el az első vendéglistát",
    "Válasszátok ki az esküvő dátumát",
    "Határozzátok meg az esküvő stílusát",
    "Nézzetek utána a helyszíneknek",
    "Foglaljátok le a helyszínt",
    "Fogadjatok esküvőszervezőt, ha szükséges",
    "Foglaljátok le a fotóst",
    "Foglaljátok le a videóst",
    "Nézzetek utána a cateringnek",
    "Gondoljátok át az esküvői biztosítást",
    "Válasszátok ki az esküvői ruhákat",
    "Határozzátok meg a partner öltözékének irányát",
    "Válasszátok ki az esküvő színeit",
    "Foglaljátok le a cateringet",
    "Foglaljátok le a virágkötőt",
    "Foglaljátok le a DJ-t vagy zenekart",
    "Foglaljátok le a hajat és sminket",
    "Egyeztessetek a szertartásvezetővel",
    "Foglaljatok vendégszállást",
    "Szervezzétek meg a közlekedést",
    "Válasszátok ki az esküvői csapatot",
    "Készítsétek el az esküvői weboldalt",
    "Kezdjétek el a nászút tervezését",
    "Rendeljétek meg a kísérők ruháit",
    "Intézzétek az öltönyöket vagy alkalmi ruhákat",
    "Véglegesítsétek a vendéglistát",
    "Küldjétek ki a dátumértesítőket",
    "Válasszátok ki a szertartás zenéit",
    "Válasszátok ki a szertartás szövegeit",
    "Válasszatok tortakészítőt",
    "Tervezzétek meg a dekort és bérléseket",
    "Foglaljatok különleges világítást vagy bútorokat",
    "Tervezzétek meg a próba vacsorát",
    "Ellenőrizzétek a nászút utazási feltételeit",
    "Rendeljétek meg a meghívókat",
    "Vegyétek meg a karikagyűrűket",
    "Egyeztessétek a ruhapróbákat",
    "Válasszátok ki az esküvői cipőket",
    "Válasszátok ki a kiegészítőket",
    "Véglegesítsétek a virágdekorációt",
    "Tervezzétek meg a legény- vagy leánybúcsút",
    "Válasszatok köszönőajándékot, ha szeretnétek",
    "Véglegesítsétek a szertartás menetét",
    "Válasszátok ki a menüt",
    "Véglegesítsétek a torta tervét",
    "Készítsétek el az esküvő napjának első időrendjét",
    "Küldjétek ki a meghívókat",
    "Kövessétek a visszajelzéseket",
    "Készítsétek el az ültetési terv első változatát",
    "Egyeztessetek a DJ-vel vagy zenekarral",
    "Készítsetek kötelező dalok listáját",
    "Készítsetek tiltólistát a dalokhoz",
    "Véglegesítsétek az esküvői ruhákat",
    "Írjátok meg a fogadalmakat, ha lesznek",
    "Készítsétek elő a házassági iratokat",
    "Erősítsétek meg a nászút foglalásait",
    "Véglegesítsétek a vendégek szállítását",
    "Tervezzetek üdvözlőcsomagot, ha szükséges",
    "Kérdezzetek rá a hiányzó visszajelzésekre",
    "Véglegesítsétek a létszámot",
    "Adjátok le a végleges létszámot a helyszínnek",
    "Adjátok le a végleges létszámot a cateringnek",
    "Véglegesítsétek az ültetési rendet",
    "Erősítsetek meg minden szolgáltatót",
    "Erősítsétek meg a zenét",
    "Erősítsétek meg a szállítást",
    "Készítsétek el az esküvői táblákat",
    "Készítsétek el az ültetőkártyákat",
    "Vegyétek át a karikagyűrűket",
    "Készítsétek elő a hátralévő kifizetéseket",
    "Véglegesítsétek az időrendet",
    "Osszátok meg az időrendet a szolgáltatókkal",
    "Erősítsétek meg az étkezési igényeket",
    "Készítsetek vészhelyzeti csomagot",
    "Jelöljétek ki a gyűrűk felelősét",
    "Jelöljetek ki valakit az ajándékok és lapok összegyűjtésére",
    "Jelöljétek ki a szolgáltatói kapcsolattartót",
    "Gyakoroljátok az első táncot",
    "Véglegesítsétek a beszédeket",
    "Kezdjétek el a nászútra pakolást",
    "Vegyétek át az esküvői ruhákat",
    "Ellenőrizzetek minden kiegészítőt",
    "Pakoljátok be az éjszakai táskát",
    "Erősítsétek meg a szolgáltatók érkezését",
    "Vegyetek részt a szertartáspróbán",
    "Készítsétek elő a szolgáltatói fizetési borítékokat",
    "Készítsétek elő a szükséges iratokat",
    "Pihenjetek és hidratáljatok",
    "Vigyétek ki a dekort a helyszínre, ha szükséges",
    "Ellenőrizzétek a gyűrűket",
    "Töltsétek fel a telefonokat és külső akkukat",
    "Készítsétek elő a ruhákat",
    "Pakoljátok be a vészhelyzeti kellékeket",
    "Egyetek és igyatok eleget",
    "Aludjatok eleget",
    "Reggelizzetek és igyatok vizet",
    "Hagyjatok elég időt a készülődésre",
    "Tartsátok biztonságban a gyűrűket és iratokat",
    "Adjátok át a logisztikát egy megbízható embernek",
    "Legyen egy nyugodt pillanatotok kettesben",
    "Készítsétek el a fontos csoportképeket",
    "Egyétek meg az esküvői vacsorát",
    "Élvezzétek a bulit és a pillanatot",
    "Gyűjtsétek össze a személyes holmikat",
    "Adjátok vissza a bérelt tárgyakat",
    "Fizessétek ki a fennmaradó szolgáltatói díjakat",
    "Tisztíttassátok vagy őrizzétek meg az esküvői ruhákat",
    "Rendezzétek az ajándékokat",
    "Küldjetek köszönőüzeneteket",
    "Osszátok meg a fotókat",
    "Értékeljétek a szolgáltatókat",
    "Válasszátok ki az album képeit",
    "Intézzétek el a név- vagy okmányváltozásokat",
    "Véglegesítsétek a nászút teendőit",
  ],
  es: [
    "Definid el presupuesto de la boda",
    "Decidid quién contribuye económicamente",
    "Preparad la primera lista de invitados",
    "Elegid la fecha de la boda",
    "Elegid el estilo de la boda",
    "Buscad lugares para la celebración",
    "Reservad el lugar",
    "Contratad wedding planner si hace falta",
    "Reservad al fotógrafo",
    "Reservad al videógrafo",
    "Buscad servicios de catering",
    "Valorad un seguro de boda",
    "Elegid los trajes de boda",
    "Definid el estilo del traje de la pareja",
    "Elegid los colores de la boda",
    "Reservad el catering",
    "Reservad la floristería",
    "Reservad DJ o banda",
    "Reservad peluquería y maquillaje",
    "Reservad al oficiante",
    "Reservad alojamiento para invitados",
    "Organizad el transporte",
    "Elegid el cortejo nupcial",
    "Cread la web de la boda",
    "Empezad a planear la luna de miel",
    "Pedid los trajes del cortejo",
    "Organizad los trajes formales",
    "Cerrad la lista de invitados",
    "Enviad los save the date",
    "Elegid la música de la ceremonia",
    "Elegid las lecturas",
    "Elegid la pastelería",
    "Planificad decoración y alquileres",
    "Reservad iluminación o mobiliario especial",
    "Planificad la cena de ensayo",
    "Revisad los requisitos del viaje de luna de miel",
    "Pedid las invitaciones",
    "Comprad las alianzas",
    "Programad los arreglos de vestuario",
    "Elegid los zapatos",
    "Elegid los accesorios",
    "Cerrad el diseño floral",
    "Planificad las despedidas",
    "Elegid detalles para invitados si queréis",
    "Confirmad la estructura de la ceremonia",
    "Elegid el menú",
    "Cerrad el diseño de la tarta",
    "Preparad el primer horario del día de la boda",
    "Enviad las invitaciones",
    "Controlad las confirmaciones",
    "Preparad el primer plano de mesas",
    "Reuníos con el DJ o la banda",
    "Cread la lista de canciones imprescindibles",
    "Cread la lista de canciones prohibidas",
    "Cerrad los trajes de boda",
    "Escribid los votos si corresponde",
    "Preparad los documentos matrimoniales",
    "Confirmad las reservas de luna de miel",
    "Cerrad el transporte de invitados",
    "Preparad bolsas de bienvenida si hacen falta",
    "Reclamad las confirmaciones pendientes",
    "Cerrad el número de invitados",
    "Dad el número final al lugar",
    "Dad el número final al catering",
    "Cerrad el plano de mesas",
    "Confirmad todos los proveedores",
    "Confirmad la música",
    "Confirmad el transporte",
    "Preparad la señalética",
    "Preparad las tarjetas de sitio",
    "Recoged las alianzas",
    "Preparad los pagos restantes",
    "Confirmad el horario final",
    "Compartidlo con los proveedores",
    "Confirmad las necesidades alimentarias",
    "Preparad un kit de emergencia",
    "Elegid a la persona responsable de las alianzas",
    "Asignad quién recoge regalos y tarjetas",
    "Asignad un contacto para proveedores",
    "Practicad el primer baile",
    "Cerrad los discursos",
    "Empezad a preparar la maleta de luna de miel",
    "Recoged los trajes",
    "Comprobad todos los accesorios",
    "Preparad una bolsa para la noche",
    "Confirmad las horas de llegada de proveedores",
    "Asistid al ensayo de ceremonia",
    "Preparad sobres de pago",
    "Preparad los documentos necesarios",
    "Descansad e hidrataos",
    "Llevad la decoración al lugar si hace falta",
    "Comprobad las alianzas",
    "Cargad teléfonos y baterías",
    "Preparad los trajes",
    "Preparad los suministros de emergencia",
    "Comed e hidrataos bien",
    "Dormid lo suficiente",
    "Desayunad y bebed agua",
    "Dejad tiempo suficiente para prepararos",
    "Mantened seguros alianzas y documentos",
    "Delegad la logística en alguien de confianza",
    "Tomad un momento privado juntos",
    "Haced las fotos de grupo importantes",
    "Comed vuestra comida de boda",
    "Disfrutad de la fiesta y del momento",
    "Recoged los objetos personales",
    "Devolved los alquileres",
    "Pagad los saldos pendientes",
    "Limpiad o conservad los trajes",
    "Organizad los regalos",
    "Enviad mensajes de agradecimiento",
    "Compartid las fotos",
    "Valorad a los proveedores",
    "Elegid las fotos del álbum",
    "Completad cambios legales de nombre o documentos",
    "Cerrad las tareas de la luna de miel",
  ],
  hr: [
    "Odredite budžet za vjenčanje",
    "Dogovorite tko financijski sudjeluje",
    "Sastavite prvi popis gostiju",
    "Odaberite datum vjenčanja",
    "Odaberite stil vjenčanja",
    "Istražite lokacije",
    "Rezervirajte lokaciju",
    "Angažirajte organizatora ako je potrebno",
    "Rezervirajte fotografa",
    "Rezervirajte videografa",
    "Istražite catering",
    "Razmotrite osiguranje vjenčanja",
    "Odaberite vjenčanu odjeću",
    "Odredite smjer odjeće partnera",
    "Odaberite boje vjenčanja",
    "Rezervirajte catering",
    "Rezervirajte cvjećara",
    "Rezervirajte DJ-a ili bend",
    "Rezervirajte frizuru i šminku",
    "Rezervirajte voditelja ceremonije",
    "Rezervirajte smještaj za goste",
    "Organizirajte prijevoz",
    "Odaberite svatove",
    "Izradite web-stranicu vjenčanja",
    "Počnite planirati medeni mjesec",
    "Naručite odjeću za svatove",
    "Organizirajte odijela ili svečanu odjeću",
    "Dovršite popis gostiju",
    "Pošaljite save-the-date obavijesti",
    "Odaberite glazbu za ceremoniju",
    "Odaberite čitanja za ceremoniju",
    "Odaberite slastičara",
    "Planirajte dekoracije i najam",
    "Rezervirajte posebnu rasvjetu ili namještaj",
    "Planirajte probnu večeru",
    "Provjerite uvjete putovanja za medeni mjesec",
    "Naručite pozivnice",
    "Kupite vjenčano prstenje",
    "Dogovorite prepravke odjeće",
    "Odaberite cipele",
    "Odaberite dodatke",
    "Dovršite cvjetni koncept",
    "Planirajte momačku ili djevojačku večer",
    "Odaberite zahvalne poklone ako želite",
    "Potvrdite tijek ceremonije",
    "Odaberite jelovnik",
    "Dovršite dizajn torte",
    "Izradite prvi raspored dana vjenčanja",
    "Pošaljite pozivnice",
    "Pratite potvrde dolaska",
    "Izradite nacrt rasporeda sjedenja",
    "Sastanite se s DJ-em ili bendom",
    "Napravite popis obaveznih pjesama",
    "Napravite popis zabranjenih pjesama",
    "Dovršite vjenčanu odjeću",
    "Napišite zavjete ako ih imate",
    "Pripremite dokumente za brak",
    "Potvrdite rezervacije medenog mjeseca",
    "Dovršite prijevoz gostiju",
    "Planirajte pakete dobrodošlice ako trebaju",
    "Provjerite nedostajuće potvrde",
    "Zaključite broj gostiju",
    "Pošaljite konačan broj lokaciji",
    "Pošaljite konačan broj cateringu",
    "Dovršite raspored sjedenja",
    "Potvrdite sve dobavljače",
    "Potvrdite glazbu",
    "Potvrdite prijevoz",
    "Pripremite svadbene oznake",
    "Pripremite kartice s imenima",
    "Preuzmite prstenje",
    "Pripremite preostala plaćanja",
    "Potvrdite konačan raspored",
    "Podijelite raspored s dobavljačima",
    "Potvrdite prehrambene potrebe",
    "Pripremite komplet za hitne slučajeve",
    "Odaberite osobu odgovornu za prstenje",
    "Zadužite nekoga za darove i čestitke",
    "Odredite kontakt-osobu za dobavljače",
    "Vježbajte prvi ples",
    "Dovršite govore",
    "Počnite pakirati za medeni mjesec",
    "Preuzmite vjenčanu odjeću",
    "Provjerite sve dodatke",
    "Spakirajte torbu za noćenje",
    "Potvrdite vrijeme dolaska dobavljača",
    "Sudjelujte na probi ceremonije",
    "Pripremite omotnice za plaćanje",
    "Pripremite potrebne dokumente",
    "Odmorite se i pijte dovoljno vode",
    "Dostavite dekoracije na lokaciju ako treba",
    "Provjerite prstenje",
    "Napunite telefone i prijenosne baterije",
    "Pripremite odjeću",
    "Spakirajte potrepštine za hitne slučajeve",
    "Dobro jedite i pijte vodu",
    "Dovoljno spavajte",
    "Doručkujte i pijte vodu",
    "Ostavite dovoljno vremena za pripremu",
    "Čuvajte prstenje i dokumente",
    "Predajte logistiku osobi od povjerenja",
    "Uzmite privatni trenutak zajedno",
    "Snimite važne grupne fotografije",
    "Pojedite svoj svadbeni obrok",
    "Uživajte u slavlju i trenutku",
    "Prikupite osobne stvari",
    "Vratite unajmljene predmete",
    "Platite preostale račune dobavljača",
    "Očistite ili sačuvajte vjenčanu odjeću",
    "Organizirajte darove",
    "Pošaljite poruke zahvale",
    "Podijelite fotografije",
    "Ocijenite dobavljače",
    "Odaberite fotografije za album",
    "Obavite promjene imena ili dokumenata",
    "Dovršite zadatke za medeni mjesec",
  ],
  de: [
    "Legt euer Hochzeitsbudget fest",
    "Klärt, wer finanziell beiträgt",
    "Erstellt eine erste Gästeliste",
    "Wählt euren Hochzeitstermin",
    "Legt euren Hochzeitsstil fest",
    "Recherchiert Locations",
    "Bucht eure Location",
    "Engagiert bei Bedarf eine Hochzeitsplanung",
    "Bucht die Fotografie",
    "Bucht die Videografie",
    "Recherchiert Catering",
    "Prüft eine Hochzeitsversicherung",
    "Wählt eure Hochzeitsoutfits",
    "Legt die Richtung für das Partner-Outfit fest",
    "Wählt eure Hochzeitsfarben",
    "Bucht das Catering",
    "Bucht die Floristik",
    "Bucht DJ oder Band",
    "Bucht Haare und Make-up",
    "Bucht die Trauungsperson",
    "Reserviert Gästeunterkünfte",
    "Organisiert den Transport",
    "Wählt eure Hochzeitsgesellschaft",
    "Erstellt eure Hochzeitswebsite",
    "Beginnt mit der Flitterwochenplanung",
    "Bestellt die Outfits der Hochzeitsgesellschaft",
    "Organisiert Anzüge oder Festkleidung",
    "Finalisiert die Gästeliste",
    "Versendet Save-the-Dates",
    "Wählt die Musik der Zeremonie",
    "Wählt Lesungen für die Zeremonie",
    "Wählt die Konditorei",
    "Plant Dekoration und Mietartikel",
    "Bucht besondere Beleuchtung oder Möbel",
    "Plant das Probeessen",
    "Prüft die Reiseanforderungen für die Flitterwochen",
    "Bestellt die Einladungen",
    "Kauft die Eheringe",
    "Plant Änderungen der Outfits",
    "Wählt Hochzeitsschuhe",
    "Wählt Accessoires",
    "Finalisiert das Blumenkonzept",
    "Plant Junggesellen- oder Junggesellinnenabschiede",
    "Wählt auf Wunsch Gastgeschenke",
    "Bestätigt den Ablauf der Zeremonie",
    "Wählt das Menü",
    "Finalisiert das Tortendesign",
    "Erstellt den ersten Ablauf für den Hochzeitstag",
    "Versendet die Einladungen",
    "Verfolgt die Rückmeldungen",
    "Erstellt einen ersten Sitzplan",
    "Trefft DJ oder Band",
    "Erstellt eine Must-play-Liste",
    "Erstellt eine No-play-Liste",
    "Finalisiert die Hochzeitsoutfits",
    "Schreibt gegebenenfalls eure Eheversprechen",
    "Bereitet die Heiratsdokumente vor",
    "Bestätigt die Flitterwochenbuchungen",
    "Finalisiert den Gästetransport",
    "Plant bei Bedarf Willkommenspakete",
    "Fragt fehlende Rückmeldungen nach",
    "Finalisiert die Gästezahl",
    "Meldet die endgültige Zahl an die Location",
    "Meldet die endgültige Zahl an das Catering",
    "Finalisiert den Sitzplan",
    "Bestätigt alle Dienstleister",
    "Bestätigt die Musik",
    "Bestätigt den Transport",
    "Bereitet die Hochzeitsschilder vor",
    "Bereitet Platzkarten vor",
    "Holt die Eheringe ab",
    "Bereitet verbleibende Zahlungen vor",
    "Bestätigt den endgültigen Ablauf",
    "Teilt den Ablauf mit den Dienstleistern",
    "Bestätigt Ernährungsanforderungen",
    "Packt ein Notfallset",
    "Bestimmt die verantwortliche Person für die Ringe",
    "Bestimmt jemanden für Geschenke und Karten",
    "Bestimmt eine Kontaktperson für Dienstleister",
    "Übt den ersten Tanz",
    "Finalisiert die Reden",
    "Beginnt für die Flitterwochen zu packen",
    "Holt die Hochzeitsoutfits ab",
    "Prüft alle Accessoires",
    "Packt eine Übernachtungstasche",
    "Bestätigt die Ankunftszeiten der Dienstleister",
    "Nehmt an der Zeremonieprobe teil",
    "Bereitet Zahlungsumschläge vor",
    "Bereitet erforderliche Dokumente vor",
    "Ruht euch aus und trinkt genug",
    "Bringt bei Bedarf die Dekoration zur Location",
    "Prüft die Ringe",
    "Ladet Telefone und Powerbanks",
    "Legt die Outfits bereit",
    "Packt Notfallutensilien",
    "Esst und trinkt ausreichend",
    "Schlaft genug",
    "Frühstückt und trinkt Wasser",
    "Plant genug Zeit zum Fertigmachen ein",
    "Bewahrt Ringe und Dokumente sicher auf",
    "Übergebt die Logistik einer Vertrauensperson",
    "Nehmt euch einen privaten Moment",
    "Macht die wichtigen Gruppenfotos",
    "Esst euer Hochzeitsessen",
    "Genießt die Feier und den Moment",
    "Sammelt persönliche Gegenstände ein",
    "Gebt Mietartikel zurück",
    "Bezahlt offene Dienstleisterrechnungen",
    "Reinigt oder konserviert die Hochzeitsoutfits",
    "Sortiert die Geschenke",
    "Versendet Dankesnachrichten",
    "Teilt die Fotos",
    "Bewertet eure Dienstleister",
    "Wählt Fotos für das Hochzeitsalbum",
    "Erledigt Namens- oder Dokumentänderungen",
    "Schließt die Flitterwochenaufgaben ab",
  ],
};

const CONDITIONAL_EXTRAS: readonly {
  section: ChecklistSectionId;
  leadDays: number;
  id: string;
  condition: ConditionTag;
  title: Record<UiLocale, string>;
}[] = [
  {
    section: "m6_9",
    leadDays: 225,
    id: "outdoor-weather-backup",
    condition: "outdoor",
    title: {
      en: "Plan an indoor weather backup",
      hu: "Tervezzetek beltéri időjárási B-tervet",
      es: "Preparad un plan interior por mal tiempo",
      hr: "Pripremite zatvoreni plan za loše vrijeme",
      de: "Plant eine Schlechtwetter-Alternative drinnen",
    },
  },
  {
    section: "m4_6",
    leadDays: 150,
    id: "outdoor-comfort",
    condition: "outdoor",
    title: {
      en: "Plan shade, heaters or rain cover",
      hu: "Tervezzetek árnyékolást, fűtést vagy esővédelmet",
      es: "Planificad sombra, calefacción o protección de lluvia",
      hr: "Planirajte hlad, grijalice ili zaštitu od kiše",
      de: "Plant Schatten, Heizstrahler oder Regenschutz",
    },
  },
  {
    section: "m4_6",
    leadDays: 150,
    id: "children-entertainment",
    condition: "has_children",
    title: {
      en: "Plan children's entertainment and care",
      hu: "Tervezzétek meg a gyerekek programját és felügyeletét",
      es: "Planificad entretenimiento y cuidado infantil",
      hr: "Planirajte zabavu i skrb za djecu",
      de: "Plant Kinderbetreuung und -unterhaltung",
    },
  },
  {
    section: "m4_6",
    leadDays: 150,
    id: "book-bar-service",
    condition: "alcohol_served",
    title: {
      en: "Book the bar service",
      hu: "Foglaljátok le a bárszolgáltatást",
      es: "Reservad el servicio de bar",
      hr: "Rezervirajte barsku uslugu",
      de: "Bucht den Barservice",
    },
  },
  {
    section: "m2_3",
    leadDays: 75,
    id: "alcohol-quantities",
    condition: "alcohol_served",
    title: {
      en: "Confirm alcohol quantities and licenses",
      hu: "Erősítsétek meg az italmennyiséget és engedélyeket",
      es: "Confirmad cantidades de alcohol y licencias",
      hr: "Potvrdite količine alkohola i dozvole",
      de: "Bestätigt Alkoholmengen und Genehmigungen",
    },
  },
  {
    section: "m2_3",
    leadDays: 75,
    id: "non-alcoholic-options",
    condition: "alcohol_served",
    title: {
      en: "Choose thoughtful non-alcoholic options",
      hu: "Válasszatok igényes alkoholmentes italokat",
      es: "Elegid buenas opciones sin alcohol",
      hr: "Odaberite kvalitetne bezalkoholne opcije",
      de: "Wählt gute alkoholfreie Alternativen",
    },
  },
  {
    section: "m9_12",
    leadDays: 315,
    id: "hotel-blocks",
    condition: "accommodation_needed",
    title: {
      en: "Arrange hotel room blocks",
      hu: "Egyeztessetek szállodai szobakeretet",
      es: "Organizad bloques de habitaciones",
      hr: "Dogovorite blok hotelskih soba",
      de: "Reserviert Hotelzimmerkontingente",
    },
  },
  {
    section: "m2_3",
    leadDays: 75,
    id: "accommodation-information",
    condition: "accommodation_needed",
    title: {
      en: "Share accommodation information with guests",
      hu: "Osszátok meg a szállásinformációkat a vendégekkel",
      es: "Compartid la información de alojamiento",
      hr: "Podijelite informacije o smještaju s gostima",
      de: "Teilt Unterkunftsinformationen mit den Gästen",
    },
  },
] as const;

const FLAT_DEFINITIONS = [
  ...DEFINITIONS.flatMap((section) => section.items),
  ...CONDITIONAL_EXTRAS.map(({ id, condition }) => ({ id, condition })),
];

export interface WeddingChecklistItem {
  id: string;
  /** Stable translation-style identity; useful to analytics and future copy moves. */
  titleKey: `planning.checklist.items.${string}`;
  title: string;
  condition?: ConditionTag;
  dueDate: string | null;
}

export interface WeddingChecklistSection {
  id: ChecklistSectionId;
  titleKey: `planning.checklist.sections.${ChecklistSectionId}`;
  title: string;
  items: WeddingChecklistItem[];
}

export function isChecklistItemApplicable(
  item: Pick<WeddingChecklistItem, "condition">,
  answers: Partial<Record<ConditionTag, "yes" | "no">>,
): boolean {
  // Inclusive by default. Only an explicit "no" removes a conditional item
  // and its contribution to progress; personalization is never required.
  return !item.condition || answers[item.condition] !== "no";
}

export function checklistSections(
  locale: UiLocale,
  weddingDate?: string | null,
  /** Guards the catalog's suggested dates against landing in the past — see
   *  `timelineDatesFor`'s `opts.todayIso`. Omit only when rendering a
   *  read-only reference (the public/anonymous checklist has no wedding date
   *  to compress against anyway). */
  todayIso?: string,
): WeddingChecklistSection[] {
  const titles = ITEM_TITLES[locale];
  let flatIndex = 0;
  return DEFINITIONS.map((section, sectionIndex) => {
    const items: WeddingChecklistItem[] = section.items.map((definition) => {
      const title = titles[flatIndex] ?? ITEM_TITLES.en[flatIndex] ?? definition.id;
      flatIndex += 1;
      const dates = timelineDatesFor(
        weddingDate,
        { lead: { days: section.leadDays }, windowDays: 0 },
        { todayIso },
      );
      return {
        id: definition.id,
        titleKey: `planning.checklist.items.${definition.id}`,
        title,
        condition: definition.condition,
        dueDate: dates?.due_date ?? null,
      };
    });
    for (const extra of CONDITIONAL_EXTRAS.filter((entry) => entry.section === section.id)) {
      const dates = timelineDatesFor(
        weddingDate,
        { lead: { days: extra.leadDays }, windowDays: 0 },
        { todayIso },
      );
      items.push({
        id: extra.id,
        titleKey: `planning.checklist.items.${extra.id}`,
        title: extra.title[locale],
        condition: extra.condition,
        dueDate: dates?.due_date ?? null,
      });
    }
    return {
      id: section.id,
      titleKey: `planning.checklist.sections.${section.id}`,
      title: SECTION_TITLES[locale][sectionIndex] ?? SECTION_TITLES.en[sectionIndex] ?? section.id,
      items,
    };
  });
}

export function checklistItemById(
  id: string,
  locale: UiLocale,
  weddingDate?: string | null,
  todayIso?: string,
) {
  return (
    checklistSections(locale, weddingDate, todayIso)
      .flatMap((section) => section.items)
      .find((entry) => entry.id === id) ?? null
  );
}

export function isChecklistTemplateId(value: string): boolean {
  return FLAT_DEFINITIONS.some((definition) => definition.id === value);
}

export function checklistTemplateSize(): number {
  return FLAT_DEFINITIONS.length;
}

// Fail loudly in development/tests if a translator ever drops an item and
// shifts every title that follows it onto the wrong stable id.
const BASE_DEFINITION_COUNT = DEFINITIONS.flatMap((section) => section.items).length;
for (const locale of Object.keys(ITEM_TITLES) as UiLocale[]) {
  if (ITEM_TITLES[locale].length !== BASE_DEFINITION_COUNT) {
    throw new Error(
      `wedding_checklist: ${locale} has ${ITEM_TITLES[locale].length} titles for ${BASE_DEFINITION_COUNT} base items`,
    );
  }
}
