// 150 questions for couples, organised into 6 decks of 25, in all five UI
// languages. Pure static data, no backend, no auth. Rendered by
// CoupleCardsPage.tsx as a one-card-at-a-time conversation tool on
// /eszkozok/100-kerdes-eskuvo-elott (HU) and
// /tools/100-questions-before-marriage (EN).
//
// The four numbered Level decks are the "100 questions" the page is named
// after; First Date and Lemonade are the two hidden accent packs either
// side of them.
//
// Each deck is independent: deck order is fixed in this array, but card
// order within a deck is randomised on first open and cached in
// localStorage so a returning visitor doesn't get the same shuffle twice
// in a session.
//
// Card COPY is data, not UI chrome, so it does not live in locales/*.ts and
// does not go through t(). Every deck carries a full array per UI locale
// (hr and de ship partial UI trees, but the cards themselves are complete),
// and `deckQuestions` is the only reader.

import { type UiLocale, UI_LOCALES } from "@shared/locales";

export type DeckId = "firstdate" | "roots" | "everyday" | "closeness" | "deepwater" | "lemonade";

/** One array of card text per UI locale. A deck that has not shipped yet
 *  carries five empty arrays, which is what `deckHasCards` reads. */
export type DeckQuestions = Readonly<Record<UiLocale, readonly string[]>>;

export interface Deck {
  id: DeckId;
  /** Locale-keyed UI labels live in tools.couple_cards.*: these are the
   *  card-content strings the deck name short label maps to via t().
   *  We keep the actual titles in locales/{hu,en,es,hr,de}.ts so the deck
   *  picker reads the same translation memory as the rest of the page. */
  titleKey: string;
  blurbKey: string;
  questions: DeckQuestions;
}

const FIRSTDATE: DeckQuestions = {
  en: [
    "What is one small thing that instantly improves your mood?",
    "What are you genuinely looking forward to right now?",
    "What can someone do on a first date that immediately feels like a good sign to you?",
    "Which meal feels comforting to you, and why that one?",
    "Are you a fast replier, a thoughtful replier, or a “sorry, I forgot I own a phone” person?",
    "What song would be playing in the background of your life right now?",
    "What simple date idea do you think is underrated?",
    "What kind of humour makes you laugh every time?",
    "What does a genuinely cosy evening look like for you?",
    "What is a random skill, talent, or oddly specific thing you are surprisingly good at?",
    "When travelling, do you prefer a carefully planned itinerary or seeing what happens as you go?",
    "What kind of compliment genuinely means something to you?",
    "Do you have a daily or weekly ritual that makes your life better?",
    "After a busy week, do you recharge alone, with close friends, or by doing something active?",
    "What topic could you happily talk about for hours?",
    "What small act of kindness do you always notice in other people?",
    "What did you love as a child that you still secretly love today?",
    "What do people often misunderstand about you when they first meet you?",
    "What is the best piece of advice you actually use in everyday life?",
    "What can make someone genuinely charming without looking as though they are trying too hard?",
    "Which three words best describe your taste in music?",
    "A city break, an escape into nature, a lazy weekend at home, or a spontaneous road trip? Choose one and tell me why.",
    "Which quality do you especially appreciate in the people you choose to spend time with?",
    "Which harmless opinion are you surprisingly passionate about?",
    "After tonight, what would be a fun idea for a second date?",
  ],
  hu: [
    "Mi az az apróság, amelytől rögtön jobb kedved lesz?",
    "Mit vársz most igazán?",
    "Mi az, amitől egy első randin rögtön azt érzed, hogy ez jó jel?",
    "Mi az az étel, amitől mindig egy kicsit jobban érzed magad, és miért pont az?",
    "Te inkább azonnal válaszolsz, átgondolod az üzeneteidet, vagy a „bocsi, elfelejtettem, hogy van telefonom” típus vagy?",
    "Ha az életed most egy film lenne, melyik dal szólna alatta?",
    "Mi az az egyszerű randiötlet, amelyet szerinted túl kevesen értékelnek?",
    "Milyen humorral lehet téged mindig megnevettetni?",
    "Neked milyen egy igazán kuckózós este?",
    "Mi az a teljesen váratlan képesség vagy furán specifikus dolog, amelyben meglepően jó vagy?",
    "Utazásnál inkább mindent előre megtervezel, vagy szereted útközben alakítani a programot?",
    "Milyen bók jelent neked igazán sokat?",
    "Van olyan napi vagy heti rituáléd, amely jobbá teszi az életedet?",
    "Egy pörgős hét után hogyan töltődsz fel leginkább: egyedül, közeli barátokkal vagy valamilyen aktív programmal?",
    "Melyik témáról tudnál örömmel órákon át beszélni?",
    "Mi az az apró kedvesség, amelyet mindig észreveszel másokban?",
    "Mi az, amit gyerekként imádtál, és titokban még ma is ugyanúgy szeretsz?",
    "Mit értenek félre veled kapcsolatban az emberek, amikor először találkoznak veled?",
    "Mi a legjobb tanács, amelyet valóban alkalmazol a mindennapokban?",
    "Mitől válik valaki igazán megnyerővé anélkül, hogy úgy tűnne, erőlködik?",
    "Melyik három szó írja le legjobban a zenei ízlésedet?",
    "Városnézés, természetközeli elvonulás, lusta otthoni hétvége vagy spontán autós kiruccanás? Válassz egyet, és mondd el, miért.",
    "Melyik tulajdonságot értékeled különösen azokban, akikkel szívesen töltöd az idődet?",
    "Mi az az ártalmatlan véleményed, amely mellett meglepően szenvedélyesen tudsz érvelni?",
    "A mai este után szerinted mi lenne egy jó program a második randira?",
  ],
  es: [
    "¿Qué pequeña cosa mejora tu estado de ánimo al instante?",
    "¿Qué esperas con verdadera ilusión en este momento?",
    "¿Qué puede hacer alguien en una primera cita que te parezca inmediatamente una buena señal?",
    "¿Qué comida te reconforta de verdad y por qué precisamente esa?",
    "¿Respondes rápido, prefieres pensar bien tus mensajes o eres de los de «perdón, olvidé que tengo móvil»?",
    "¿Qué canción sonaría ahora mismo como banda sonora de tu vida?",
    "¿Qué idea sencilla para una cita te parece infravalorada?",
    "¿Qué tipo de humor consigue hacerte reír siempre?",
    "¿Cómo es para ti una noche verdaderamente acogedora?",
    "¿Qué habilidad inesperada, talento o cosa extrañamente específica se te da sorprendentemente bien?",
    "Cuando viajas, ¿prefieres llevar un itinerario bien planificado o ir viendo qué ocurre sobre la marcha?",
    "¿Qué tipo de cumplido significa algo de verdad para ti?",
    "¿Tienes algún ritual diario o semanal que mejore tu vida?",
    "Después de una semana intensa, ¿recargas energía a solas, con amigos cercanos o haciendo alguna actividad?",
    "¿Sobre qué tema podrías hablar durante horas con gusto?",
    "¿Qué pequeño gesto de amabilidad siempre percibes en los demás?",
    "¿Qué te encantaba de pequeño o pequeña y sigues queriendo en secreto hoy?",
    "¿Qué suele malinterpretar la gente sobre ti cuando te conoce por primera vez?",
    "¿Cuál es el mejor consejo que aplicas de verdad en tu vida cotidiana?",
    "¿Qué puede hacer que una persona resulte verdaderamente encantadora sin parecer que se está esforzando demasiado?",
    "¿Qué tres palabras describen mejor tus gustos musicales?",
    "¿Una escapada urbana, una salida a la naturaleza, un fin de semana tranquilo en casa o un viaje espontáneo por carretera? Elige una opción y dime por qué.",
    "¿Qué cualidad valoras especialmente en las personas con las que eliges pasar tu tiempo?",
    "¿Qué opinión inofensiva defiendes con una pasión sorprendente?",
    "Después de esta noche, ¿qué idea sería divertida para una segunda cita?",
  ],
  hr: [
    "Koja ti sitnica odmah popravi raspoloženje?",
    "Čemu se trenutačno iskreno veseliš?",
    "Što netko može učiniti na prvom spoju, a da ti se odmah učini kao dobar znak?",
    "Koje ti jelo pruža osjećaj utjehe i zašto baš ono?",
    "Odgovaraš li brzo, voliš li dobro promisliti odgovor ili si tip osobe „oprosti, zaboravio ili zaboravila sam da imam mobitel“?",
    "Koja bi pjesma trenutačno svirala u pozadini tvojeg života?",
    "Koja je jednostavna ideja za spoj, po tvojem mišljenju, podcijenjena?",
    "Koja te vrsta humora svaki put nasmije?",
    "Kako za tebe izgleda uistinu ugodna večer?",
    "Koja je neobična vještina, talent ili vrlo specifična stvar u kojoj si iznenađujuće dobar ili dobra?",
    "Kada putuješ, voliš li pažljivo isplaniran raspored ili radije usput vidiš što će se dogoditi?",
    "Kakav ti kompliment uistinu nešto znači?",
    "Imaš li dnevni ili tjedni ritual koji ti život čini boljim?",
    "Kako se najbolje napuniš energijom nakon napornog tjedna: nasamo, s bliskim prijateljima ili uz neku aktivnost?",
    "O kojoj bi temi mogao ili mogla sa zadovoljstvom razgovarati satima?",
    "Koju malu gestu dobrote uvijek primijetiš kod drugih ljudi?",
    "Što si volio ili voljela kao dijete, a potajno voliš i danas?",
    "Što ljudi često pogrešno shvate o tebi kada te prvi put upoznaju?",
    "Koji je najbolji savjet koji doista primjenjuješ u svakodnevnom životu?",
    "Što nekoga može učiniti uistinu šarmantnim, a da ne djeluje kao da se previše trudi?",
    "Koje tri riječi najbolje opisuju tvoj glazbeni ukus?",
    "Gradski odmor, bijeg u prirodu, lijen vikend kod kuće ili spontano putovanje automobilom? Odaberi jedno i reci zašto.",
    "Koju osobinu posebno cijeniš kod ljudi s kojima biraš provoditi vrijeme?",
    "Koje bezazleno mišljenje zastupaš s iznenađujućom strašću?",
    "Što bi nakon večerašnjeg susreta bila zabavna ideja za drugi spoj?",
  ],
  de: [
    "Welche Kleinigkeit hebt sofort deine Stimmung?",
    "Worauf freust du dich gerade wirklich?",
    "Was kann jemand bei einem ersten Date tun, das sich für dich sofort wie ein gutes Zeichen anfühlt?",
    "Welches Essen gibt dir ein Gefühl von Geborgenheit, und warum gerade dieses?",
    "Antwortest du schnell, überlegt oder gehörst du eher zur Sorte „Sorry, ich habe vergessen, dass ich ein Handy besitze“?",
    "Welcher Song würde gerade im Hintergrund deines Lebens laufen?",
    "Welche einfache Date-Idee wird deiner Meinung nach unterschätzt?",
    "Welche Art von Humor bringt dich jedes Mal zum Lachen?",
    "Wie sieht für dich ein richtig gemütlicher Abend aus?",
    "Welche ungewöhnliche Fähigkeit oder erstaunlich spezielle Sache kannst du überraschend gut?",
    "Hast du auf Reisen lieber einen sorgfältig geplanten Ablauf oder schaust du gern spontan, was sich ergibt?",
    "Welche Art von Kompliment bedeutet dir wirklich etwas?",
    "Hast du ein tägliches oder wöchentliches Ritual, das dein Leben besser macht?",
    "Wie tankst du nach einer anstrengenden Woche am besten auf: allein, mit engen Freunden oder bei einer aktiven Unternehmung?",
    "Über welches Thema könntest du mit Freude stundenlang sprechen?",
    "Welche kleine freundliche Geste fällt dir bei anderen Menschen immer auf?",
    "Was hast du als Kind geliebt und liebst es insgeheim noch heute?",
    "Was verstehen Menschen oft falsch an dir, wenn sie dich zum ersten Mal kennenlernen?",
    "Was ist der beste Ratschlag, den du im Alltag tatsächlich befolgst?",
    "Was macht jemanden wirklich charmant, ohne dass es angestrengt wirkt?",
    "Welche drei Wörter beschreiben deinen Musikgeschmack am besten?",
    "Städtetrip, Auszeit in der Natur, entspanntes Wochenende zu Hause oder spontaner Roadtrip? Wähle eines und erzähl mir, warum.",
    "Welche Eigenschaft schätzt du besonders an den Menschen, mit denen du gern Zeit verbringst?",
    "Welche harmlose Meinung vertrittst du mit überraschend großer Leidenschaft?",
    "Was wäre nach heute Abend eine schöne Idee für ein zweites Date?",
  ],
};

const ROOTS: DeckQuestions = {
  en: [
    "Which tradition from your childhood would you bring into our life together, and which would you deliberately leave behind?",
    "Which family meal or gathering do you still remember with a smile, and why that one?",
    "How was success celebrated in your home, and how was failure handled?",
    "What did love look like in your home: words, touch, practical help, time together, or something else?",
    "Who made you feel safe as a child, and what did they do that created that feeling?",
    "What kind of holiday table did you grow up around: quiet, loud, tense, prayerful, chaotic, warm, or something else?",
    "What sentence about money was often repeated in your family and still echoes in your head today?",
    "How did people apologise in your family, if they apologised at all?",
    "Which emotion was difficult or forbidden to express in your home?",
    "What did you grow up hearing about what a man, a woman, or a partner was supposed to be?",
    "What conflict pattern did you carry into adulthood that you still need to work on?",
    "What did you inherit from the people who raised you that you are grateful for?",
    "What did you inherit from the people who raised you that you do not want to pass on?",
    "How did the adults in your home respond when someone cried or became emotionally overwhelmed?",
    "Who seemed to be loved unconditionally in your family, and who seemed to have to earn love?",
    "Was there a divorce, separation, or quiet distance in your family, and how did it shape you?",
    "Was there a relationship in your family that quietly fell apart while everyone kept up appearances?",
    "Was there a moment, loss, or change that rearranged your family, even if no one described it that way?",
    "Who was the first person in your family whose death you remember, and who showed you how to grieve?",
    "Is there a family secret you learned even though you were not supposed to know it?",
    "What could you not ask about at home? What would you ask now if no one became upset?",
    "Who in your family are you still angry with, even if you rarely admit it?",
    "What were the people who raised you like, and if you want children, what kind of parent would you hope to be?",
    "What kind of relationship would you like to have with my family? What would feel natural, and what would feel forced?",
    "How should we divide holidays fairly when both families hope to spend them with us?",
  ],
  hu: [
    "Melyik gyerekkori hagyományodat hoznád át a közös életünkbe, és melyiket hagynád szándékosan magad mögött?",
    "Melyik családi étkezésre vagy összejövetelre emlékszel még ma is mosolyogva, és miért pont arra?",
    "Hogyan ünnepelték nálatok a sikert, és hogyan kezelték a kudarcot?",
    "Hogyan mutatták ki nálatok a szeretetet: szavakkal, érintéssel, gyakorlati segítséggel, együtt töltött idővel vagy valami mással?",
    "Ki mellett érezted magad biztonságban gyerekként, és mit tett azért, hogy ezt érezd?",
    "Milyen ünnepi asztal mellett nőttél fel: csendes, hangos, feszült, imádságos, kaotikus, meghitt vagy valami más?",
    "Milyen pénzzel kapcsolatos mondat ismétlődött gyakran a családodban, amelyet ma is hallasz a fejedben?",
    "Hogyan kértek bocsánatot nálatok otthon, ha egyáltalán kértek?",
    "Melyik érzelmet volt nehéz vagy tilos kimutatni nálatok otthon?",
    "Mit hallottál gyerekként arról, milyennek „kellene lennie” egy férfinak, egy nőnek vagy egy társnak?",
    "Milyen konfliktusmintát hoztál magaddal felnőttkorodra, amelyen még dolgoznod kell?",
    "Mit örököltél azoktól, akik felneveltek, amiért hálás vagy?",
    "Mit örököltél azoktól, akik felneveltek, amit nem szeretnél továbbadni?",
    "Hogyan reagáltak nálatok a felnőttek, amikor valaki sírt vagy érzelmileg túlterhelődött?",
    "Kit szerettek látszólag feltétel nélkül a családodban, és kinek kellett úgy éreznie, hogy ki kell érdemelnie a szeretetet?",
    "Volt válás, különköltözés vagy kimondatlan eltávolodás a családodban? Hogyan formált ez téged?",
    "Volt olyan kapcsolat a családodban, amely csendben szétesett, miközben kifelé továbbra is minden rendben lévőnek tűnt?",
    "Volt olyan pillanat, veszteség vagy változás, amely átrendezte a családodat, még ha senki nem is nevezte így?",
    "Ki volt az első családtag, akinek a halálára emlékszel, és kitől tanultad meg, hogyan lehet gyászolni?",
    "Van olyan családi titok, amelyet úgy tudtál meg, hogy nem kellett volna tudnod róla?",
    "Miről nem lehetett kérdezni nálatok otthon? Mit kérdeznél meg most, ha senki nem sértődne meg?",
    "Kire haragszol még mindig a családodban, még ha ritkán is vallod be?",
    "Milyenek voltak azok, akik felneveltek, és ha szeretnél gyereket, te milyen szülő szeretnél lenni?",
    "Milyen kapcsolatot szeretnél a családommal? Mi érződne természetesnek, és mi erőltetettnek?",
    "Hogyan osszuk meg igazságosan az ünnepeket, amikor mindkét család szeretné, hogy velük legyünk?",
  ],
  es: [
    "¿Qué tradición de tu infancia llevarías a nuestra vida en común y cuál dejarías atrás deliberadamente?",
    "¿Qué comida o reunión familiar sigues recordando con una sonrisa y por qué precisamente esa?",
    "¿Cómo se celebraban los éxitos en tu casa y cómo se afrontaban los fracasos?",
    "¿Cómo se demostraba el amor en tu casa: con palabras, contacto físico, ayuda práctica, tiempo compartido o de alguna otra manera?",
    "¿Quién te hacía sentir a salvo durante tu infancia y qué hacía para transmitirte esa seguridad?",
    "¿Cómo eran las celebraciones familiares en torno a la mesa cuando crecías: tranquilas, ruidosas, tensas, marcadas por la oración, caóticas, acogedoras o de otro tipo?",
    "¿Qué frase sobre el dinero se repetía a menudo en tu familia y todavía resuena hoy en tu cabeza?",
    "¿Cómo se pedía perdón en tu familia, si es que se pedía?",
    "¿Qué emoción era difícil o estaba prohibido expresar en tu casa?",
    "¿Qué escuchabas al crecer sobre cómo debía ser un hombre, una mujer o una persona como pareja?",
    "¿Qué patrón de conflicto arrastraste hasta la edad adulta y todavía necesitas trabajar?",
    "¿Qué heredaste de las personas que te criaron que hoy agradeces?",
    "¿Qué heredaste de las personas que te criaron que no quieres transmitir?",
    "¿Cómo reaccionaban los adultos de tu casa cuando alguien lloraba o se sentía emocionalmente desbordado?",
    "¿Quién parecía recibir amor incondicional en tu familia y quién parecía tener que ganárselo?",
    "¿Hubo algún divorcio, separación o distanciamiento silencioso en tu familia? ¿Cómo te marcó?",
    "¿Hubo alguna relación en tu familia que se desmoronó en silencio mientras todos mantenían las apariencias?",
    "¿Hubo algún momento, pérdida o cambio que reconfiguró a tu familia, aunque nadie lo describiera así?",
    "¿Quién fue el primer familiar cuya muerte recuerdas y quién te enseñó a vivir el duelo?",
    "¿Hay algún secreto familiar que descubriste aunque se suponía que no debías conocerlo?",
    "¿Sobre qué no se podía preguntar en tu casa? ¿Qué preguntarías ahora si nadie se enfadara ni se sintiera herido?",
    "¿Con quién de tu familia sigues enfadado o enfadada, aunque rara vez lo admitas?",
    "¿Cómo eran las personas que te criaron y, si quieres tener hijos, qué clase de madre o padre te gustaría ser?",
    "¿Qué tipo de relación te gustaría tener con mi familia? ¿Qué te resultaría natural y qué te parecería forzado?",
    "¿Cómo deberíamos repartir nuestro tiempo durante las fiestas de manera justa cuando ambas familias quieren que las pasemos con ellas?",
  ],
  hr: [
    "Koju bi tradiciju iz djetinjstva prenio ili prenijela u naš zajednički život, a koju bi svjesno ostavio ili ostavila iza sebe?",
    "Kojeg se obiteljskog obroka ili okupljanja i danas sjećaš s osmijehom i zašto baš njega?",
    "Kako se u tvojem domu slavio uspjeh, a kako se nosilo s neuspjehom?",
    "Kako se u tvojem domu pokazivala ljubav: riječima, dodirom, praktičnom pomoći, zajedničkim vremenom ili na neki drugi način?",
    "Uz koga si se kao dijete osjećao ili osjećala sigurno i što je ta osoba činila da se tako osjećaš?",
    "Za kakvim si blagdanskim stolom odrastao ili odrastala: tihim, glasnim, napetim, molitvenim, kaotičnim, toplim ili drukčijim?",
    "Koja se rečenica o novcu često ponavljala u tvojoj obitelji i još ti i danas odzvanja u glavi?",
    "Kako su se ljudi u tvojoj obitelji ispričavali, ako su se uopće ispričavali?",
    "Koju je emociju u tvojem domu bilo teško ili zabranjeno izražavati?",
    "Što si tijekom odrastanja slušao ili slušala o tome što se očekuje od muškarca, žene ili partnera?",
    "Koji si obrazac sukoba prenio ili prenijela u odraslu dob, a na kojem još trebaš raditi?",
    "Što si naslijedio ili naslijedila od ljudi koji su te odgojili, a za što si zahvalan ili zahvalna?",
    "Što si naslijedio ili naslijedila od ljudi koji su te odgojili, a što ne želiš prenositi dalje?",
    "Kako su odrasli u tvojem domu reagirali kada bi netko plakao ili bio preplavljen emocijama?",
    "Tko je u tvojoj obitelji, činilo se, bio voljen bezuvjetno, a tko je, činilo se, morao zaslužiti ljubav?",
    "Je li u tvojoj obitelji bilo razvoda, rastave ili tihog udaljavanja i kako je to oblikovalo tebe?",
    "Je li u tvojoj obitelji postojao odnos koji se tiho raspadao dok su svi održavali privid da je sve u redu?",
    "Je li postojao trenutak, gubitak ili promjena koja je iz temelja promijenila tvoju obitelj, čak i ako to nitko nije tako nazvao?",
    "Tko je bio prvi član tvoje obitelji čije se smrti sjećaš i tko ti je pokazao kako tugovati?",
    "Postoji li obiteljska tajna koju si saznao ili saznala iako je trebala ostati skrivena od tebe?",
    "O čemu se u tvojem domu nije smjelo pitati? Što bi pitao ili pitala sada kada se nitko ne bi uzrujao?",
    "Na koga si u svojoj obitelji još uvijek ljut ili ljuta, čak i ako to rijetko priznaješ?",
    "Kakvi su bili ljudi koji su te odgojili i, ako želiš djecu, kakav bi roditelj želio ili željela biti?",
    "Kakav bi odnos želio ili željela imati s mojom obitelji? Što bi ti bilo prirodno, a što nametnuto?",
    "Kako ćemo pravedno podijeliti blagdane kada obje obitelji žele da ih provedemo s njima?",
  ],
  de: [
    "Welche Tradition aus deiner Kindheit würdest du in unser gemeinsames Leben mitnehmen, und welche würdest du bewusst hinter dir lassen?",
    "An welches Familienessen oder Beisammensein denkst du noch heute mit einem Lächeln zurück, und warum gerade daran?",
    "Wie wurden bei euch zu Hause Erfolge gefeiert, und wie ging man mit Misserfolgen um?",
    "Wie wurde bei euch zu Hause Liebe gezeigt: durch Worte, Berührungen, praktische Hilfe, gemeinsame Zeit oder auf andere Weise?",
    "Bei wem hast du dich als Kind sicher gefühlt, und wodurch hat diese Person dir dieses Gefühl gegeben?",
    "Wie war die Stimmung am Festtagstisch, an dem du aufgewachsen bist: still, laut, angespannt, andächtig, chaotisch, herzlich oder ganz anders?",
    "Welcher Satz über Geld wurde in deiner Familie oft wiederholt und klingt dir bis heute im Kopf nach?",
    "Wie hat man sich in deiner Familie entschuldigt, falls man sich überhaupt entschuldigt hat?",
    "Welches Gefühl war bei euch zu Hause nur schwer auszudrücken oder durfte gar nicht gezeigt werden?",
    "Was hast du beim Aufwachsen darüber gehört, wie ein Mann, eine Frau oder ein Partner angeblich sein sollte?",
    "Welches Konfliktmuster hast du ins Erwachsenenleben mitgenommen, an dem du noch arbeiten musst?",
    "Was hast du von den Menschen übernommen, die dich großgezogen haben, wofür du dankbar bist?",
    "Was hast du von den Menschen übernommen, die dich großgezogen haben, das du nicht weitergeben möchtest?",
    "Wie reagierten die Erwachsenen bei euch zu Hause, wenn jemand weinte oder von seinen Gefühlen überwältigt war?",
    "Wer schien in deiner Familie bedingungslos geliebt zu werden, und wer schien sich Liebe verdienen zu müssen?",
    "Gab es in deiner Familie eine Scheidung, Trennung oder stille Entfremdung, und wie hat dich das geprägt?",
    "Gab es in deiner Familie eine Beziehung, die still zerbrach, während nach außen der Schein gewahrt wurde?",
    "Gab es einen Moment, Verlust oder Wandel, der deine Familie grundlegend verändert hat, auch wenn es niemand so benannt hat?",
    "Wer war der erste Mensch in deiner Familie, an dessen Tod du dich erinnerst, und wer hat dir gezeigt, wie man trauert?",
    "Gibt es ein Familiengeheimnis, das du herausgefunden hast, obwohl du eigentlich nichts davon wissen solltest?",
    "Worüber durfte bei euch zu Hause nicht gesprochen oder gefragt werden? Was würdest du heute fragen, wenn niemand verletzt oder verärgert reagieren würde?",
    "Auf wen in deiner Familie bist du noch immer wütend, auch wenn du es selten zugibst?",
    "Wie würdest du die Menschen beschreiben, die dich großgezogen haben, und was für ein Elternteil würdest du gern sein, falls du Kinder möchtest?",
    "Welche Art von Beziehung möchtest du zu meiner Familie haben? Was würde sich natürlich anfühlen, und was eher gezwungen?",
    "Wie teilen wir Feiertage fair auf, wenn beide Familien sie mit uns verbringen möchten?",
  ],
};

const EVERYDAY: DeckQuestions = {
  en: [
    "What monthly amount can either of us spend freely without checking with the other first?",
    "Do you know my exact take-home income? Do I know yours?",
    "Joint accounts, separate accounts, or a combination of both? Why would that suit us best?",
    "What was the last purchase you regretted, and what did it teach you about yourself?",
    "Are there any debts, financial obligations, accounts, savings, or money-related worries we have not discussed openly yet?",
    "How would you feel if I earned considerably more than you? And the other way around?",
    "How large should our financial safety net be for both of us to sleep well at night?",
    "How would you feel if one of our families helped us financially with a home? What expectations could come with that help?",
    "How much time should we spend with our families, and when would it begin to feel like too much?",
    "What boundaries do we need with each other’s families around visits, advice, money, keys, and opinions?",
    "How should we decide where to live if our wishes are different?",
    "Where do you honestly imagine us living five years from now?",
    "Would you move to another city or country for my career? Would I move for yours?",
    "What would we do if one of us were out of work for a year?",
    "What would a fair, not necessarily equal, division of shopping, cooking, cleaning, planning, appointments and care work look like to us?",
    "How much clutter can you live with before it begins to affect you?",
    "Has there been a purchase you hesitated to tell me about? What made it difficult to share?",
    "Does any friendship, yours or mine, create tension between us? How could we discuss it without becoming defensive?",
    "What counts as privacy, and what counts as secrecy, when it comes to phones, messages, and social media?",
    "How much time alone does each of us need, and how can we ask for it without the other feeling rejected?",
    "Which dream of yours have you already set aside for our shared life without ever mentioning it?",
    "What would we do if we suddenly inherited a substantial amount of money?",
    "How much of our life are we willing to give to work, ambition, or building something bigger?",
    "Do we want children? If so, how many, and how would we face it if parenthood did not happen the way we hoped?",
    "If we become parents, how would we divide parental leave, night-time care, household work, and paid work?",
  ],
  hu: [
    "Mekkora az az összeg havonta, amelyet bármelyikünk szabadon elkölthet anélkül, hogy előtte egyeztetne a másikkal?",
    "Tudod pontosan, mennyi a nettó jövedelmem? Én tudom a tiédet?",
    "Közös számlák, külön számlák vagy a kettő kombinációja? Miért ez illene hozzánk a legjobban?",
    "Mi volt az utolsó vásárlásod, amelyet megbántál, és mit tanított neked önmagadról?",
    "Van olyan tartozás, pénzügyi kötelezettség, számla, megtakarítás vagy pénzzel kapcsolatos aggodalom, amelyről még nem beszéltünk nyíltan?",
    "Mit éreznél, ha én jelentősen többet keresnék nálad? És fordítva?",
    "Mekkora pénzügyi tartalékra lenne szükségünk ahhoz, hogy mindketten nyugodtan aludjunk?",
    "Mit éreznél, ha valamelyik családunk anyagilag segítene nekünk az otthonteremtésben? Milyen elvárások járhatnának ezzel a segítséggel?",
    "Mennyi időt töltsünk a családjainkkal, és mikortól éreznénk úgy, hogy ez már túl sok?",
    "Milyen határokra van szükségünk egymás családjával kapcsolatban a látogatások, tanácsok, pénz, kulcsok és vélemények terén?",
    "Hogyan döntsük el, hol éljünk, ha különböznek a vágyaink?",
    "Őszintén hol képzelsz el minket öt év múlva?",
    "Elköltöznél egy másik városba vagy országba az én karrierem miatt? Én elköltöznék a tiéd miatt?",
    "Mit tennénk, ha egyikünk egy évig munka nélkül maradna?",
    "Hogyan nézne ki számunkra a bevásárlás, főzés, takarítás, szervezés, időpontok és gondoskodási feladatok igazságos, nem feltétlenül egyenlő megosztása?",
    "Mennyi rendetlenséget viselsz jól, és mikortól kezd igazán zavarni vagy kimeríteni?",
    "Volt olyan vásárlásod, amelyet nehéz volt elmondanod nekem? Miért volt nehéz beszélni róla?",
    "Okoz-e feszültséget köztünk valamelyik barátság, akár a tiéd, akár az enyém? Hogyan beszélhetnénk róla anélkül, hogy rögtön védekezni kezdenénk?",
    "Mi számít magánszférának, és mi számít titkolózásnak a telefonok, üzenetek és közösségi média esetében?",
    "Mennyi egyedül töltött időre van szüksége mindkettőnknek, és hogyan kérhetjük ezt úgy, hogy a másik ne érezze elutasítva magát?",
    "Melyik álmodat tetted már félre a közös életünk miatt úgy, hogy még sosem mondtad ki?",
    "Mit tennénk, ha hirtelen jelentős összeget örökölnénk?",
    "Az életünkből mennyit vagyunk hajlandók munkára, ambícióra vagy valami nagyobb felépítésére fordítani?",
    "Szeretnénk gyereket? Ha igen, hányat, és hogyan néznénk szembe azzal, ha a szülővé válás nem úgy alakulna, ahogy reméljük?",
    "Ha szülőkké válunk, hogyan osztanánk meg a szülői szabadságot, az éjszakai gondoskodást, a házimunkát és a fizetett munkát?",
  ],
  es: [
    "¿Qué cantidad mensual puede gastar cada uno libremente sin consultarlo antes con el otro?",
    "¿Sabes exactamente cuáles son mis ingresos netos? ¿Sé yo cuáles son los tuyos?",
    "¿Cuentas conjuntas, separadas o una combinación de ambas? ¿Por qué sería esa la mejor opción para nosotros?",
    "¿Cuál fue la última compra de la que te arrepentiste y qué te enseñó sobre ti?",
    "¿Hay alguna deuda, obligación económica, cuenta, ahorro o preocupación relacionada con el dinero de la que todavía no hayamos hablado abiertamente?",
    "¿Cómo te sentirías si yo ganara bastante más que tú? ¿Y si fuera al revés?",
    "¿De qué tamaño debería ser nuestro colchón financiero para que ambos pudiéramos dormir tranquilos?",
    "¿Cómo te sentirías si una de nuestras familias nos ayudara económicamente a conseguir una vivienda? ¿Qué expectativas podrían acompañar esa ayuda?",
    "¿Cuánto tiempo deberíamos pasar con nuestras familias y cuándo empezaría a parecernos demasiado?",
    "¿Qué límites necesitamos con la familia del otro respecto a las visitas, los consejos, el dinero, las llaves y las opiniones?",
    "¿Cómo deberíamos decidir dónde vivir si nuestros deseos son distintos?",
    "Si eres completamente sincero o sincera, ¿dónde imaginas que viviremos dentro de cinco años?",
    "¿Te mudarías a otra ciudad o a otro país por mi carrera? ¿Me mudaría yo por la tuya?",
    "¿Qué haríamos si uno de los dos se quedara sin trabajo durante un año?",
    "¿Cómo sería para nosotros un reparto justo, aunque no necesariamente igual, de las compras, la cocina, la limpieza, la planificación, las citas y los cuidados?",
    "¿Cuánto desorden puedes tolerar antes de que empiece a afectarte?",
    "¿Ha habido alguna compra que dudaste en contarme? ¿Por qué te resultó difícil hablar de ella?",
    "¿Hay alguna amistad, tuya o mía, que genere tensión entre nosotros? ¿Cómo podríamos hablar de ella sin ponernos a la defensiva?",
    "¿Qué consideramos privacidad y qué consideramos ocultación cuando se trata de teléfonos, mensajes y redes sociales?",
    "¿Cuánto tiempo a solas necesita cada uno y cómo podemos pedirlo sin que el otro se sienta rechazado?",
    "¿Qué sueño tuyo has dejado ya a un lado por nuestra vida en común sin haberlo mencionado nunca?",
    "¿Qué haríamos si de repente heredáramos una cantidad importante de dinero?",
    "¿Qué parte de nuestra vida estamos dispuestos a dedicar al trabajo, a la ambición o a construir algo más grande?",
    "¿Queremos tener hijos? En caso afirmativo, ¿cuántos? ¿Y cómo afrontaríamos que nuestro camino hacia la maternidad o paternidad no se desarrollara como esperábamos?",
    "Si tenemos hijos, ¿cómo repartiríamos los permisos parentales, los cuidados nocturnos, las tareas domésticas y el trabajo remunerado?",
  ],
  hr: [
    "Koliki iznos svatko od nas može mjesečno slobodno potrošiti bez prethodnog dogovora s drugim?",
    "Znaš li točno koliki je moj neto prihod? Znam li ja koliki je tvoj?",
    "Zajednički računi, odvojeni računi ili kombinacija jednog i drugog? Zašto bi nam to najbolje odgovaralo?",
    "Koja je posljednja kupnja zbog koje si požalio ili požalila i što te naučila o tebi?",
    "Postoje li dugovi, financijske obveze, računi, ušteđevina ili brige povezane s novcem o kojima još nismo otvoreno razgovarali?",
    "Kako bi se osjećao ili osjećala kada bih ja zarađivao ili zarađivala znatno više od tebe? A obrnuto?",
    "Kolika bi trebala biti naša financijska pričuva da bismo oboje mogli mirno spavati?",
    "Kako bi se osjećao ili osjećala kada bi nam jedna od naših obitelji financijski pomogla oko doma? Kakva bi očekivanja mogla doći s tom pomoći?",
    "Koliko bismo vremena trebali provoditi sa svojim obiteljima i kada bi to počelo djelovati kao previše?",
    "Koje su nam granice potrebne s obiteljima onog drugog kada je riječ o posjetima, savjetima, novcu, ključevima i mišljenjima?",
    "Kako ćemo odlučiti gdje živjeti ako su nam želje različite?",
    "Gdje nas iskreno zamišljaš za pet godina?",
    "Bi li se preselio ili preselila u drugi grad ili državu zbog moje karijere? Bih li se ja preselio ili preselila zbog tvoje?",
    "Što bismo učinili kada bi jedno od nas godinu dana bilo bez posla?",
    "Kako bi za nas izgledala pravedna, ne nužno jednaka podjela kupnje, kuhanja, čišćenja, planiranja, dogovaranja termina i brige o drugima?",
    "Koliko nereda možeš podnijeti prije nego što počne utjecati na tebe?",
    "Je li bilo kupnje o kojoj si mi oklijevao ili oklijevala reći? Zbog čega ti je to bilo teško podijeliti?",
    "Stvara li neko prijateljstvo, tvoje ili moje, napetost među nama? Kako bismo o tome mogli razgovarati bez obrambenog stava?",
    "Što smatramo privatnošću, a što skrivanjem kada je riječ o telefonima, porukama i društvenim mrežama?",
    "Koliko vremena nasamo treba svakome od nas i kako ga možemo zatražiti, a da se druga osoba ne osjeti odbačeno?",
    "Koji si svoj san već ostavio ili ostavila po strani zbog našeg zajedničkog života, a da to nikada nisi spomenuo ili spomenula?",
    "Što bismo učinili kada bismo iznenada naslijedili znatnu svotu novca?",
    "Koliki smo dio svojeg života spremni posvetiti poslu, ambiciji ili izgradnji nečeg većeg?",
    "Želimo li djecu? Ako ih želimo, koliko? I kako bismo se nosili s time kada se roditeljstvo ne bi ostvarilo onako kako smo se nadali?",
    "Ako postanemo roditelji, kako bismo podijelili roditeljski dopust, noćnu brigu, kućanske poslove i plaćeni rad?",
  ],
  de: [
    "Welchen Betrag darf jeder von uns monatlich frei ausgeben, ohne sich vorher mit dem anderen abzustimmen?",
    "Kennst du mein genaues Nettoeinkommen? Kenne ich deines?",
    "Gemeinsame Konten, getrennte Konten oder eine Mischung aus beidem? Warum würde das am besten zu uns passen?",
    "Welchen Kauf hast du zuletzt bereut, und was hat er dir über dich selbst gezeigt?",
    "Gibt es Schulden, finanzielle Verpflichtungen, Konten, Ersparnisse oder Geldsorgen, über die wir noch nicht offen gesprochen haben?",
    "Wie würdest du dich fühlen, wenn ich deutlich mehr verdienen würde als du? Und umgekehrt?",
    "Wie groß sollte unser finanzielles Polster sein, damit wir beide nachts ruhig schlafen können?",
    "Wie würdest du dich fühlen, wenn eine unserer Familien uns finanziell bei einem Zuhause helfen würde? Welche Erwartungen könnten mit dieser Hilfe verbunden sein?",
    "Wie viel Zeit sollten wir mit unseren Familien verbringen, und ab wann würde es sich nach zu viel anfühlen?",
    "Welche Grenzen brauchen wir gegenüber der Familie des anderen bei Besuchen, Ratschlägen, Geld, Schlüsseln und Meinungen?",
    "Wie entscheiden wir, wo wir leben, wenn unsere Wünsche auseinandergehen?",
    "Wo siehst du uns ganz ehrlich in fünf Jahren leben?",
    "Würdest du für meine Karriere in eine andere Stadt oder ein anderes Land ziehen? Würde ich es für deine tun?",
    "Was würden wir tun, wenn einer von uns ein Jahr lang ohne Arbeit wäre?",
    "Wie sähe für uns eine faire, nicht zwingend gleiche Aufteilung von Einkaufen, Kochen, Putzen, Planen, Terminen und Fürsorgearbeit aus?",
    "Wie viel Unordnung kannst du aushalten, bevor sie anfängt, dich zu belasten?",
    "Gab es einen Kauf, von dem du mir nur ungern erzählt hast? Warum fiel es dir schwer, ihn anzusprechen?",
    "Erzeugt eine Freundschaft, deine oder meine, Spannung zwischen uns? Wie könnten wir darüber sprechen, ohne sofort in eine Abwehrhaltung zu gehen?",
    "Was gilt bei Handys, Nachrichten und sozialen Medien als Privatsphäre, und was als Geheimhaltung?",
    "Wie viel Zeit für sich braucht jeder von uns, und wie können wir darum bitten, ohne dass der andere sich zurückgewiesen fühlt?",
    "Welchen deiner Träume hast du bereits für unser gemeinsames Leben zurückgestellt, ohne es je anzusprechen?",
    "Was würden wir tun, wenn wir plötzlich eine größere Geldsumme erben würden?",
    "Wie viel von unserem Leben sind wir bereit, Arbeit, Ehrgeiz oder dem Aufbau von etwas Größerem zu widmen?",
    "Möchten wir Kinder? Wenn ja, wie viele, und wie würden wir damit umgehen, wenn Elternschaft nicht so möglich wäre, wie wir es uns erhoffen?",
    "Falls wir Eltern werden: Wie würden wir Elternzeit, nächtliche Betreuung, Hausarbeit und Erwerbsarbeit aufteilen?",
  ],
};

const CLOSENESS: DeckQuestions = {
  en: [
    "When did you realise that you were not only in love with me, but actively choosing me?",
    "Which shared moment still makes you smile or laugh when you remember it on your own?",
    "What is a quirk of mine that others might find strange but you have grown to love?",
    "Which small gesture or habit of mine have you picked up without noticing?",
    "What does it mean to you when I sit beside you and simply stay quiet?",
    "Is there a silence between us that feels like home, and another that creates tension? Where is the line between them?",
    "What gives me away when something is wrong, even before I can name it myself?",
    "What does the word “home” mean to you: a place, a person, a rhythm, or something else?",
    "What small ritual of ours can turn an ordinary weekday into a tiny celebration?",
    "What is a question you wish I would ask you, but I never do?",
    "What do you wish I would notice about you that you have not yet said out loud?",
    "What does faithfulness mean to you, and which behaviours would feel like crossing a boundary?",
    "What should we do if our levels of desire differ for a while, with one of us wanting more and the other less?",
    "How would you like us to talk about desire, boundaries, and trying something different in bed?",
    "If one of us withdraws from intimacy, how can we respond with curiosity and care rather than taking it immediately as rejection?",
    "What should never happen during an argument, even when we are furious?",
    "Have you ever said something to me in anger that was more about an old wound than about me?",
    "What is the first sentence you want to hear from me after a fight?",
    "What do you want me to do when you are crying and do not want to speak: stay beside you, hold you, ask questions, or give you space?",
    "What have you forgiven me for in words but still sometimes feel like an old scar?",
    "Is there a question you have been afraid to ask me because you do not know what you would do with the answer?",
    "Which side of yourself do you show only when you feel completely safe?",
    "What did you start doing differently because of me without me ever asking?",
    "When do you feel most deeply connected to me?",
    "What about us right now do you think we will still look back on with a smile in twenty years?",
  ],
  hu: [
    "Mikor érezted először, hogy nemcsak szerelmes vagy belém, hanem tudatosan engem választasz?",
    "Melyik közös pillanatunk jut néha eszedbe úgy, hogy egyedül is elmosolyodsz vagy felnevetsz tőle?",
    "Mi az a furcsaságom, amelyet mások talán különösnek tartanának, de te idővel megszeretted?",
    "Melyik apró mozdulatomat vagy szokásomat vetted át észrevétlenül?",
    "Mit jelent neked, amikor leülök melléd, és egyszerűen csak csendben ott maradok?",
    "Van olyan csend köztünk, amely otthonos, és olyan, amely feszültséget teremt? Hol van közöttük a határ?",
    "Mi árul el engem, amikor valami nincs rendben, még mielőtt én magam meg tudnám nevezni?",
    "Mit jelent neked az „otthon” szó: egy helyet, egy embert, egy ritmust vagy valami mást?",
    "Mi az a kis közös rituálénk, amely egy egyszerű hétköznapot is apró ünneppé tud változtatni?",
    "Mi az a kérdés, amelyet szeretnéd, hogy feltegyek neked, de sosem teszem?",
    "Mi az, amit szeretnéd, hogy észrevegyek rajtad, de még nem mondtál ki hangosan?",
    "Mit jelent számodra a hűség, és mely viselkedések jelentenék neked egy határ átlépését?",
    "Mit tegyünk, ha egy ideig eltér a vágyunk, és egyikünk többet szeretne, a másik kevesebbet?",
    "Hogyan szeretnéd, hogy a vágyainkról, a határainkról és az ágyban kipróbált új dolgokról beszéljünk?",
    "Ha egyikünk eltávolodik az intimitástól, hogyan reagálhatunk kíváncsisággal és törődéssel ahelyett, hogy rögtön elutasításként értelmeznénk?",
    "Mi az, aminek egy vita során akkor sem szabad megtörténnie, amikor nagyon dühösek vagyunk?",
    "Mondtál már nekem dühből olyasmit, amely inkább egy régi sebedről szólt, mint rólam?",
    "Mi az első mondat, amelyet hallani szeretnél tőlem egy veszekedés után?",
    "Mit szeretnél, mit tegyek, amikor sírsz és nem akarsz beszélni: maradjak melletted, öleljelek meg, kérdezzek vagy adjak neked teret?",
    "Mi az, amit szavakban már megbocsátottál nekem, de néha még mindig régi sebként tér vissza?",
    "Van olyan kérdés, amelyet azért félsz feltenni nekem, mert nem tudod, mit kezdenél a válasszal?",
    "Melyik oldaladat mutatod meg csak akkor, amikor teljes biztonságban érzed magad?",
    "Mit kezdtél el másképp csinálni miattam úgy, hogy én sosem kértem?",
    "Mikor érzed magad a legmélyebben kapcsolódva hozzám?",
    "Mi az a mostani közös életünkből, amire szerinted húsz év múlva is mosolyogva fogunk visszanézni?",
  ],
  es: [
    "¿Cuándo te diste cuenta de que no solo estabas enamorado o enamorada de mí, sino que me estabas eligiendo conscientemente?",
    "¿Qué momento compartido sigue haciéndote sonreír o reír cuando lo recuerdas a solas?",
    "¿Qué peculiaridad mía podría parecer extraña a los demás, pero tú has acabado queriendo?",
    "¿Qué pequeño gesto o hábito mío has adoptado sin darte cuenta?",
    "¿Qué significa para ti cuando me siento a tu lado y simplemente permanezco en silencio?",
    "¿Hay algún silencio entre nosotros que se sienta como estar en casa y otro que genere tensión? ¿Dónde está la diferencia?",
    "¿Qué me delata cuando algo no va bien, incluso antes de que yo pueda ponerle nombre?",
    "¿Qué significa para ti la palabra «hogar»: un lugar, una persona, un ritmo o algo más?",
    "¿Qué pequeño ritual nuestro puede convertir un día cualquiera entre semana en una pequeña celebración?",
    "¿Qué pregunta te gustaría que te hiciera, pero nunca te hago?",
    "¿Qué te gustaría que percibiera en ti que todavía no has dicho en voz alta?",
    "¿Qué significa para ti la fidelidad y qué comportamientos sentirías como una transgresión de los límites?",
    "¿Qué deberíamos hacer si durante un tiempo nuestros niveles de deseo son distintos y uno quiere más que el otro?",
    "¿Cómo te gustaría que habláramos del deseo, los límites y la posibilidad de probar algo diferente en la cama?",
    "Si uno de los dos se distancia de la intimidad, ¿cómo podemos responder con curiosidad y cuidado en lugar de interpretarlo inmediatamente como rechazo?",
    "¿Qué no debería ocurrir nunca durante una discusión, ni siquiera cuando estamos furiosos?",
    "¿Alguna vez me has dicho algo desde la rabia que tuviera más que ver con una herida antigua que conmigo?",
    "¿Cuál es la primera frase que quieres oír de mí después de una discusión?",
    "¿Qué quieres que haga cuando lloras y no deseas hablar: quedarme a tu lado, abrazarte, hacer preguntas o darte espacio?",
    "¿Qué me has perdonado con palabras, pero a veces todavía sientes como una vieja cicatriz?",
    "¿Hay alguna pregunta que te dé miedo hacerme porque no sabes qué harías con la respuesta?",
    "¿Qué lado de ti muestras únicamente cuando te sientes completamente a salvo?",
    "¿Qué empezaste a hacer de otra manera por mí sin que yo te lo pidiera nunca?",
    "¿Cuándo sientes una conexión más profunda conmigo?",
    "¿Qué aspecto de nosotros, tal como somos ahora, crees que seguiremos recordando con una sonrisa dentro de veinte años?",
  ],
  hr: [
    "Kada si shvatio ili shvatila da nisi samo zaljubljen ili zaljubljena u mene, nego da me svjesno biraš?",
    "Koji te naš zajednički trenutak i dalje nasmije kada ga se sjetiš dok si sam ili sama?",
    "Koju moju neobičnu osobinu drugi možda smatraju čudnom, a ti si je s vremenom zavolio ili zavoljela?",
    "Koju si moju malu gestu ili naviku nesvjesno preuzeo ili preuzela?",
    "Što ti znači kada sjednem pokraj tebe i jednostavno ostanem u tišini?",
    "Postoji li među nama tišina koja djeluje kao dom i druga koja stvara napetost? Gdje je granica između njih?",
    "Što me odaje kada nešto nije u redu, čak i prije nego što to sam ili sama uspijem imenovati?",
    "Što za tebe znači riječ „dom”: mjesto, osoba, ritam ili nešto drugo?",
    "Koji naš mali ritual može običan radni dan pretvoriti u malu proslavu?",
    "Koje bi pitanje volio ili voljela da ti postavim, ali to nikada ne učinim?",
    "Što bi volio ili voljela da primijetim kod tebe, a što još nisi izgovorio ili izgovorila naglas?",
    "Što za tebe znači vjernost i koja bi ponašanja doživio ili doživjela kao prelazak granice?",
    "Što bismo trebali učiniti ako nam se razine želje neko vrijeme razlikuju, kada jedno od nas želi više, a drugo manje?",
    "Kako bi volio ili voljela da razgovaramo o željama, granicama i isprobavanju nečeg drukčijeg u krevetu?",
    "Ako se jedno od nas povuče iz intimnosti, kako možemo reagirati sa željom da razumijemo i s pažnjom, umjesto da to odmah shvatimo kao odbijanje?",
    "Što se tijekom svađe nikada ne bi smjelo dogoditi, čak ni kada smo bijesni?",
    "Jesi li mi ikada u ljutnji rekao ili rekla nešto što se više odnosilo na staru ranu nego na mene?",
    "Koju prvu rečenicu želiš čuti od mene nakon svađe?",
    "Što želiš da učinim kada plačeš i ne želiš govoriti: da ostanem uz tebe, zagrlim te, postavljam pitanja ili ti dam prostora?",
    "Što si mi riječima oprostio ili oprostila, ali to ponekad još uvijek osjećaš poput starog ožiljka?",
    "Postoji li pitanje koje si mi se bojao ili bojala postaviti jer ne znaš što bi učinio ili učinila s odgovorom?",
    "Koju stranu sebe pokazuješ samo kada se osjećaš potpuno sigurno?",
    "Što si zbog mene počeo ili počela raditi drukčije, a da te to nikada nisam tražio ili tražila?",
    "Kada se osjećaš najdublje povezano sa mnom?",
    "Na što ćemo se iz našeg sadašnjeg života, po tvojem mišljenju, i za dvadeset godina osvrnuti s osmijehom?",
  ],
  de: [
    "Wann hast du erkannt, dass du nicht nur in mich verliebt bist, sondern dich bewusst für mich entscheidest?",
    "Welcher gemeinsame Moment bringt dich noch immer zum Lächeln oder Lachen, wenn du allein daran zurückdenkst?",
    "Welche meiner Eigenheiten finden andere vielleicht seltsam, während du sie mit der Zeit lieben gelernt hast?",
    "Welche kleine Geste oder Gewohnheit von mir hast du unbemerkt übernommen?",
    "Was bedeutet es dir, wenn ich mich neben dich setze und einfach still bei dir bleibe?",
    "Gibt es eine Stille zwischen uns, die sich wie Zuhause anfühlt, und eine andere, die Spannung erzeugt? Wo liegt die Grenze dazwischen?",
    "Woran erkennst du, dass mit mir etwas nicht stimmt, noch bevor ich es selbst benennen kann?",
    "Was bedeutet das Wort „Zuhause“ für dich: ein Ort, ein Mensch, ein Rhythmus oder etwas anderes?",
    "Welches kleine Ritual von uns kann einen gewöhnlichen Wochentag in ein kleines Fest verwandeln?",
    "Welche Frage würdest du dir von mir wünschen, die ich dir nie stelle?",
    "Was wünschst du dir, dass ich an dir bemerke, obwohl du es noch nicht laut ausgesprochen hast?",
    "Was bedeutet Treue für dich, und welche Verhaltensweisen würden sich für dich wie eine Grenzüberschreitung anfühlen?",
    "Was sollten wir tun, wenn unser Verlangen eine Zeit lang unterschiedlich stark ist, einer von uns also mehr möchte und der andere weniger?",
    "Wie möchtest du, dass wir über Verlangen, Grenzen und das Ausprobieren von etwas Neuem im Bett sprechen?",
    "Wenn einer von uns sich aus der Intimität zurückzieht, wie können wir mit Offenheit und Fürsorge reagieren, statt es sofort als Zurückweisung zu verstehen?",
    "Was darf während eines Streits niemals passieren, selbst wenn wir außer uns vor Wut sind?",
    "Hast du mir im Zorn schon einmal etwas gesagt, das mehr mit einer alten Wunde als mit mir zu tun hatte?",
    "Welchen ersten Satz möchtest du nach einem Streit von mir hören?",
    "Was soll ich tun, wenn du weinst und nicht sprechen möchtest: bei dir bleiben, dich halten, Fragen stellen oder dir Raum geben?",
    "Was hast du mir mit Worten vergeben, fühlt sich aber manchmal noch wie eine alte Narbe an?",
    "Gibt es eine Frage, die du mir aus Angst nicht gestellt hast, weil du nicht weißt, wie du mit der Antwort umgehen würdest?",
    "Welche Seite von dir zeigst du nur, wenn du dich vollkommen sicher fühlst?",
    "Was hast du meinetwegen angefangen anders zu machen, ohne dass ich dich je darum gebeten habe?",
    "Wann fühlst du dich mir am tiefsten verbunden?",
    "Worauf aus unserem heutigen gemeinsamen Leben werden wir deiner Meinung nach auch in zwanzig Jahren noch lächelnd zurückblicken?",
  ],
};

const DEEPWATER: DeckQuestions = {
  en: [
    "What is a wound of yours that you feel I may never fully understand?",
    "If your mental health seriously declined, what signs should I notice, how could I support you, and when should we involve professional help?",
    "What does “sacred” mean to you today?",
    "Do you believe in something you cannot prove?",
    "What do you think you could forgive, and what could you never forgive?",
    "If trust between us were seriously broken, what would repair require, and what might be impossible to repair?",
    "Which boundary, if crossed, would make this relationship unsafe or impossible for you to continue?",
    "What frightens you more: the possibility that choosing each other is wrong, or the responsibility that comes with it being right?",
    "What has been your most painful failure so far, and have you told me the whole story or only parts of it?",
    "Is there a moment between us that you still have not fully settled within yourself?",
    "What would we do if one of us became seriously ill while we were still young?",
    "How do you grieve, and how will I know what you need from me when you are grieving?",
    "If one of us could not make or communicate a medical decision, what would we want the other to do?",
    "How would you feel about going to couples therapy if we became stuck?",
    "What would we do if one of our beliefs, values, or worldviews changed significantly during our marriage?",
    "If our plans for parenthood changed, how would we approach fertility treatment, adoption, or a life without children?",
    "If we have a child who makes a choice one of us deeply disagrees with, how should we respond?",
    "If we have children, what part of your story would you want them to hear from you before anyone else tells it?",
    "How should we decide what to do if one of our parents or close family members needs care that changes our life?",
    "What would we do if alcohol, gambling, or another way of coping began to harm one of us or our relationship?",
    "Which values do you want our home to be known for, even by someone who visits only once?",
    "What would you promise now that you would still want to keep thirty years from today?",
    "What do you want me to keep telling you, even when I assume you already know it?",
    "What do you know for certain about me, and what is still only a hope?",
    "If we had to plan our tenth wedding anniversary today, what would you want it to look and feel like?",
  ],
  hu: [
    "Mi az a seb benned, amelyről úgy érzed, talán sosem fogom teljesen megérteni?",
    "Ha jelentősen romlana a mentális egészséged, milyen jeleket kellene észrevennem, hogyan támogathatnálak, és mikor lenne ideje szakember segítségét kérnünk?",
    "Mit jelent számodra ma az, hogy valami „szent”?",
    "Hiszel valamiben, amit nem tudsz bizonyítani?",
    "Mit gondolsz, mit tudnál megbocsátani, és mit nem tudnál soha?",
    "Ha súlyosan megtörne köztünk a bizalom, mire lenne szükség a helyreállításához, és mi lehetne helyrehozhatatlan?",
    "Melyik határ átlépése tenné számodra ezt a kapcsolatot biztonságtalanná vagy folytathatatlanná?",
    "Mi ijeszt meg jobban: annak a lehetősége, hogy rossz döntés volt egymást választanunk, vagy az a felelősség, amely azzal jár, ha jó döntést hoztunk?",
    "Mi volt eddig a legfájóbb kudarcod, és elmondtad már nekem az egész történetet, vagy csak egyes részeit?",
    "Van olyan pillanat köztünk, amelyet még mindig nem rendeztél el teljesen magadban?",
    "Mit tennénk, ha egyikünk még fiatalon súlyosan megbetegedne?",
    "Hogyan gyászolsz, és honnan fogom tudni, mire van szükséged tőlem, amikor veszteséget élsz át?",
    "Ha egyikünk nem tudna meghozni vagy közölni egy egészségügyi döntést, mit szeretnénk, mit tegyen a másik?",
    "Hogyan viszonyulnál ahhoz, hogy párterápiára menjünk, ha elakadunk?",
    "Mit tennénk, ha a házasságunk alatt egyikünk hite, értékrendje vagy világnézete jelentősen megváltozna?",
    "Ha megváltoznának a szülővé válással kapcsolatos terveink, hogyan viszonyulnánk a meddőségi kezelésekhez, az örökbefogadáshoz vagy a gyermek nélküli élethez?",
    "Ha lenne gyermekünk, aki olyan döntést hoz, amellyel egyikünk mélyen nem ért egyet, hogyan reagáljunk?",
    "Ha lennének gyerekeink, a történeted melyik részét szeretnéd, hogy tőled hallják először, mielőtt bárki más mesélne róla?",
    "Hogyan döntsük el, mit tegyünk, ha valamelyik szülőnknek vagy közeli családtagunknak olyan gondoskodásra lenne szüksége, amely megváltoztatja az életünket?",
    "Mit tennénk, ha az alkohol, a szerencsejáték vagy más megküzdési szokás ártani kezdene egyikünknek vagy a kapcsolatunknak?",
    "Mely értékeket szeretnéd, hogy még az is érezze az otthonunkban, aki csak egyszer jár nálunk?",
    "Mit ígérnél meg most, amit harminc év múlva is meg szeretnél tartani?",
    "Mit szeretnéd, hogy újra és újra elmondjak neked, még akkor is, amikor azt hiszem, már úgyis tudod?",
    "Mi az, amit biztosan tudsz rólam, és mi az, ami még csak remény?",
    "Ha ma kellene megterveznünk a tizedik házassági évfordulónkat, milyennek szeretnéd?",
  ],
  es: [
    "¿Qué herida tuya sientes que quizá nunca llegue a comprender del todo?",
    "Si tu salud mental empeorara seriamente, ¿qué señales debería observar, cómo podría apoyarte y cuándo deberíamos recurrir a ayuda profesional?",
    "¿Qué significa hoy para ti que algo sea «sagrado»?",
    "¿Crees en algo que no puedes demostrar?",
    "¿Qué crees que podrías perdonar y qué no podrías perdonar nunca?",
    "Si la confianza entre nosotros se rompiera seriamente, ¿qué haría falta para repararla y qué podría resultar imposible de reparar?",
    "¿Qué límite, si se cruzara, haría que esta relación dejara de ser segura o posible para ti?",
    "¿Qué te asusta más: la posibilidad de que elegirnos sea un error o la responsabilidad que implica que sea la decisión correcta?",
    "¿Cuál ha sido hasta ahora tu fracaso más doloroso y me has contado toda la historia o solo algunas partes?",
    "¿Hay algún momento entre nosotros que todavía no hayas terminado de resolver en tu interior?",
    "¿Qué haríamos si uno de los dos enfermara gravemente cuando todavía somos jóvenes?",
    "¿Cómo vives el duelo y cómo sabré qué necesitas de mí cuando estés atravesando una pérdida?",
    "Si uno de los dos no pudiera tomar o comunicar una decisión médica, ¿qué querríamos que hiciera el otro?",
    "¿Cómo te sentirías ante la posibilidad de acudir a terapia de pareja si llegáramos a un punto muerto?",
    "¿Qué haríamos si durante nuestro matrimonio las creencias, los valores o la visión del mundo de uno de los dos cambiaran significativamente?",
    "Si nuestros planes respecto a tener hijos cambiaran, ¿cómo abordaríamos los tratamientos de fertilidad, la adopción o una vida sin hijos?",
    "Si tenemos un hijo o una hija que toma una decisión con la que uno de los dos está profundamente en desacuerdo, ¿cómo deberíamos responder?",
    "Si tenemos hijos, ¿qué parte de tu historia querrías que escucharan primero de ti, antes de que se la contara otra persona?",
    "¿Cómo deberíamos decidir qué hacer si uno de nuestros padres o familiares cercanos necesitara cuidados que cambiaran nuestra vida?",
    "¿Qué haríamos si el alcohol, el juego u otra forma de afrontar los problemas empezara a perjudicar a uno de los dos o a nuestra relación?",
    "¿Por qué valores te gustaría que se reconociera nuestro hogar, incluso por alguien que solo nos visitara una vez?",
    "¿Qué prometerías ahora que seguirías queriendo cumplir dentro de treinta años?",
    "¿Qué quieres que siga diciéndote incluso cuando yo dé por hecho que ya lo sabes?",
    "¿Qué sabes con certeza sobre mí y qué sigue siendo solo una esperanza?",
    "Si hoy tuviéramos que planear nuestro décimo aniversario de boda, ¿cómo te gustaría que fuera y qué sensación te gustaría que transmitiera?",
  ],
  hr: [
    "Koja je tvoja rana za koju osjećaš da je možda nikada neću potpuno razumjeti?",
    "Kada bi se tvoje mentalno zdravlje ozbiljno pogoršalo, koje bih znakove trebao ili trebala primijetiti, kako bih ti mogao ili mogla pružiti podršku i kada bismo trebali potražiti stručnu pomoć?",
    "Što za tebe danas znači da je nešto „sveto“?",
    "Vjeruješ li u nešto što ne možeš dokazati?",
    "Što misliš da bi mogao ili mogla oprostiti, a što nikada ne bi mogao ili mogla oprostiti?",
    "Kada bi povjerenje među nama bilo ozbiljno narušeno, što bi bilo potrebno da ga obnovimo i što bi možda bilo nemoguće popraviti?",
    "Prelazak koje bi granice za tebe ovu vezu učinio nesigurnom ili nemogućom za nastavak?",
    "Što te više plaši: mogućnost da je naš izbor pogrešan ili odgovornost koja dolazi s time da je ispravan?",
    "Koji je dosad bio tvoj najbolniji neuspjeh i jesi li mi ispričao ili ispričala cijelu priču ili samo njezine dijelove?",
    "Postoji li trenutak među nama koji još uvijek nisi potpuno razriješio ili razriješila u sebi?",
    "Što bismo učinili kada bi se jedno od nas ozbiljno razboljelo još u mladosti?",
    "Kako tuguješ i kako ću znati što ti treba od mene kada prolaziš kroz žalovanje?",
    "Kada jedno od nas ne bi moglo donijeti ili priopćiti medicinsku odluku, što bismo željeli da druga osoba učini?",
    "Kako bi se osjećao ili osjećala u vezi s odlaskom na partnersku terapiju kada bismo zapeli?",
    "Što bismo učinili kada bi se tijekom našeg braka uvjerenja, vrijednosti ili pogled na svijet jednog od nas znatno promijenili?",
    "Ako bi se naši planovi o roditeljstvu promijenili, kako bismo pristupili liječenju neplodnosti, posvojenju ili životu bez djece?",
    "Ako budemo imali dijete koje donese odluku s kojom se jedno od nas duboko ne slaže, kako bismo trebali reagirati?",
    "Ako budemo imali djecu, koji bi dio svoje priče želio ili željela da prvo čuju od tebe, prije nego što im ga ispriča netko drugi?",
    "Kako ćemo odlučiti što učiniti ako jednom od naših roditelja ili bliskih članova obitelji bude potrebna skrb koja mijenja naš život?",
    "Što bismo učinili kada bi alkohol, kockanje ili neki drugi način nošenja s teškoćama počeo štetiti jednom od nas ili našoj vezi?",
    "Po kojim bi vrijednostima želio ili željela da naš dom bude poznat, čak i nekome tko nas posjeti samo jednom?",
    "Što bi obećao ili obećala sada, a što bi i za trideset godina još uvijek želio ili željela održati?",
    "Što želiš da ti nastavim govoriti čak i kada pretpostavim da to već znaš?",
    "Što o meni znaš sa sigurnošću, a što je još uvijek samo nada?",
    "Kada bismo danas morali isplanirati desetu godišnjicu braka, kako bi želio ili željela da izgleda i kakav bi osjećaj trebala pružiti?",
  ],
  de: [
    "Welche deiner Wunden werde ich deiner Meinung nach vielleicht nie ganz verstehen?",
    "Wenn sich deine psychische Gesundheit deutlich verschlechtern würde: Auf welche Anzeichen sollte ich achten, wie könnte ich dich unterstützen und wann sollten wir professionelle Hilfe hinzuziehen?",
    "Was bedeutet „heilig“ heute für dich?",
    "Glaubst du an etwas, das du nicht beweisen kannst?",
    "Was könntest du deiner Meinung nach vergeben, und was niemals?",
    "Wenn das Vertrauen zwischen uns schwer beschädigt würde: Was wäre nötig, um es wiederherzustellen, und was ließe sich vielleicht nicht mehr reparieren?",
    "Welche Grenzüberschreitung würde diese Beziehung für dich unsicher machen oder dazu führen, dass du sie nicht weiterführen könntest?",
    "Was macht dir mehr Angst: die Möglichkeit, dass unsere Entscheidung füreinander falsch ist, oder die Verantwortung, die damit einhergeht, dass sie richtig ist?",
    "Was war bisher dein schmerzhaftester Misserfolg, und hast du mir die ganze Geschichte erzählt oder nur Teile davon?",
    "Gibt es einen Moment zwischen uns, den du innerlich noch nicht vollständig verarbeitet hast?",
    "Was würden wir tun, wenn einer von uns schon in jungen Jahren schwer erkranken würde?",
    "Wie trauerst du, und woran werde ich erkennen, was du in deiner Trauer von mir brauchst?",
    "Wenn einer von uns eine medizinische Entscheidung nicht treffen oder mitteilen könnte, was sollte der andere dann tun?",
    "Wie würdest du dazu stehen, eine Paartherapie zu beginnen, wenn wir nicht mehr weiterkommen?",
    "Was würden wir tun, wenn sich die Überzeugungen, Werte oder die Weltanschauung eines von uns während unserer Ehe deutlich verändern würden?",
    "Wenn sich unsere Pläne für eine Elternschaft ändern würden: Wie würden wir mit Kinderwunschbehandlungen, Adoption oder einem Leben ohne Kinder umgehen?",
    "Wenn wir ein Kind haben, das eine Entscheidung trifft, mit der einer von uns überhaupt nicht einverstanden ist, wie sollten wir reagieren?",
    "Falls wir Kinder haben: Welchen Teil deiner Geschichte sollen sie zuerst von dir hören, bevor jemand anderes davon erzählt?",
    "Wie entscheiden wir, was zu tun ist, wenn ein Elternteil oder naher Angehöriger Pflege braucht, die unser Leben verändert?",
    "Was würden wir tun, wenn Alkohol, Glücksspiel oder eine andere Art, mit Problemen umzugehen, einem von uns oder unserer Beziehung zu schaden begänne?",
    "Für welche Werte soll unser Zuhause stehen, selbst für jemanden, der uns nur ein einziges Mal besucht?",
    "Was würdest du heute versprechen, das du auch in dreißig Jahren noch halten möchtest?",
    "Was soll ich dir immer wieder sagen, selbst wenn ich davon ausgehe, dass du es längst weißt?",
    "Was weißt du mit Sicherheit über mich, und was ist bisher nur eine Hoffnung?",
    "Wenn wir heute unseren zehnten Hochzeitstag planen müssten: Wie sollte er aussehen und sich anfühlen?",
  ],
};

const LEMONADE: DeckQuestions = {
  en: [
    "What would our perfect Saturday morning look like?",
    "Which film would be the perfect cosy-night movie for us?",
    "Which song would we absolutely nail at karaoke?",
    "Which meal tastes most like home when we cook it together?",
    "If we could have one shared superpower, what would it be?",
    "Which animal are you in this relationship, and which animal am I?",
    "What would our perfect date night look like?",
    "If you had to give us a nickname as a duo, what would it be?",
    "If we both had tomorrow off, how would we spend the day?",
    "Which scent always reminds you of me?",
    "What made us laugh the hardest recently?",
    "If we went to a costume party together, what would we dress up as?",
    "Which everyday moment with me feels quietly romantic?",
    "Where would we escape for a weekend, just the two of us?",
    "Which season feels most like us?",
    "Which little morning ritual of ours would you never want to lose?",
    "What is our ultimate comfort-food order?",
    "Which series would you love for us to start together from the beginning?",
    "Which place from your childhood would you most love to show me?",
    "What is your favourite memory from our first trip together, or what do you imagine it will be if we have not taken one yet?",
    "If we could have a little place anywhere in the world, where would it be?",
    "Which photo of us feels most like us?",
    "If we adopted a dog or a cat, what would we name them?",
    "What is something silly that only the two of us understand?",
    "What is the silliest argument we have ever had and can still laugh about?",
  ],
  hu: [
    "Milyen lenne a tökéletes közös szombat reggelünk?",
    "Melyik film lenne a tökéletes választás egy közös, bekuckózós estére?",
    "Melyik dalt adnánk elő hibátlanul karaokén?",
    "Melyik étel íze jelenti nekünk leginkább az otthont, amikor együtt főzzük?",
    "Ha lehetne egy közös szupererőnk, mi lenne az?",
    "Te milyen állat lennél ebben a kapcsolatban, és én milyen állat lennék?",
    "Milyen lenne a tökéletes közös randiesténk?",
    "Ha becenevet kellene adnod nekünk mint párosnak, mi lenne az?",
    "Ha holnap mindketten szabadok lennénk, hogyan töltenénk a napot?",
    "Melyik illat juttat mindig engem eszedbe?",
    "Min nevettünk mostanában a legnagyobbat?",
    "Ha együtt mennénk jelmezbálba, minek öltöznénk?",
    "Melyik közös hétköznapi pillanatunkban van valami csendes romantika?",
    "Hová szöknénk el egy hétvégére, csak mi ketten?",
    "Melyik évszak illik hozzánk a legjobban?",
    "Melyik apró reggeli szokásunkat nem szeretnéd soha elveszíteni?",
    "Mi a kedvenc bekuckózós kajarendelésünk?",
    "Melyik sorozatot kezdenéd el velem szívesen az elejétől?",
    "Gyerekkorod melyik helyét mutatnád meg nekem a legszívesebben?",
    "Mi a kedvenc emléked az első közös utazásunkról, vagy milyennek képzeled az első közös utazásunkat, ha még nem volt ilyen?",
    "Ha lehetne egy kis közös helyünk bárhol a világon, hol lenne?",
    "Melyik közös fotónk a leginkább mi?",
    "Ha örökbe fogadnánk egy kutyát vagy macskát, milyen nevet adnánk neki?",
    "Mi az a butaság vagy belső poén, amelyet csak mi ketten értünk?",
    "Mi volt a legbutább vitánk, amelyen még mindig tudunk nevetni?",
  ],
  es: [
    "¿Cómo sería nuestra mañana de sábado perfecta?",
    "¿Qué película sería perfecta para una noche acogedora juntos?",
    "¿Qué canción bordaríamos en un karaoke?",
    "¿Qué comida sabe más a hogar cuando la cocinamos juntos?",
    "Si pudiéramos tener un superpoder compartido, ¿cuál sería?",
    "¿Qué animal eres tú en esta relación y qué animal soy yo?",
    "¿Cómo sería nuestra cita nocturna perfecta?",
    "Si tuvieras que ponernos un apodo como dúo, ¿cuál sería?",
    "Si mañana los dos tuviéramos el día libre, ¿cómo lo pasaríamos?",
    "¿Qué aroma te recuerda siempre a mí?",
    "¿Qué es lo que más nos ha hecho reír últimamente?",
    "Si fuéramos juntos a una fiesta de disfraces, ¿de qué nos disfrazaríamos?",
    "¿Qué momento cotidiano conmigo te parece discretamente romántico?",
    "¿Adónde nos escaparíamos un fin de semana, solo nosotros dos?",
    "¿Qué estación del año se parece más a nosotros?",
    "¿Qué pequeño ritual matutino nuestro no querrías perder nunca?",
    "¿Qué comida pedimos siempre cuando necesitamos algo reconfortante?",
    "¿Qué serie te encantaría que empezáramos juntos desde el principio?",
    "¿Qué lugar de tu infancia te gustaría más enseñarme?",
    "¿Cuál es tu recuerdo favorito de nuestro primer viaje juntos o cómo imaginas que será si todavía no hemos hecho ninguno?",
    "Si pudiéramos tener un pequeño lugar propio en cualquier parte del mundo, ¿dónde estaría?",
    "¿Qué foto nuestra refleja mejor quiénes somos juntos?",
    "Si adoptáramos un perro o un gato, ¿qué nombre le pondríamos?",
    "¿Qué tontería entendemos únicamente nosotros dos?",
    "¿Cuál ha sido la discusión más absurda que hemos tenido y de la que todavía podemos reírnos?",
  ],
  hr: [
    "Kako bi izgledalo naše savršeno subotnje jutro?",
    "Koji bi film bio savršen za našu ugodnu večer kod kuće?",
    "Koju bismo pjesmu briljantno izveli na karaokama?",
    "Koje nam jelo, kada ga kuhamo zajedno, najviše ima okus doma?",
    "Kada bismo mogli imati jednu zajedničku supermoć, koja bi to bila?",
    "Koju životinju predstavljaš ti u ovoj vezi, a koju ja?",
    "Kako bi izgledao naš savršen večernji spoj?",
    "Kada bi nam kao paru morao ili morala dati nadimak, koji bi to bio?",
    "Kada bismo sutra oboje imali slobodan dan, kako bismo ga proveli?",
    "Koji te miris uvijek podsjeti na mene?",
    "Što nas je u posljednje vrijeme najviše nasmijalo?",
    "Kada bismo zajedno išli na kostimiranu zabavu, u što bismo se odjenuli?",
    "Koji ti se svakodnevni trenutak sa mnom čini tiho romantičnim?",
    "Kamo bismo pobjegli na vikend, samo nas dvoje?",
    "Koje godišnje doba najviše nalikuje nama?",
    "Koji naš mali jutarnji ritual nikada ne bi želio ili željela izgubiti?",
    "Koju hranu najradije naručujemo kada nam treba nešto utješno?",
    "Koju bi seriju volio ili voljela da zajedno počnemo gledati od prve epizode?",
    "Koje bi mi mjesto iz svojeg djetinjstva najradije pokazao ili pokazala?",
    "Koja ti je najdraža uspomena s našeg prvog zajedničkog putovanja ili kako ga zamišljaš ako još nismo putovali zajedno?",
    "Kada bismo mogli imati svoje malo mjesto bilo gdje na svijetu, gdje bi ono bilo?",
    "Koja naša fotografija najviše djeluje kao „mi“?",
    "Kada bismo udomili psa ili mačku, koje bismo mu ime dali?",
    "Koja je to luckasta stvar koju razumijemo samo nas dvoje?",
    "Koja je bila naša najblesavija svađa kojoj se još uvijek možemo smijati?",
  ],
  de: [
    "Wie sähe unser perfekter Samstagmorgen aus?",
    "Welcher Film wäre perfekt für einen gemütlichen Abend zu zweit?",
    "Welchen Song würden wir beim Karaoke richtig gut hinbekommen?",
    "Welches Gericht schmeckt am meisten nach Zuhause, wenn wir es gemeinsam kochen?",
    "Wenn wir eine gemeinsame Superkraft haben könnten, welche wäre es?",
    "Welches Tier bist du in dieser Beziehung, und welches Tier bin ich?",
    "Wie sähe unser perfekter gemeinsamer Date-Abend aus?",
    "Wenn du uns als Duo einen Spitznamen geben müsstest, welcher wäre es?",
    "Wenn wir morgen beide frei hätten, wie würden wir den Tag verbringen?",
    "Welcher Duft erinnert dich immer an mich?",
    "Worüber haben wir in letzter Zeit am meisten gelacht?",
    "Wenn wir gemeinsam auf eine Kostümparty gingen, als was würden wir uns verkleiden?",
    "Welcher alltägliche Moment mit mir fühlt sich auf leise Weise romantisch an?",
    "Wohin würden wir für ein Wochenende fliehen, nur wir beide?",
    "Welche Jahreszeit fühlt sich am meisten nach uns an?",
    "Welches kleine Morgenritual von uns möchtest du niemals verlieren?",
    "Was bestellen wir am liebsten, wenn wir richtiges Wohlfühlessen brauchen?",
    "Welche Serie würdest du gern mit mir ganz von vorn anfangen?",
    "Welchen Ort aus deiner Kindheit würdest du mir am liebsten zeigen?",
    "Was ist deine schönste Erinnerung an unsere erste gemeinsame Reise, oder wie stellst du sie dir vor, falls wir noch keine gemacht haben?",
    "Wenn wir irgendwo auf der Welt ein kleines gemeinsames Zuhause haben könnten, wo wäre es?",
    "Welches Foto von uns fühlt sich am meisten nach uns an?",
    "Wenn wir einen Hund oder eine Katze adoptieren würden, welchen Namen würden wir ihm oder ihr geben?",
    "Welche alberne Sache verstehen nur wir beide?",
    "Was war unser albernster Streit, über den wir heute noch lachen können?",
  ],
};

export const COUPLE_CARD_DECKS: readonly Deck[] = [
  {
    id: "firstdate",
    titleKey: "tools.couple_cards.deck_firstdate_title",
    blurbKey: "tools.couple_cards.deck_firstdate_blurb",
    questions: FIRSTDATE,
  },
  {
    id: "roots",
    titleKey: "tools.couple_cards.deck_roots_title",
    blurbKey: "tools.couple_cards.deck_roots_blurb",
    questions: ROOTS,
  },
  {
    id: "everyday",
    titleKey: "tools.couple_cards.deck_everyday_title",
    blurbKey: "tools.couple_cards.deck_everyday_blurb",
    questions: EVERYDAY,
  },
  {
    id: "closeness",
    titleKey: "tools.couple_cards.deck_closeness_title",
    blurbKey: "tools.couple_cards.deck_closeness_blurb",
    questions: CLOSENESS,
  },
  {
    id: "deepwater",
    titleKey: "tools.couple_cards.deck_deepwater_title",
    blurbKey: "tools.couple_cards.deck_deepwater_blurb",
    questions: DEEPWATER,
  },
  // Hidden easter-egg deck: a playful pack, only revealed after the visitor
  // swipes horizontally across the mini-deck row. Stays in this array
  // unconditionally so the data shape stays simple; the gating lives in
  // CoupleCardsPage state.
  {
    id: "lemonade",
    titleKey: "tools.couple_cards.deck_lemonade_title",
    blurbKey: "tools.couple_cards.deck_lemonade_blurb",
    questions: LEMONADE,
  },
];

export const DECK_SIZE = 25;

/** The card list to show a visitor. Falls back to EN when a locale's array
 *  is missing or empty, the same per-key degradation `t()` applies to UI
 *  copy: a half-translated deck reads as English rather than as blanks. */
export function deckQuestions(deck: Deck, locale: UiLocale): readonly string[] {
  const list = deck.questions[locale];
  if (list && list.length > 0) return list;
  return deck.questions.en;
}

/** A deck is playable once its cards have landed. Asked of EN because EN is
 *  what every other locale falls back to. */
export function deckHasCards(deck: Deck): boolean {
  return deck.questions.en.length > 0;
}

/** Every locale a deck carries cards in, in switcher order. Exported for
 *  the admin feedback triage, which has to look a vote's snapshot up by the
 *  locale the visitor was reading in. */
export const CARD_LOCALES: readonly UiLocale[] = UI_LOCALES;

// The numbered "Level 1-4" red decks, in fixed order. Accent decks
// (firstdate, lemonade) sit outside this set: firstdate is the hidden
// first-date pack tucked off the LEFT edge of the deck row, lemonade the
// playful pack off the RIGHT. Both render with their own palette
// and a name instead of a Level number.
export const RED_DECK_ORDER: readonly DeckId[] = ["roots", "everyday", "closeness", "deepwater"];

export function isAccentDeck(id: DeckId): boolean {
  return id === "firstdate" || id === "lemonade";
}

/** 1-based Level number for a red deck; 0 for accent decks. */
export function redLevel(id: DeckId): number {
  return RED_DECK_ORDER.indexOf(id) + 1;
}

/** Easter-egg lemonade reveal is intentionally session-ephemeral: every
 *  fresh page load starts back at "hidden" so the visitor has to re-
 *  discover the swipe. We keep the load/save helpers exported and the
 *  legacy localStorage key around so both surfaces (landing teaser +
 *  tool page) share the same wiring, but persistence is now a no-op.
 *  If we ever want a one-time discovery (visit-A unlocks → visit-B sees
 *  it), wiring it back into localStorage is the obvious place. */
export const LEMONADE_REVEAL_KEY = "weddly.couple_cards.lemonade_revealed";

export function loadLemonadeRevealed(): boolean {
  // Always start hidden: the swipe is the unlock. No-op localStorage
  // read keeps the easter egg feeling like an easter egg.
  if (typeof window !== "undefined") {
    try {
      // Clear any leftover persisted flag from the previous behaviour so
      // returning visitors actually re-experience the hidden state.
      window.localStorage.removeItem(LEMONADE_REVEAL_KEY);
    } catch {
      // localStorage blocked: nothing to clean up anyway.
    }
  }
  return false;
}

export function saveLemonadeRevealed(): void {
  // Intentionally a no-op: reveals don't persist across reloads, see
  // `loadLemonadeRevealed` for the why.
}
